---
kind: pipeline
type: ssh
name: update

trigger:
  branch:
  - update_home_assistant

server:
  host: 192.168.178.5
  user: pi
  ssh_key:
    from_secret: SSH_KEY

steps:
- name: prepare
  environment:
    TOKEN:
      from_secret: token
    URL:
      from_secret: url
  commands:
    - >
      curl -X POST -H "Authorization: Bearer $TOKEN" -H 'Content-Type: application/json' -d '{"entity_id": "script.prepare_restart"}' https://$URL:8123/api/services/script/turn_on

- name: restart
  commands:
  - cd /opt/configurations/docker-compose/homeassistant
  - docker-compose pull
  - docker-compose down
  - docker-compose up -d

- name: clean
  commands:
  - cd /opt/configurations/docker-compose/homeassistant
  - docker image prune -f
  - docker container prune -f 
