sudo: required

services:
  - docker

before_install:
  - mv travis_secrets.yaml secrets.yaml

script:
  - docker-compose -f testing/docker-compose.yml up

after_script:
  - docker-compose -f testing/docker-compose.yml down