homeassistant:
  # Name of the location where Home Assistant is running
  name: Frankfurt

  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude_value
  longitude: !secret longitude_value
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 107

  # metric for Metric, imperial for Imperial
  unit_system: metric
  
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Berlin

  customize: !include includes/customize.yaml

logger:
  default: warning

recorder:
  db_url: !secret mysql_path
# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  api_password: !secret http_password
  base_url: !secret base_url
  ssl_certificate: !secret ssl_certificate_path        
  ssl_key: !secret ssl_private_key
  ip_ban_enabled: True
  login_attempts_threshold: 3

# Checks for available updates
updater:

# Discover some devices automatically
discovery:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Support for iOS app
ios:

# iOS notification
notify:
  platform: ios
  name: ios_app
  target: !secret ios_token

  #- platform: telegram
  #  name: telegram
  #  api_key: !secret telegram_api_key
  #  chat_id: !secret telegram_chat_id

# Presence Detection
device_tracker:
  - platform: fritz
    host: !secret fritz_host
    password: !secret fritz_password
    track_new_devices: false 
  - platform: bluetooth_tracker

# Track the sun
sun:

media_player:
  - platform: plex

  - platform: apple_tv
    name: AppleTV
    host: atv.cbs-service.net
    login_id: !secret atv_login

netatmo:
  api_key: !secret netatmo_api_key
  secret_key: !secret netatmo_secret_key
  username: !secret netatmo_username
  password: !secret netatmo_password
 

input_select:
  tv_mode:
    name: 'TV mode'
    options:
     - INIT
     - AUS
     - TV
     - AppleTV
     - Plex
     - FireTV
     - Music
    initial: INIT
    icon: mdi:television
  log_level:
    name: 'Log Level'
    options:
      - critical
      - fatal
      - error
      - warning
      - warn
      - info
      - debug
      - notset
    initial: warn

input_slider:
  appletv_delay:
    name: AppleTV Delay
    initial: 10
    min: 0
    max: 10
    step: 1


tradfri:
  host: 192.168.178.52
  api_key: !secret tradfri_api_key

# plant:
#   bad:
#     sensors:
#       moisture: sensor.bad_moisture
#       battery: sensor.bad_battery
#       temperature: sensor.bad_temperature
#       conductivity: sensor.bad_conductivity
#       brightness: sensor.bad_light_intensity
#     min_moisture: 20
#     max_moisture: 60
#     min_battery: 17
#     min_conductivity: 500
#     min_temperature: 15

zone 1:
  name: Work Sascha
  latitude: !secret lat_zone_1 
  longitude: !secret long_zone_1 

zone 2:
  name: Work Nicole
  latitude: !secret lat_zone_2 
  longitude: !secret long_zone_2 

zone 3:
  name: Home Nicole
  latitude: !secret lat_zone_3 
  longitude: !secret long_zone_3

##########################
# Includes
##########################

sensor: !include includes/sensors.yaml
binary_sensor: !include includes/binary_sensor.yaml
automation: !include_dir_merge_list automation/
#automation: !include includes/automations.yaml
script: !include includes/scripts.yaml
group: !include includes/groups.yaml
switch: !include includes/switch.yaml
scene: !include includes/scenes.yaml
input_boolean: !include includes/inputs.yaml
shell_command: !include includes/shell_commands.yaml