homeassistant:
  # Name of the location where Home Assistant is running
  name: Frankfurt

  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude_value
  longitude: !secret longitude_value
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 107

  # metric for Metric, imperial for Imperial
  unit_system: metric

  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Berlin

  customize: !include includes/customize.yaml
  packages: !include_dir_named packages

  auth_providers:
    - type: homeassistant

config:

logger:
  default: error

mqtt:
  broker: !secret mqtt_broker_ip
  username: owntracks
  password: !secret mqtt_password
  protocol: 3.1
  port: 1883
  discovery: true
  birth_message:
    topic: "hass/status"
    payload: "online"
  will_message:
    topic: "hass/status"
    payload: "offline"

map:

system_health:

# influxdb:
#  host: !secret influxdb_ip
#  username: homeassistant
#  password: !secret influxdb_password
#  max_retries: 10
#  include:
#    domains:
#      - sensor
#      - binary_sensor

recorder:
  db_url: !secret mysql_path
  purge_keep_days: 5
  include: !include includes/include.yaml
  exclude: !include includes/exclude.yaml

# View all events in a logbook
logbook:
  include: !include includes/include.yaml
  exclude: !include includes/exclude.yaml

http:
  ssl_certificate: !secret ssl_certificate_path
  ssl_key: !secret ssl_private_key
  ip_ban_enabled: false
  login_attempts_threshold: 3

# Discover some devices automatically
discovery:

# Enables support for tracking state changes over time.
history:

# Support for iOS app
ios:

owntracks:
  max_gps_accuracy: 100

# Track the sun
sun:

input_number:
  sonos_speaker:
    name: Volume
    initial: 0.1
    min: 0
    max: 1
    step: 0.01

vacuum:
  platform: xiaomi_miio
  name: "Vacuum Cleaner"
  host: !secret robo_ip
  token: !secret mirobo_token

# fan:
#   platform: xiaomi_miio_fan
#   name: Fan
#   host: 192.168.178.38
#   token: !secret fan_token

zone:
  - name: Work User 1
    latitude: !secret lat_zone_1
    longitude: !secret long_zone_1

  - name: Work User 2
    latitude: !secret lat_zone_2
    longitude: !secret long_zone_2

person:
  - name: !secret user_1
    id: user_1
    device_trackers:
      - device_tracker.batphone
      - device_tracker.batphone_app
  - name: !secret user_2
    id: user_2
    device_trackers:
      - device_tracker.user_2_iphone
      # - device_tracker.user_2_iphone_app

notify:
  - name: devices_user_1
    platform: group
    services:
      - service: mobile_app_batphone
      - service: mobile_app_batmac


##########################
# Includes
##########################

sensor: !include includes/sensors.yaml
binary_sensor: !include includes/binary_sensor.yaml
automation: !include_dir_merge_list automation/
script: !include includes/scripts.yaml
group: !include includes/groups.yaml
switch: !include includes/switch.yaml
input_boolean: !include includes/inputs.yaml
shell_command: !include includes/shell_commands.yaml
light: !include includes/lights.yaml
homekit: !include includes/homekit.yaml
input_select: !include includes/input_select.yaml
cover: !include includes/cover.yaml
alarm_control_panel: !include includes/alarm_control_panel.yaml
