homeassistant:
  # Name of the location where Home Assistant is running
  name: Frankfurt

  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude_value
  longitude: !secret longitude_value
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 107

  # metric for Metric, imperial for Imperial
  unit_system: metric
  
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Berlin

  customize: !include includes/customize.yaml

logger:
  default: warning
  logs:
    # Hide botvac connexion errors which happen sometimes:
    homeassistant.components.vacuum: error
    miio.device: critical

mqtt:
  broker: hass.cbs-service.net
  username: owntracks
  password: !secret mqtt_password
  protocol: 3.1
  port: 1883

map:

recorder:
  db_url: !secret mysql_path
  purge_interval: 2
  purge_keep_days: 5
  exclude:
    entities:
      - sensor.netatmo
      - sensor.netatmo_outdoor_radio
      - sensor.netatmo_schlafzimmer_radio
      - sensor.dark_sky_summary
      - sensor.dark_sky_hourly_summary
      - device_tracker.netatmo
      - device_tracker.server
      - device_tracker.wohnzimmer
      - device_tracker.appletv
      - device_tracker.tradfri
      - device_tracker.switch
      - device_tracker.plex
      - device_tracker.broadlink
      - device_tracker.epson029ea9
      - device_tracker.batplay1
      - light.kuche1
      - light.kuche2
      - light.eingang
      - sensor.tribunexhome_assistant_last_build_duration
      - sensor.tribunexhome_assistant_last_build_finished_at
      - sensor.tribunexhome_assistant_last_build_id
      - sensor.tribunexhome_assistant_last_build_started_at
      - sensor.tribunexhome_assistant_last_build_state


# Enables the frontend
frontend:
  javascript_version: latest

# Enables configuration UI
config:

http:
  api_password: !secret http_password
  base_url: !secret base_url
  ssl_certificate: !secret ssl_certificate_path        
  ssl_key: !secret ssl_private_key
  ip_ban_enabled: True
  login_attempts_threshold: 3

# Checks for available updates
updater:

# Discover some devices automatically
discovery:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:
  exclude:
    entities:
      - sensor.netatmo
      - sensor.netatmo_outdoor_radio
      - sensor.netatmo_schlafzimmer_radio
      - sensor.dark_sky_summary
      - sensor.dark_sky_hourly_summary
      - device_tracker.netatmo
      - device_tracker.server
      - device_tracker.wohnzimmer
      - device_tracker.appletv
      - device_tracker.tradfri
      - device_tracker.switch
      - device_tracker.plex
      - device_tracker.broadlink
      - device_tracker.epson029ea9
      - device_tracker.batplay1
      - light.kuche1
      - light.kuche2
      - light.eingang
      - sensor.tribunexhome_assistant_last_build_duration
      - sensor.tribunexhome_assistant_last_build_finished_at
      - sensor.tribunexhome_assistant_last_build_id
      - sensor.tribunexhome_assistant_last_build_started_at
      - sensor.tribunexhome_assistant_last_build_state


# Support for iOS app
ios:

# iOS notification
notify:
  platform: ios
  name: ios_app
  target: !secret ios_token

  #- platform: telegram
  #  name: telegram
  #  api_key: !secret telegram_api_key
  #  chat_id: !secret telegram_chat_id

# Presence Detection
device_tracker:
  - platform: fritz
    host: !secret fritz_host
    password: !secret fritz_password
    track_new_devices: false 
  - platform: owntracks
    max_gps_accuracy: 100
  #- platform: bluetooth_tracker

# Track the sun
sun:

media_player:
  - platform: apple_tv
    host: atv.cbs-service.net
    login_id: !secret atv_login
    credentials: !secret atv_credentials
  - platform: apple_tv
    host: atv2.cbs-service.net
    login_id: !secret atv_login
    credentials: !secret atv2_credentials

  - platform: sonos

  # - platform: spotify
  #   client_id: !secret spotify_client_id
  #   client_secret: !secret spotify_client_secret

netatmo:
  api_key: !secret netatmo_api_key
  secret_key: !secret netatmo_secret_key
  username: !secret netatmo_username
  password: !secret netatmo_password


input_select:
  tv_mode:
    name: 'TV mode'
    options:
     - AUS
     - TV
     - AppleTV
     - Plex
     - Music
    initial: AUS
    icon: mdi:television
  sonos_source:
    name: Sonos Source
    options:
      - Hits (Sascha)
      - Fidi & Bumsi
      - HIT RADIO FFH
      - ANTENNE BAYERN
      - Christmas
      - Soundtracks
      - SELECT
    initial: SELECT
    icon: mdi:radio
  log_level:
    name: 'Log Level'
    options:
      - critical
      - fatal
      - error
      - warning
      - warn
      - info
      - debug
      - notset
    initial: error

input_number:
  sonos_speaker:
    name: Volume
    initial: 0.1
    min: 0
    max: 1
    step: 0.01

tradfri:
  host: 192.168.178.52
  allow_tradfri_groups: true

xiaomi_aqara:
  discovery_retry: 5
  gateways:
    - key: !secret aqara_token

vacuum:
  platform: xiaomi_miio 
  name: Staubsauger
  host: robo.cbs-service.net
  token: !secret mirobo_token

tts:
  - platform: google
    language: 'de'

zone 1:
  name: Work Sascha
  latitude: !secret lat_zone_1 
  longitude: !secret long_zone_1 

zone 2:
  name: Work Nicole
  latitude: !secret lat_zone_2 
  longitude: !secret long_zone_2 

# zone 4:
#   name: Sofa
#   latitude: !secret latitude_value
#   longitude: !secret longitude_value

zone 4:
  name: Bedroom
  radius: 5
  passive: true
  latitude: !secret latitude_value
  longitude: !secret longitude_value

##########################
# Includes
##########################

sensor: !include includes/sensors.yaml
binary_sensor: !include includes/binary_sensor.yaml
automation: !include_dir_merge_list automation/
script: !include includes/scripts.yaml
group: !include includes/groups.yaml
switch: !include includes/switch.yaml
scene: !include includes/scenes.yaml
input_boolean: !include includes/inputs.yaml
shell_command: !include includes/shell_commands.yaml