version: "3"

services:
  hass:
    container_name: hass
    image: lroguet/rpi-home-assistant:latest
    network_mode: "host"
    volumes:
      - /opt/home_assistant/:/config
      - /home/pi/secrets.yaml:/config/secrets.yaml
      - /etc/localtime:/etc/localtime:ro