version: "3"

services:

	hass:
	  container_name: hass
	  image: lroguet/rpi-home-assistant:latest
	  net: host
	  volumes:
	    - /opt/home_assistant/:/config
	    - /etc/localtime:/etc/localtime:ro