- alias: "Weather: Weather Report"
  initial_state: "on"
  trigger:
    platform: time
    at: "07:00"
  condition:
    condition: state
    entity_id: device_tracker.iphones
    state: "home"
  action:
    - service: notify.mobile_app_batphone
      data:
        title: "Weather Report for today"
        message: "Current: {{states.sensor.dark_sky_temperature.state}}°C H/L: {{states.sensor.dark_sky_daytime_high_temperature.state}}°C/{{states.sensor.dark_sky_overnight_low_temperature.state}}°C {{states.sensor.dark_sky_hourly_summary.state}}"
