- alias: 'Heating: Turn on heating if somebody arrives at home'
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: group.personen
      from: 'not_home'
      to: 'home'
  condition:
    condition: and
    conditions:
      - condition: time
        after: '08:00'
        before: '22:00'
      - condition: numeric_state
        entity_id: sensor.temperature_livingroom
        below: '20'
  action:
    - service: script.turn_on_heating_living_room

- alias: 'Heating: Turn on heating if somebody stays home'
  initial_state: 'on'
  trigger:
    - platform: time
      at: '10:00:00'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: group.personen
        state: 'home'
      - condition: numeric_state
        entity_id: sensor.temperature_livingroom
        below: '20'
  action:
    - service: script.turn_on_heating_living_room

- alias: 'Heating: Turn off heating in the evening'
  initial_state: 'on'
  trigger:
    - platform: time
      at: '23:00:00'
    - platform: state
      entity_id: light.living_room_lights
      from: 'on'
      to: 'off'
  condition:
    - condition: time
      after: '20:00'
      before: '23:01'
  action:
    - service: script.turn_off_heating_living_room

- alias: 'Heating: Turn on heating if somebody stays home'
  initial_state: 'on'
  trigger:
    - platform: time
      at: '10:00:00'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: group.personen
        state: 'home'
      - condition: numeric_state
        entity_id: sensor.temperature_livingroom
        below: '20'
  action:
    - service: script.turn_on_heating_living_room

- alias: 'Heating: Turn on heating in the bathroom based on time'
  initial_state: 'on'
  trigger:
    - platform: time
      at: '07:00:00'
  condition:
    condition: and
    conditions:
      - condition: time
        weekday:
          - mon
          - tue
          - wed
          - thu
          - fri
      - condition: numeric_state
        entity_id: sensor.temperature_bath
        below: '20'
  action:
    - service: script.turn_on_heating_bath_room

- alias: 'Heating: Turn off heating in the bathroom based on time'
  initial_state: 'on'
  trigger:
    - platform: time
      at: '08:00:00'
  condition:
    - condition: time
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
  action:
    - service: script.turn_off_heating_bath_room