- alias: "Rain: Rainy Day"
  initial_state: "on"
  trigger:
    - platform: numeric_state
      entity_id: sensor.dark_sky_precip_probability
      above: 60
  condition:
    - condition: time
      after: "07:00"
      before: "20:00"
  action:
    - service: notify.devices_user_1
      data:
        title: "Rain Alert"
        message: "It looks like its gonna rain: ({{states.sensor.dark_sky_precip_probability.state}}%) / ({{states.sensor.dark_sky_precip_intensity.state}}). {{states.sensor.dark_sky_summary.state}}"

- alias: "Rain: Rainy Day"
  initial_state: "on"
  trigger:
    - platform: numeric_state
      entity_id: sensor.dark_sky_precip_probability
      below: 20
  condition:
    - condition: time
      after: "07:00"
      before: "20:00"
  action:
    - service: notify.devices_user_1
      data:
        title: "Rain Stoppes"
        message: "It looks like it stopped raining: ({{states.sensor.dark_sky_precip_probability.state}}%) / ({{states.sensor.dark_sky_precip_intensity.state}}). {{states.sensor.dark_sky_summary.state}}"

