- alias: "Temperature: Warmer outside"
  initial_state: "on"
  trigger:
    - platform: numeric_state
      entity_id: sensor.out_vs_in
      above: 2
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: device_tracker.batphone
        state: "home"
      - condition: numeric_state
        entity_id: "sensor.dark_sky_temperature"
        above: "20"
      - condition: state
        entity_id: binary_sensor.balcony_door
        state: "on"
  action:
    - service: notify.devices_user_1
      data:
        title: "Doors"
        message: "Close the balcony door, since it is {{states.sensor.out_vs_in.state}}°C outside."

- alias: "Temperature: Colder outside"
  initial_state: "on"
  trigger:
    - platform: numeric_state
      entity_id: sensor.out_vs_in
      below: -2
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: device_tracker.batphone
        state: "home"
      - condition: numeric_state
        entity_id: "sensor.dark_sky_temperature"
        above: "20"
      - condition: state
        entity_id: binary_sensor.balcony_door
        state: "off"
  action:
    - service: notify.devices_user_1
      data:
        title: "Doors"
        message: "Open the balcony door, since it is {{states.sensor.out_vs_in.state}}°C colder outside."

- alias: "Humidity warning"
  initial_state: "on"
  trigger:
    - platform: numeric_state
      entity_id:
        - sensor.humidity_bath
        - sensor.humidity_bedroom
        - sensor.humidity_livingroom
        - sensor.humidity_office
      above: 65
  action:
    - service: nnotify.devices_user_1
      data:
        title: "Humidity"
        message: >
          {%- for entity_id in states.group.humidity.attributes.entity_id if states(entity_id) > '65' -%}
            {%- if loop.first %}Humidity: {% endif -%}
              {{state_attr(entity_id, 'friendly_name') }}: {{state_attr(entity_id, 'humidity') }}
            {%- if not loop.last %}, {% endif -%}
          {%- endfor -%}
