- alias: "Temperature: Warmer outside living room"
  use_blueprint:
    path: temperature_outside_warmer.yaml
    input:
      out_vs_in: sensor.livingroom_out_vs_in
      input_group_windows: binary_sensor.livingroom_doors
      input_room_name: "Living Room"


- alias: "Temperature: Warmer outside bedroom"
  use_blueprint:
    path: temperature_outside_warmer.yaml
    input:
      out_vs_in: sensor.bedroom_out_vs_in
      input_group_windows: binary_sensor.bedroom_windows
      input_room_name: "Bedroom"


- alias: "Temperature: Colder outside living room"
  use_blueprint:
    path: temperature_outside_colder.yaml
    input:
      out_vs_in: sensor.livingroom_out_vs_in
      input_group_windows: binary_sensor.livingroom_doors
      input_room_name: "Living Room"

- alias: "Temperature: Colder outside bedroom"
  use_blueprint:
    path: temperature_outside_colder.yaml
    input:
      out_vs_in: sensor.bedroom_out_vs_in
      input_group_windows: binary_sensor.bedroom_windows
      input_room_name: "Bedroom"


- alias: "Humidity warning"
  initial_state: "on"
  trigger:
    - platform: numeric_state
      entity_id:
        - sensor.bath_humidity
        - sensor.bedroom_humidity
        - sensor.livingroom_humidity
        - sensor.office_humidity
        - sensor.child_humidity
      above: 60
  action:
    - service: notify.devices_user_1
      data:
        title: "Humidity"
        message: >
          {%- for entity_id in states.group.humidity.attributes.entity_id if states(entity_id) > '65' -%}
            {%- if loop.first %}Humidity: {% endif -%}
              {{state_attr(entity_id, 'friendly_name') }}: {{ states(entity_id) }}
            {%- if not loop.last %}, {% endif -%}
          {%- endfor -%}
