- alias: "Temperature: Warmer outside"
  initial_state: "on"
  trigger:
    - platform: numeric_state
      entity_id: sensor.out_vs_in
      above: 0
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: group.personen
        state: "home"
      - condition: numeric_state
        entity_id: "sensor.outdoor_temperature"
        above: "20"
      - condition: state
        entity_id: binary_sensor.balcony_door
        state: "on"
  action:
    - service: notify.devices_user_1
      data:
        title: "Doors"
        message: "Close the living room doors, since it is {{states('sensor.out_vs_in')}}°C warmer outside."

- alias: "Temperature: Colder outside"
  initial_state: "on"
  trigger:
    - platform: numeric_state
      entity_id: sensor.out_vs_in
      below: -2
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: group.personen
        state: "home"
      - condition: numeric_state
        entity_id: "sensor.outdoor_temperature"
        above: "20"
      - condition: state
        entity_id: binary_sensor.balcony_door
        state: "off"
  action:
    - service: notify.devices_user_1
      data:
        title: "Doors"
        message: "Open the balcony door, since it is {{states('sensor.out_vs_in')}}°C colder outside."

- alias: "Humidity warning"
  initial_state: "on"
  trigger:
    - platform: numeric_state
      entity_id:
        - sensor.bath_humidity
        - sensor.bedroom_humidity
        - sensor.livingroom_humidity
        - sensor.office_humidity
        - sensor.child_humidity
      above: 60
  action:
    - service: notify.devices_user_1
      data:
        title: "Humidity"
        message: >
          {%- for entity_id in states.group.humidity.attributes.entity_id if states(entity_id) > '65' -%}
            {%- if loop.first %}Humidity: {% endif -%}
              {{state_attr(entity_id, 'friendly_name') }}: {{ states(entity_id) }}
            {%- if not loop.last %}, {% endif -%}
          {%- endfor -%}
