version: '3'
services:
  homeassistant:
    image: homeassistant/home-assistant
    container_name: homeassistant
    network_mode: host
    command: [ "python", "-m", "homeassistant", "--script", "check_config", "--config", "/config" ] 
    volumes:
      - ${HOME_ASSISTANT_CONFIG_PATH}:/config
      - ${SSL_PATH}:/ssl