version: '3'
services:
  homeassistant:
    image: homeassistant/home-assistant:stable
    container_name: homeassistant
    network_mode: host
    command: ["python", "-m", "homeassistant", "--script", "check_config", "--config", "/config"]
    volumes:
      - ../:/config
      - ../ssl:/ssl
