- alias: "TV: Toggle TV2 in bedroom on long button press"
  initial_state: "on"
  trigger:
    platform: state
    entity_id: sensor.bedroom_click
    to: "long"
  action:
    - service: switch.toggle
      entity_id: switch.tv_2

- alias: "TV: Toggle on AppleTV on tap twice action"
  initial_state: "on"
  trigger:
    - platform: mqtt
      topic: 'zigbee2mqtt/sensor_cube'
  condition:
    condition: or
    conditions:
      - condition: template
        value_template: '{{ "tap" == trigger.payload_json.action }}'
      - condition: template
        value_template: '{{ "shake" == trigger.payload_json.action }}'
  action:
    service: switch.toggle
    entity_id: switch.tv_media

- alias: "TV: Close covers if TV is used"
  initial_state: "on"
  trigger:
    platform: state
    entity_id: switch.tv
    from: "off"
    to: "on"
  condition:
    condition: and
    conditions:
      - condition: time
        after: "09:00"
        before: "18:00"
      - condition: state
        entity_id: binary_sensor.dark_outside
        state: "off"
  action:
    - service: script.close_covers_for_tv
    - wait_for_trigger:
        platform: state
        entity_id: switch.tv
        from: "on"
        to: "off"
    - service: script.open_covers_for_tv
