- alias: 'TV: Select mode'
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: input_select.tv_mode
  condition:  
   condition: state
   entity_id: switch.tv
   state: 'on'
  action:
    - service: script.turn_on 
      data_template:
        entity_id: >
          {% if trigger.to_state.state == 'AppleTV' %}
            script.set_input_apple_tv
          {% elif trigger.to_state.state == 'TV' %}
            script.set_input_tv
          {% elif trigger.to_state.state == 'Plex' %}
            script.set_input_plex
          {% elif trigger.to_state.state == 'Music' %}
            script.set_input_music
          {% elif trigger.to_state.state == 'AUS' %}
            script.turn_off_tv_livingroom
          {% endif %}

- alias: 'TV: Select mode + TV'
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: input_select.tv_mode
  condition:  
   condition: state
   entity_id: switch.tv
   state: 'off'
  action:
    - service: switch.turn_on
      entity_id: switch.tv
    - delay:
        seconds: 12
    - service: script.turn_on 
      data_template:
        entity_id: >
          {% if trigger.to_state.state == 'AppleTV' %}
            script.set_input_apple_tv
          {% elif trigger.to_state.state == 'TV' %}
            script.set_input_tv
          {% elif trigger.to_state.state == 'Plex' %}
            script.set_input_plex
          {% elif trigger.to_state.state == 'Music' %}
            script.set_input_music
          {% elif trigger.to_state.state == 'AUS' %}
            script.turn_off_tv_livingroom
          {% endif %}

- alias: 'TV: Pause AppleTV if SONOS is used'
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: media_player.living_room
    from: 'paused'
    to: 'playing'
  condition:
    - condition: state
      entity_id: media_player.wohnzimmer
      state: 'playing'
  action:
    - service: media_player.media_pause
      entity_id: media_player.wohnzimmer

- alias: 'TV: Toggle TV2 in bedroom on long button press'
  initial_state: 'on'
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.switch_bedroom
      click_type: long_click_press
  action:
    - service: switch.toggle
      entity_id: switch.tv_2

- alias: 'TV: Turn on AppleTV on tap twice action'
  initial_state: 'on'
  trigger:
    platform: event
    event_type: xiaomi_aqara.cube_action
    event_data:
      entity_id: binary_sensor.cube_livingroom
      action_type: tap_twice
  condition:
    condition: state
    entity_id: switch.tv
    state: 'off'
  action:
    service: input_select.select_option
    data:
      entity_id: input_select.tv_mode
      option: AppleTV

- alias: 'TV: Turn off TV and pause sonos on shake_air'
  initial_state: 'on'
  trigger:
    platform: event
    event_type: xiaomi_aqara.cube_action
    event_data:
      entity_id: binary_sensor.cube_livingroom
      action_type: shake_air
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.tv_mode
        option: AUS
    - service: script.pause_sonos

- alias: 'TV: Pause AppleTV on flip90'
  initial_state: 'on'
  trigger:
    platform: event
    event_type: xiaomi_aqara.cube_action
    event_data:
      entity_id: binary_sensor.cube_livingroom
      action_type: flip90
  condition:
    condition: state
    entity_id: switch.tv
    state: 'on'
  action:
    - service: media_player.media_pause
      entity_id: media_player.wohnzimmer