#- alias: "TV: Toggle TV2 in bedroom on long button press"
#  initial_state: "on"
#  trigger:
#    - device_id: 3fc934a83becd8fc3406f5ca61be4928
#      domain: zha
#      platform: device
#      type: remote_button_long_press
#      subtype: button
#  action:
#    service: switch.toggle
#    entity_id: switch.tv_2

- alias: "TV: Toggle on AppleTV on tap twice action"
  initial_state: "on"
  trigger:
    - platform: mqtt
      topic: 'zigbee2mqtt/sensor_cube'
  condition:
    condition: or
    conditions:
      - condition: template
        value_template: '{{ "tap" == trigger.payload_json.action }}'
      - condition: template
        value_template: '{{ "shake" == trigger.payload_json.action }}'
  action:
    service: switch.toggle
    entity_id: switch.tv_media

- alias: "TV: Close covers if TV is used"
  initial_state: "on"
  trigger:
    platform: state
    entity_id: switch.tv_media
    from: "off"
    to: "on"
  condition:
    condition: and
    conditions:
      - condition: time
        after: "09:00"
        before: "18:00"
      - condition: state
        entity_id: binary_sensor.dark_outside
        state: "off"
  action:
    - service: script.close_covers_for_tv
    - wait_for_trigger:
        platform: state
        entity_id: switch.tv_media
        from: "on"
        to: "off"
    - service: script.open_covers_for_tv

- alias: "TV: Turn on Playbar if TV is turn"
  initial_state: "on"
  trigger:
    platform: state
    entity_id: switch.tv
    from: "off"
    to: "on"
  action:
    - service: switch.turn_on
      data:
        entity_id:
          - switch.sonos_playbar
    - wait_for_trigger:
        platform: state
        entity_id: switch.tv
        from: "on"
        to: "off"
    - service: switch.turn_on
      data:
        entity_id:
          - switch.sonos_playbar

- alias: "TV 2: Turn off TV 2 after 120 minutes at night"
  initial_state: "on"
  trigger:
    platform: state
    entity_id: switch.tv_2
    from: "off"
    to: "on"
  condition:
    - condition: time
      after: "20:00"
      before: "21:00"
  action:
    - delay:
        minutes: 120
    - service: switch.turn_off
      entity_id: switch.tv_2

- alias: "TV 2: Turn off TV 2 after 90 minutes at night"
  initial_state: "on"
  trigger:
    platform: state
    entity_id: switch.tv_2
    from: "off"
    to: "on"
  condition:
    - condition: time
      after: "21:00"
      before: "23:00"
  action:
    - delay:
        minutes: 90
    - service: switch.turn_off
      entity_id: switch.tv_2

- alias: "TV 2: Turn off TV 2 after 45 minutes at night"
  initial_state: "on"
  trigger:
    platform: state
    entity_id: switch.tv_2
    from: "off"
    to: "on"
  condition:
    - condition: time
      after: "23:00"
      before: "08:00"
  action:
    - delay:
        minutes: 45
    - service: switch.turn_off
      entity_id: switch.tv_2
