blueprint:
  name: Warmer outside
  description: Send notification if warmer outside
  domain: automation
  input:
    input_out_vs_in:
      name: Diff Temperature Sensor
      description: The sensor calulating the diff betwenn a specific room and outdoor temperature
      selector:
        entity:
          domain: sensor
    input_group_windows:
      name: Open Windows
      description: The group of windows in the room
      selector:
        entity:
          domain: binary_sensor
          device_class: opening

variables:
  group_windows: !input input_group_windows
  sensor_out_vs_in: !input input_out_vs_in

trigger:
  platform: numeric_state
  entity_id: !input input_out_vs_in
  above: 0
condition:
  condition: and
  conditions:
    - condition: state
      entity_id: group.personen
      state: "home"
    - condition: numeric_state
      entity_id: "sensor.outdoor_temperature"
      above: "20"
    - condition: state
      entity_id: !input input_group_windows
      state: "on"
action:
  - service: notify.devices_user_1
    data:
      title: "Doors"
      message: >
        Close the follwing doors / windows, since it is {{states(sensor_out_vs_in)}}°C warmer outside.
        {%- for entity_id in states[group_windows].attributes.entity_id if states(entity_id) == 'on' -%}
          {%- if loop.first %} Open: {% endif -%}
          {{state_attr(entity_id, 'friendly_name') }}
          {%- if not loop.last %}, {% endif -%}
        {%- endfor -%}
