- alias: 'Lights: Turn on light in bathroom if motion is detected'
  trigger:
    platform: state
    entity_id: binary_sensor.motion_sensor_158d000121c575
    from: 'off'
    to: 'on'
  condition:
    condition: and
    conditions:
      - condition: time
        after: '16:00'
        before: '02:00'
      - condition: state
        entity_id: sensor.dark_outside
        state: 'on'
  action:
    - service: script.turn_on_bath_default_lights

- alias: 'Lights: Turn off light in bathroom if there is no motion for 3 minutes'
  trigger:
    platform: state
    entity_id: binary_sensor.motion_sensor_158d000121c575
    from: 'on'
    to: 'off'
    for: 
      minutes: 1
  action:
    - service: light.turn_off
      data:
        entity_id: light.bath
        transition: 2

- alias: 'Lights: Set hallway light to be brighter during the day'
  initial_state: 'on'
  trigger:
      platform: time
      at: '04:55'
  action:
    - service: light.turn_on
      data: 
        entity_id: light.bad
        brightness: 50
        transition: 4
    - delay:
        seconds: 1 
    - service: light.turn_off
      entity_id: light.bad

- alias: 'Lights: Dim hallway light at night'
  initial_state: 'on'
  trigger:
      platform: time
      at: '22:00'
  action:
    - service: light.turn_on
      data: 
        entity_id: light.bad
        brightness: 10
    - delay:
        seconds: 2
    - service: light.turn_off
      entity_id: light.bad