- alias: 'Lights: Set hallway light to be brighter during the day'
  initial_state: 'on'
  trigger:
      platform: time
      at: '04:55'
  action:
    - service: light.turn_on
      data: 
        entity_id: light.bad
        brightness: 50
        transition: 4
    - delay:
        seconds: 1 
    - service: light.turn_off
      entity_id: light.bad

- alias: 'Lights: Dim hallway light at night'
  initial_state: 'on'
  trigger:
      platform: time
      at: '22:00'
  action:
    - service: light.turn_on
      data: 
        entity_id: light.bad
        brightness: 10
    - delay:
        seconds: 2
    - service: light.turn_off
      entity_id: light.bad