- alias: Trigger hallway & stair lights by motion sensor
  use_blueprint:
    path: motion_lights.yaml
    input:
      motion_sensor: group.motion_gang
      target_light:
        entity_id: light.stairs

- alias: Trigger front hallway lights by motion sensor
  use_blueprint:
    path: motion_lights_dark_outside.yaml
    input:
      motion_sensor: binary_sensor.motion_entrance
      target_light:
        entity_id: light.entrance

- alias: Trigger front door light by motion sensor
  use_blueprint:
    path: motion_lights.yaml
    input:
      motion_sensor: binary_sensor.entry
      target_light:
        entity_id: light.eingang