- alias: 'Lights: Turn on light in hallway if motion is detected'
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: binary_sensor.gang_motion
    from: 'off'
    to: 'on'
  action:
    - service: light.turn_on
      data:
        entity_id: light.bad_gang
        brightness: 150
        transition: 2

- alias: 'Lights: Turn off light in hallway if there is no motion'
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: binary_sensor.gang_motion
    from: 'on'
    to: 'off'
  action:
    - service: light.turn_off
      data:
        entity_id: light.bad_gang
        transition: 2