- alias: "Lights: Turn on light in hallway if motion is detected (nightmode)"
  initial_state: "on"
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.gang_motion
        - binary_sensor.gang_motion_2
      from: "off"
      to: "on"
  condition:
    - condition: time
      after: "22:00"
      before: "07:00"
  action:
    - service: light.turn_on
      data:
        entity_id: light.hallway
        brightness: 100
        transition: 3
    - service: switch.turn_on
      entity_id: switch.light_stairs

- alias: "Lights: Turn on light in hallway if motion is detected (daymode)"
  initial_state: "on"
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.gang_motion
        - binary_sensor.gang_motion_2
      from: "off"
      to: "on"
  condition:
    - condition: time
      after: "07:00"
      before: "22:00"
  action:
    - service: light.turn_on
      data:
        entity_id: light.hallway
        brightness: 230
        transition: 3
    - service: switch.turn_on
      entity_id: switch.light_stairs

- alias: "Lights: Turn off light in hallway if there is no motion"
  initial_state: "on"
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.gang_motion
        - binary_sensor.gang_motion_2
      from: "on"
      to: "off"
  action:
    - service: light.turn_off
      data:
        entity_id: light.hallway
        transition: 2
    - service: switch.turn_off
      entity_id: switch.light_stairs

- alias: "Lights: Turn on light in front hallway if motion is detected"
  initial_state: "on"
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.motion_entrance
      from: "off"
      to: "on"
  condition:
    - condition: state
      entity_id: binary_sensor.dark_outside
      state: "on"
  action:
    - service: light.turn_on
      data:
        entity_id: light.entrance
        brightness: 200
        transition: 2

- alias: "Lights: Turn off light in front hallway if there is no motion"
  initial_state: "on"
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.motion_entrance
      from: "on"
      to: "off"
  action:
    - service: light.turn_off
      data:
        entity_id: light.entrance
        transition: 2


- alias: "Lights: Turn on entrance light if door is opened"
  initial_state: "on"
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.entry
        - binary_sensor.front_door
      from: "off"
      to: "on"
  action:
    - service: light.turn_on
      data:
        entity_id: light.eingang
        brightness: 200
        transition: 1


- alias: "Lights: Turn off entrance light if no motion"
  initial_state: "on"
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.entry
      from: "on"
      to: "off"
  action:
    - service: light.turn_off
      data:
        entity_id: light.eingang
        transition: 2
