- alias: Trigger front hallway lights by motion sensor
  use_blueprint:
    path: motion_lights_dark_outside.yaml
    input:
      motion_sensor: binary_sensor.motion_kitchen
      target_light:
        entity_id: light.kitchen
