- alias: "Lights: Turn on light in the kitchen if motion is detected"
  initial_state: "on"
  trigger:
    platform: state
    entity_id: binary_sensor.motion_kitchen
    from: "off"
    to: "on"
  condition:
    - condition: state
      entity_id: sensor.dark_outside
      state: "on"
  action:
    - service: script.turn_on_kitchen_lights

- alias: "Lights: Turn off light in the kitchen if there is no motion for 2.5 minutes"
  initial_state: "on"
  trigger:
    platform: state
    entity_id: binary_sensor.motion_kitchen
    from: "on"
    to: "off"
    for:
      seconds: 30
  action:
    - service: script.turn_off_kitchen_lights

- alias: "Lights: Turn on hallway light if door is opened"
  initial_state: "on"
  trigger:
    platform: state
    entity_id: binary_sensor.front_door
    from: "off"
    to: "on"
  condition:
    - condition: state
      entity_id: sensor.dark_outside
      state: "on"
  action:
    - service: light.turn_on
      data:
        entity_id: light.eingang
