- alias: "Lights: Turn on livingroom lights at sunset"
  initial_state: "on"
  trigger:
    - platform: state
      entity_id: binary_sensor.dark_outside
      from: "off"
      to: "on"
    - platform: state
      entity_id: group.personen
      from: "not_home"
      to: "home"
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: group.personen
        state: "home"
      - condition: state
        entity_id: binary_sensor.dark_outside
        state: "on"
  action:
    - service: script.turn_on_livingroom_default_lights
    - service: script.turn_on_christmas

- alias: "Lights: Turn on livingroom lights in the morning"
  initial_state: "on"
  trigger:
    - platform: state
      entity_id: group.motion_gang
      from: "off"
      to: "on"
  condition:
    condition: and
    conditions:
      - condition: time
        after: "06:30"
        before: "10:00"
      - condition: state
        entity_id: binary_sensor.dark_outside
        state: "on"
  action:
    - service: script.turn_on_livingroom_default_lights
    - service: script.turn_on_christmas
    - wait_for_trigger:
        platform: state
        entity_id: binary_sensor.dark_outside
        from: "off"
        to: "on"
    - service: script.turn_off_living_room_lights

- alias: "Lights: Turn on and off lights in livingroom if motion is detected"
  initial_state: "on"
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_livingroom
      from: "off"
      to: "on"
  condition:
    condition: and
    conditions:
      - condition: time
        after: "03:01"
        before: "05:00"
      - condition: state
        entity_id: binary_sensor.dark_outside
        state: "on"
  action:
    - service: script.turn_on_livingroom_default_lights
    - wait_for_trigger:
        platform: state
        entity_id: binary_sensor.motion_livingroom
        from: "on"
        to: "off"
    - service: script.turn_off_livingroom