- alias: 'Lights: Turn on light in office if motion is detected'
  trigger:
    platform: state
    entity_id: binary_sensor.motion_sensor_158d0001ff3f0a
    from: 'off'
    to: 'on'
  condition:
    - condition: state
      entity_id: sensor.dark_outside
      state: 'on'
  action:
    - service: script.turn_on_office_default_lights

- alias: 'Lights: Turn off light in office lights if there is no motion for 3 minutes'
  trigger:
    platform: state
    entity_id: binary_sensor.motion_sensor_158d0001ff3f0a
    from: 'on'
    to: 'off'
    for: 
      minutes: 1
  action:
    - service: light.turn_off
      data:
        entity_id: light.arbeitszimmer
        transition: 2