- alias: Trigger office light by motion sensor
  description: Test
  use_blueprint:
    path: motion_lights_dark_outside.yaml
    input:
      motion_sensor: binary_sensor.motion_office
      target_light:
        entity_id: light.office
