- alias: "Lights: Turn on light in office if motion is detected"
  initial_state: "on"
  trigger:
    platform: state
    entity_id: binary_sensor.motion_office
    from: "off"
    to: "on"
  condition:
    - condition: state
      entity_id: sensor.dark_outside
      state: "on"
  action:
    - service: script.turn_on_office_default_lights

- alias: "Lights: Turn off light in office lights if there is no motion for 3 minutes"
  initial_state: "on"
  trigger:
    platform: state
    entity_id: binary_sensor.motion_office
    from: "on"
    to: "off"
    for:
      minutes: 2
  action:
    - service: light.turn_off
      data:
        entity_id: light.arbeitszimmer
        transition: 2
