- alias: "Lights: Turn on light in office if motion is detected"
  initial_state: "on"
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_office
      from: "off"
      to: "on"
  condition:
    - condition: state
      entity_id: sensor.dark_outside
      state: "on"
  action:
    - service: light.turn_on
      data:
        entity_id: light.arbeitszimmer
        brightness: 200

- alias: "Lights: Turn off light in office lights if there is no motion for 3 minutes"
  initial_state: "on"
  trigger:
    platform: state
    entity_id: 
      - binary_sensor.motion_office
      - binary_sensor.batmac_active
    from: "on"
    to: "off"
    for:
      minutes: 2
  condition:
    - condition: state
      entity_id: binary_sensor.batmac_active
      state: "off"
  action:
    - delay:
        seconds: 20
    - service: light.turn_off
      data:
        entity_id: light.arbeitszimmer
        transition: 2
