- alias: 'Alarm: Trigger alarm when motion is detected'
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.front_door
        - binary_sensor.balcony_door
        - binary_sensor.office_door
        - binary_sensor.living_room_balcony_door
        - binary_sensor.childrens_room_door
        - binary_sensor.motion_livingroom
        - binary_sensor.gang_motion
        - binary_sensor.gang_motion_2
        - binary_sensor.motion_gang
        - binary_sensor.motion_office
        - binary_sensor.entry
      to: 'on'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: alarm_control_panel.alarm
        state: armed_away
      - condition: template
        value_template: "{{ not is_state('vacuum.vacuum_cleaner', 'cleaning') }}"
  action:
    service: alarm_control_panel.alarm_trigger
    entity_id: alarm_control_panel.alarm

- alias: 'Alarm: Trigger alarm when motion is detected'
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.front_door
        - binary_sensor.balcony_door
        - binary_sensor.office_door
        - binary_sensor.living_room_balcony_door
        - binary_sensor.childrens_room_door
      to: 'on'
  condition:
    condition: or
    conditions:
      - condition: state
        entity_id: alarm_control_panel.alarm
        state: armed_home
  action:
    service: alarm_control_panel.alarm_trigger
    entity_id: alarm_control_panel.alarm

# Disarm Alarm

- alias: 'Alarm: Disarm alarm when users are home'
  trigger:
    - platform: state
      entity_id: group.personen
      from: not_home
      to: home
  action:
    - service: script.disable_alarm

- alias: 'Alarm: Disarm phone is removed from charger in the morning'
  trigger:
    - platform: state
      entity_id: sensor.batphone_battery_state
      to: 'Not Charging'
  condition:
    - condition: time
      after: "06:00"
      before: "11:00"
  action:
    - service: script.disable_alarm

- alias: 'Alarm: Send notification when alarm is Disarmed'
  trigger:
    - platform: state
      entity_id: alarm_control_panel.alarm
      to: 'disarmed'
  action:
    - service: notify.devices_user_1
      data_template:
        title: 'Alarm'
        message: "Alarm is disarmed at {{ states('sensor.date_time') }}"


# Enable Alarm

- alias: 'Alarm: Arm the alarm when users are not home'
  trigger:
    - platform: state
      entity_id: group.personen
      from: home
      to: not_home
  action:
    - service: script.enable_alarm

- alias: 'Alarm: Arm the alarm when phone is charging'
  trigger:
    - platform: state
      entity_id: sensor.batphone_battery_state
      to: 'Charging'
  condition:
    - condition: time
      after: "20:00"
      before: "05:00"
  action:
    - service: alarm_control_panel.alarm_arm_home
      data:
        entity_id: alarm_control_panel.alarm
        code: 1234
    - service: notify.devices_user_1
      data_template:
        title: "Alarm"
        message: >
          Alarm is armed in home mode at {{ states('sensor.date_time') }}.
          {%- for entity_id in states.group.doors.attributes.entity_id if states(entity_id) == 'on' -%}
            {%- if loop.first %}Open Doors: {% endif -%}
            {{state_attr(entity_id, 'friendly_name') }}
            {%- if not loop.last %}, {% endif -%}
          {%- endfor -%}

- alias: 'Alarm: Send notification when alarm is armed in away mode'
  trigger:
    - platform: state
      entity_id: alarm_control_panel.alarm
      to: 'armed_away'
  action:
    - service: notify.devices_user_1
      data_template:
        title: "Alarm"
        message: >
          Alarm is armed at {{ states('sensor.date_time') }}.
          {%- for entity_id in states.group.doors_and_windows.attributes.entity_id if states(entity_id) == 'on' -%}
            {%- if loop.first %}Open Doors: {% endif -%}
            {{state_attr(entity_id, 'friendly_name') }}
            {%- if not loop.last %}, {% endif -%}
          {%- endfor -%}

- alias: "Door: A Door is still open"
  initial_state: "on"
  trigger:
    - platform: state
      entity_id: binary_sensor.front_door
      from: "off"
      to: "on"
  condition:
    condition: state
    entity_id: group.doors
    state: "on"
  action:
    - service: notify.devices_user_1
      data_template:
        title: "Doors"
        message: >
          {%- for entity_id in states.group.doors.attributes.entity_id if states(entity_id) == 'on' -%}
            {%- if loop.first %}Open doors: {% endif -%}
            {{state_attr(entity_id, 'friendly_name') }}
            {%- if not loop.last %}, {% endif -%}
          {%- endfor -%}
    - delay:
        seconds: 20

- alias: "Door: Front Door is still open"
  initial_state: "on"
  trigger:
    - platform: state
      entity_id: binary_sensor.front_door
      from: "off"
      to: "on"
      for:
        minutes: 5
  action:
    - service: notify.devices_user_1
      data_template:
        title: "Door"
        message: "Front Door is still open"

- alias: "Door: Garden trunk left open"
  initial_state: "on"
  trigger:
    - platform: state
      entity_id: binary_sensor.garden_trunk
      from: "off"
      to: "on"
      for:
        minutes: 5
  action:
    - service: notify.devices_user_1
      data_template:
        title: "Door"
        message: "Garden trunk is still open!"

- alias: "Mail: The mailbox was opened"
  initial_state: "on"
  trigger:
    - device_id: b9805d8380855ea31eb01ce954f06e1d
      domain: zha
      platform: device
      type: device_tilted
      subtype: device_tilted
  action:
    - service: notify.devices_user_1
      data_template:
        title: "Mailbox"
        message: "Mailbox was opened"
        data:
          push:
            thread-id: "mailbox"
    - delay:
        seconds: 10

- alias: "Water: Water leak detected by water sensor"
  initial_state: "on"
  trigger:
    platform: state
    entity_id: binary_sensor.water_leak_sensor
    from: "off"
    to: "on"
  action:
    - service: notify.devices_user_1
      data:
        title: "Water Sensor"
        message: "Water leak detected! Check washing mashine"

- alias: "Water: Stopped Water leak detected by water sensor"
  initial_state: "on"
  trigger:
    platform: state
    entity_id: binary_sensor.water_leak_sensor
    from: "on"
    to: "off"
  action:
    - service: notify.devices_user_1
      data:
        title: "Water Sensor"
        message: "Water leak got resolved"
