# Trigger alarm if motion is detected, altough noboby is home   
- alias: 'Alarm'    
  trigger:    
    - platform: state     
      entity_id: light.lampe_gang_bad  
      from: 'off'   
      to: 'on' 
    - platform: state     
      entity_id: light.lampe_gang_eingang  
      from: 'off'   
      to: 'on'   
  condition:    
    condition: state    
    entity_id: group.personen   
    to: 'not home'   
  action:     
    - service: notify.ios_iphones   
      data:   
        title: 'Alarm'    
        message: 'Motion was detected, but nobody seems to be at home!'

