# Trigger alarm if motion is detected, altough noboby is home   
- alias: 'Alarm' 
  initial_state: 'on'   
  trigger:    
    - platform: state     
      entity_id: light.bad, light.eingang, binary_sensor.door_window_sensor_158d0001d8253a, light.kueche1
      from: 'off'   
      to: 'on'   
  condition:
    condition: and
    conditions:    
      - condition: state    
        entity_id: group.personen   
        state: 'not_home'
      - condition: state
        entity_id: vacuum.staubsauger
        state: 'off'
  action:     
    - service: notify.ios_iphones_app   
      data_template:   
        title: 'Alarm'    
        message: 'Motion was detected by {{ trigger.to_state.attributes.friendly_name }}, but nobody seems to be at home!'