- alias: "Alarm: Notify if motion is detected"
  initial_state: "on"
  trigger:
    - platform: state
      entity_id: 
        - light.eingang
        - binary_sensor.front_door
      from: "off"
      to: "on"
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: group.personen
        state: "not_home"
      - condition: state
        entity_id: vacuum.vacuum_cleaner
        state: "docked"
  action:
    - service: notify.mobile_app_batphone
      data_template:
        title: "Alarm"
        message: "Motion was detected by {{ trigger.to_state.attributes.friendly_name }}, but nobody seems to be at home!"

- alias: "Door: A Door is still open"
  initial_state: "on"
  trigger:
    - platform: state
      entity_id: binary_sensor.front_door
      from: "off"
      to: "on"
  condition:
    condition: state
    entity_id: group.doors
    state: "on"
  action:
    - service: notify.mobile_app_batphone
      data_template:
        title: "Doors"
        message: >
          "Open doors:  {% if is_state('binary_sensor.balcony_door', 'on') %}Kitchen, {% endif %}
                        {% if is_state('binary_sensor.living_room_balcony_door', 'on') %}Livingroom, {% endif %}
                        {% if is_state('binary_sensor.office_door', 'on') %}Office, {% endif %}
                        {% if is_state('binary_sensor.childrens_room_door', 'on') %}Child`s room{% endif %}"

- alias: "Door: Front Door is still open"
  initial_state: "on"
  trigger:
    - platform: state
      entity_id: binary_sensor.front_door
      from: "off"
      to: "on"
      for:
        minutes: 5
  action:
    - service: notify.mobile_app_batphone
      data_template:
        title: "Door"
        message: "Front Door is still open"
