# Trigger alarm if motion is detected, altough noboby is home   
- alias: 'Alarm' 
  initial_state: 'on'   
  trigger:    
    - platform: state     
      entity_id: light.bad 
      from: 'off'   
      to: 'on' 
    - platform: state     
      entity_id: light.eingang  
      from: 'off'   
      to: 'on'   
  condition:    
    condition: state    
    entity_id: group.personen   
    state: 'not home'   
  action:     
    - service: notify.ios_iphones_app   
      data:   
        title: 'Alarm'    
        message: 'Motion was detected, but nobody seems to be at home!'

