- alias: "Alarm: Notify if motion is detected"
  initial_state: "on"
  trigger:
    - platform: state
      entity_id:
        - light.eingang
        - binary_sensor.front_door
        - binary_sensor.gang_motion
        - binary_sensor.gang_motion_2
        - group.doors
        - binary_sensor.entry
        - binary_sensor.motion_entrance
      from: "off"
      to: "on"
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: group.personen
        state: "not_home"
      - condition: template
        value_template: "{{ not is_state('vacuum.vacuum_cleaner', 'cleaning') }}"
  action:
    - service: notify.devices_user_1
      data_template:
        title: "Alarm"
        message: "Motion was detected by {{ trigger.to_state.attributes.friendly_name }}, but nobody seems to be at home!"
        data:
          push:
            sound:
              name: default
              critical: 1
              volume: 1.0
            thread-id: "alarm"
    - delay:
        seconds: 10

- alias: "Door: A Door is still open"
  initial_state: "on"
  trigger:
    - platform: state
      entity_id: binary_sensor.front_door
      from: "off"
      to: "on"
  condition:
    condition: state
    entity_id: group.doors
    state: "on"
  action:
    - service: notify.devices_user_1
      data_template:
        title: "Doors"
        message: >
          "Open doors: {% if is_state('binary_sensor.balcony_door', 'on') %}Kitchen, {% endif %} {% if is_state('binary_sensor.living_room_balcony_door', 'on') %}Livingroom, {% endif %}{% if is_state('binary_sensor.office_door', 'on') %}Office, {% endif %}{% if is_state('binary_sensor.childrens_room_door', 'on') %}Child`s room{% endif %}"
    - delay:
        seconds: 20

- alias: "Door: Front Door is still open"
  initial_state: "on"
  trigger:
    - platform: state
      entity_id: binary_sensor.front_door
      from: "off"
      to: "on"
      for:
        minutes: 5
  action:
    - service: notify.devices_user_1
      data_template:
        title: "Door"
        message: "Front Door is still open"

- alias: "Mail: The mailbox was opened"
  initial_state: "on"
  trigger:
    - platform: event
      event_type: xiaomi_aqara.movement
      event_data:
        entity_id: sensor.vibration_action
        movement_type: tilt
    - platform: state
      entity_id: sensor.vibration_action
      to: 'vibration'
    - platform: state
      entity_id: sensor.vibration_action
      to: 'tilt'
  action:
    - service: notify.devices_user_1
      data_template:
        title: "Mailbox"
        message: "Mailbox was opened"
        data:
          push:
            thread-id: "mailbox"
    - delay:
        seconds: 10
