- alias: 'Alarm: Notify if motion is detected' 
  initial_state: 'on'   
  trigger:    
    - platform: state     
      entity_id: light.eingang, binary_sensor.door_window_sensor_158d0001d8253a, light.kueche1
      from: 'off'   
      to: 'on'   
  condition:
    condition: and
    conditions:    
      - condition: state    
        entity_id: group.personen   
        state: 'not_home'
      - condition: state
        entity_id: vacuum.vacuum_cleaner
        state: 'off'
  action:     
    - service: notify.ios_iphones_app   
      data_template:   
        title: 'Alarm'    
        message: 'Motion was detected by {{ trigger.to_state.attributes.friendly_name }}, but nobody seems to be at home!'

- alias: 'Door: Balcony Door is still open' 
  initial_state: 'on'   
  trigger:    
    - platform: state     
      entity_id: binary_sensor.door_window_sensor_158d0001d8253a
      from: 'off'   
      to: 'on'   
  condition:
    condition: state    
    entity_id: group.balcony_doors   
    state: 'on'
  action:     
    - service: notify.ios_iphones_app   
      data_template:   
        title: 'Door'    
        message: 'Balcony Door is still open'

- alias: 'Door: Front Door is still open' 
  initial_state: 'on'   
  trigger:    
    - platform: state     
      entity_id: binary_sensor.door_window_sensor_158d0001d8253a
      from: 'off'   
      to: 'on'
      for:
        minutes: 5
  action:     
    - service: notify.ios_iphones_app   
      data_template:   
        title: 'Door'    
        message: 'Front Door is still open'