- alias: "Speaker: Toggle speaker with button press"
  initial_state: "on"
  trigger:
    platform: state
    entity_id: sensor.button_child_action
    to: "single"
  action:
    - service: script.toggle_speaker_and_light_childroom
