- alias: "Cover: Open all covers in the morning"
  initial_state: "on"
  trigger:
    - platform: state
      entity_id: 
        - binary_sensor.gang_motion
        - binary_sensor.gang_motion_2
      from: "off"
      to: "on"
  condition:
    condition: and
    conditions:
      - condition: time
        after: "06:00"
        before: "11:00"
      - condition: state
        entity_id: cover.all
        state: "closed"
  action:
    - service: script.open_all_covers

- alias: "Cover: Close all covers in the evening"
  initial_state: "on"
  trigger:
    - platform: state
      entity_id: sensor.dark_outside
      from: "off"
      to: "on"
  condition:
    condition: and
    conditions:
      - condition: time
        after: "17:00"
        before: "23:00"
      - condition: state
        entity_id: cover.all
        state: "open"
  action:
    - service: script.close_all_covers
