- alias: "Cover: Open all covers in the morning"
  initial_state: "on"
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.gang_motion
        - binary_sensor.gang_motion_2
      from: "off"
      to: "on"
  condition:
    condition: and
    conditions:
      - condition: time
        after: "06:00"
        before: "11:00"
      - condition: state
        entity_id: cover.all
        state: "closed"
      - condition: state
        entity_id: binary_sensor.dark_outside
        state: "off"
  action:
    - service: script.open_all_covers

- alias: "Cover: Open all covers in the morning if its bright outside"
  initial_state: "on"
  trigger:
    - platform: state
      entity_id: binary_sensor.dark_outside
      from: "on"
      to: "off"
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: cover.all
        state: "closed"
      - condition: time
        after: "06:00"
        before: "11:00"
  action:
    - service: script.open_all_covers

- alias: "Cover: Close all covers in the evening"
  initial_state: "on"
  trigger:
    - platform: state
      entity_id: binary_sensor.dark_outside
      from: "off"
      to: "on"
  condition:
    condition: and
    conditions:
      - condition: time
        after: "16:00"
        before: "23:00"
      - condition: state
        entity_id: cover.all
        state: "open"
  action:
    - delay:
        minutes: 30
    - service: script.close_all_covers

- alias: "Cover: Close front covers if it is sunny and nobody is home"
  initial_state: "on"
  trigger:
    - platform: numeric_state
      entity_id: sensor.openweathermap_temperature
      above: 25
    - platform: state
      entity_id: group.personen
      from: home
      to: not_home
  condition:
    condition: and
    conditions:
      - condition: time
        after: "10:00"
        before: "20:00"
      - condition: state
        entity_id: group.personen
        state: not_home
  action:
    - service: script.close_front_covers

- alias: "Cover: Open front covers if someone arrives home"
  initial_state: "on"
  trigger:
    - platform: state
      entity_id: group.personen
      from: not_home
      to: home
  condition:
    condition: and
    conditions:
      - condition: time
        after: "10:00"
        before: "20:00"
      - condition: numeric_state
        entity_id: sensor.openweathermap_temperature
        below: 25
  action:
    - service: script.open_front_covers

- alias: "Cover: Close front covers if it is sunny"
  initial_state: "on"
  trigger:
    - platform: time
      at: "14:30"
  action:
    - service: script.close_front_covers

- alias: "Cover: Open front covers after sun is away"
  initial_state: "on"
  trigger:
    - platform: time
      at: "18:30"
  action:
    - service: script.open_front_covers

- alias: "Cover: Open all covers in the morning on vacation"
  initial_state: "on"
  trigger:
    - platform: time
      at: "08:00"
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.vacation_mode
        state: "on"
      - condition: state
        entity_id: cover.all
        state: "closed"
  action:
    - delay:
        minutes: '{{ range(2, 36) | random }}'
    - service: script.open_all_covers
