# Inspired by https://github.com/CCOSTAN/Home-AssistantConfig
- alias: 'Device Status'
  trigger:
    - platform: state
      entity_id:
        - sensor.robo
        - sensor.tradfri
        - sensor.switch
      to: 'off'
      for:
        minutes: 5
  action:
    - service: notify.ios_iphones   
      data:   
        title: 'Devices'    
        message: '{{ trigger.to_state.attributes.friendly_name }} is {{ trigger.to_state.state }}'