# Inspired by https://github.com/CCOSTAN/Home-AssistantConfig
- alias: 'Status: Device status offline'
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: sensor.robo, sensor.tradfri, sensor.switch, sensor.aqara_gateway
      to: 'off'
      for:
        minutes: 5
  action:
    - service: notify.ios_iphones_app   
      data_template:   
        title: 'Devices' 
        message: '{{ trigger.to_state.attributes.friendly_name }} is {{ trigger.to_state.state }}'

- alias: 'Status: Remote Device status offline'
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: binary_sensor.ping_dreieich, binary_sensor.ping_eltern, binary_sensor.ping_gote, binary_sensor.ping_polanetzki, binary_sensor.ping_schwarzwald, binary_sensor.ping_sebastian, binary_sensor.ping_sonja, binary_sensor.ping_uwe, binary_sensor.ping_vhv, binary_sensor.ping_wsw
      to: 'off'
      for:
        minutes: 5
  action:
    - service: notify.ios_iphones_app   
      data_template:   
        title: 'Devices'  
        message: '{{ trigger.to_state.attributes.friendly_name }} is {{ trigger.to_state.state }}'

# Inspired by https://github.com/CCOSTAN/Home-AssistantConfig
- alias: 'Status: Device status online'
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: sensor.robo, sensor.tradfri, sensor.switch, sensor.aqara_gateway, binary_sensor.ping_dreieich, binary_sensor.ping_eltern, binary_sensor.ping_gote, binary_sensor.ping_polanetzki, binary_sensor.ping_schwarzwald, binary_sensor.ping_sebastian, binary_sensor.ping_sonja, binary_sensor.ping_uwe, binary_sensor.ping_vhv, binary_sensor.ping_wsw
      to: 'on'
      for:
        minutes: 1
  action:
    - service: notify.ios_iphones_app   
      data_template:   
        title: 'Devices'    
        message: '{{ trigger.to_state.attributes.friendly_name }} is {{ trigger.to_state.state }}'