- alias: "Garden Watering: Turn on watering"
  initial_state: "on"
  trigger:
    platform: time
    at: "08:00"
  condition:
    condition: and
    conditions:
      - condition: time
        weekday:
          - mon
          - thu
          - sat
      - condition: numeric_state
        entity_id: sensor.rain_last_day
        below: 5
      - condition: numeric_state
        entity_id: sensor.openweathermap_forecast_precipitation
        below: 5
  action:
    - service: notify.devices_user_1
      data_template:
        title: "Watering"
        message: > 
          Garden Watering will start in 10 minutes. 
          Rain yesterday: {{ states('sensor.rain_last_day') }}l /
          Rain today: {{ states('sensor.openweathermap_forecast_precipitation') }}l
    - delay:
        minutes: 10
    - service: script.activate_water_rasen
    - service: script.activate_water_hecke
    - service: script.activate_water_blumenbeet
    - service: script.activate_water_rasen_klein
    - service: notify.devices_user_1
      data_template:
        title: "Watering"
        message: "Garden Watering finished"

- alias: "Garden Watering: Reset Auto off timer"
  initial_state: "on"
  trigger:
    - platform: state
      entity_id: switch.garden_water_valve
      to: "off"
  condition: []
  action:
    - service: zha.set_zigbee_cluster_attribute
      data:
        ieee: 00:3c:84:ff:fe:15:fc:9f
        endpoint_id: 1
        cluster_id: 61184
        attribute: 61185
        value: 4000
  mode: single
