- alias: "Garden Watering: Turn on watering"
  initial_state: "on"
  trigger:
    platform: time
    at: "07:00"
  condition:
    condition: time
    weekday:
      - mon
      - thu
      - sat
  action:
    - service: script.activate_water_rasen
    - service: script.activate_water_hecke
    - service: script.activate_water_blumenbeet
    - service: script.activate_water_rasen_klein

- alias: "Garden Watering: Reset Auto off timer"
  initial_state: "on"
  trigger:
    - platform: state
      entity_id: switch.garden_water_valve
      to: "off"
  condition: []
  action:
    - service: zha.set_zigbee_cluster_attribute
      data:
        ieee: 00:3c:84:ff:fe:15:fc:9f
        endpoint_id: 1
        cluster_id: 61184
        attribute: 61185
        value: 4000
  mode: single
