- alias: 'Lights: Turn on livingroom lights at sunset'
  initial_state: 'on'
  trigger:
    - platform: sun
      event: sunset
      offset: '-00:20:00'
    - platform: state
      entity_id: group.personen
      from: 'not_home'
      to: 'home'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: group.personen
        state: 'home'
      - condition: or
        conditions:
          - condition: sun
            after: sunset
            after_offset: '-00:20:00'
          - condition: time
            before: '03:00'
  action:
    - service: script.turn_on 
      data_template:
        entity_id: >
          {% if is_state('switch.tv', 'on') %}
            script.turn_on_livingroom_dimmed_lights
          {% else %}
            script.turn_on_livingroom_default_lights
          {% endif %}
    # - service: homeassistant.turn_on
    #   entity_id: group.christmas
    - service: light.turn_on
      data:
        entity_id: light.eingang

# Turn on light at Sofa if ATV is paused   
- alias: 'Lights: Dim lights when AppleTV is played'
  initial_state: 'on'   
  trigger:    
    - platform: state   
      entity_id: media_player.wohnzimmer    
      from: 'paused'    
      to: 'playing'     
  condition:    
    condition: and    
    conditions:   
      - condition: state    
        entity_id: sun.sun    
        state: below_horizon    
      - condition: time   
        after: '20:00'    
        before: '03:00'
      - condition: state
        entity_id: light.sofa
        state: 'on'   
  action:   
    - service: script.turn_on_livingroom_dimmed_lights


# Turn on light at Sofa if ATV is paused
- alias: 'Lights: Turn on light when AppleTV is paused'
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: media_player.wohnzimmer
      from: 'playing'
      to: 'paused'
      for:
        seconds: 1
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: sun.sun
        state: below_horizon
      - condition: time
        after: '20:00'
        before: '03:00'
      - condition: state
        entity_id: light.sofa
        state: 'on'
  action:
    - service: script.turn_on_livingroom_default_lights

- alias: 'Lights: 60 minutes timer for devices at night'
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: group.bed_room
      from: 'off'
      to: 'on'
  condition:
    condition: time
    after: '23:00'
    before: '05:00'
  action:
    - service: script.turn_off_bedroom_delay_60

# Turn off devices in the livingroom 15 minutes when switched on after 3:01
- alias: 'Lights: 15 minutes timer for devices at night'
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: group.living_room
      from: 'off'
      to: 'on'
  condition:
    condition: time
    after: '03:01'
    before: '05:00'
  action:
    - service: script.turn_off_livingroom_delay_15


# Turn on lights in bedroom, if TV is switched off
- alias: 'Lights: Turn on lights in bedroom after TV is switched off'
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: switch.tv
      from: 'on'
      to: 'off'
  condition:
    condition: time
    after: '21:00'
    before: '00:00'
  action: 
    - service: script.turn_on_bedroom_dimmed_lights
    - service: script.turn_off_livingroom_delay_15

# Turn on lights in the livingroom if someone is awake before sun rises
- alias: 'Lights: Turn on livingroom lights in the morning'
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: light.bad
      from: 'off'
      to: 'on'
    - platform: state
      entity_id: light.kueche1
      from: 'off'
      to: 'on'
    - platform: state
      entity_id: light.eingang
      from: 'off'
      to: 'on'
  condition:
    - condition: time
      after: '06:30'
      before: '10:00'
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
        - sat
  action:
    - service: script.turn_off
      entity_id: script.turn_off_livingroom_lights_delay_30
    - service: script.turn_on_livingroom_morning
    - service: script.turn_off_livingroom_lights_delay_30

- alias: 'Lights: Dim hallway light at night'
  initial_state: 'on'
  trigger:
      platform: time
      at: '22:00'
  action:
    - service: light.turn_on
      data: 
        entity_id: light.bad
        brightness: 10
    - delay:
        seconds: 2
    - service: light.turn_off
      entity_id: light.bad

- alias: 'Lights: Set hallway light to be brighter during the day'
  initial_state: 'on'
  trigger:
      platform: time
      at: '05:30'
  action:
    - service: light.turn_on
      data: 
        entity_id: light.bad
        brightness: 50
        transition: 4
    - delay:
        minutes: 1 
    - service: light.turn_off
      entity_id: light.bad

- alias: 'Lights: Turn on light in the kitchen if motion is detected'
  trigger:
    platform: state
    entity_id: binary_sensor.motion_sensor_158d0001a90475
    from: 'off'
    to: 'on'
  condition:
    condition: or
    conditions:
      - condition: sun
        after: sunset
        after_offset: '-01:00:00'
      - condition: sun
        before: sunrise
        before_offset: '01:00:00'
  action:
    - service: script.turn_on_kitchen_lights

- alias: 'Lights: Turn off light in the kitchen if there is no motion for 2.5 minutes'
  trigger:
    platform: state
    entity_id: binary_sensor.motion_sensor_158d0001a90475
    from: 'on'
    to: 'off'
    for: 
      seconds: 30
  action:
    - service: script.turn_off_kitchen_lights


- alias: 'Lights: Turn on light in working room if motion is detected'
  trigger:
    platform: state
    entity_id: binary_sensor.motion_sensor_158d000121c575
    from: 'off'
    to: 'on'
  condition:
    condition: or
    conditions:
      - condition: sun
        after: sunset
        after_offset: '-01:00:00'
      - condition: sun
        before: sunrise
        before_offset: '01:00:00'
  action:
    - service: script.turn_on_office_default_lights

- alias: 'Lights: Turn off light in working room if there is no motion for 3 minutes'
  trigger:
    platform: state
    entity_id: binary_sensor.motion_sensor_158d000121c575
    from: 'on'
    to: 'off'
    for: 
      minutes: 1
  action:
    - service: light.turn_off
      data:
        entity_id: light.arbeitszimmer
        transition: 2


- alias: 'Turn on hallway light if door is opened'
  trigger:
    platform: state
    entity_id: binary_sensor.door_window_sensor_158d0001d8253a
    from: 'off'
    to: 'on'
  condition:
    condition: or
    conditions:
      - condition: sun
        after: sunset
        after_offset: '-01:00:00'
      - condition: sun
        before: sunrise
        before_offset: '01:00:00'
  action:
    - service: light.turn_on
      data:
        entity_id: light.eingang

- alias: 'Turn on lights in bedroom and switch of living room'
  trigger:
    platform: event
    event_type: click
    event_data:
      entity_id: binary_sensor.switch_158d0001d8795f
      click_type: single
  condition:
    - condition: state
      entity_id: group.lights_bedroom
      state: 'off' 
  action:
    - service: script.turn_on_bedroom_dimmed_lights


- alias: 'Turn off lights in bedroom'
  trigger:  
    platform: event
    event_type: click
    event_data:
      entity_id: binary_sensor.switch_158d0001d8795f
      click_type: single
  condition:
    - condition: state
      entity_id: group.lights_bedroom
      state: 'on' 
  action:
    - service: homeassistant.turn_off
      entity_id: group.lights_bedroom
