- alias: 'Livingroom lights at sunset'
  trigger:
    - platform: sun
      event: sunset
      offset: '-00:10:00'
    - platform: state
      entity_id: group.personen
      from: 'not_home'
      to: 'home'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: group.personen
        state: 'home'
      - condition: state
        entity_id: switch.tv
        state: 'off'
      - condition: or
        conditions:
          - condition: sun
            after: sunset
            after_offset: '-00:10:00'
          - condition: time
            before: '03:00'
  action:
    - service: light.turn_on
      data: 
        entity_id: group.wohnzimmer_lampen
        brightness: 150

- alias: 'Livingroom lights at sunset + TV is on'
  trigger:
    - platform: sun
      event: sunset
      offset: '-00:10:00'
    - platform: state
      entity_id: group.personen
      from: 'not_home'
      to: 'home'
    - platform: state
      entity_id: light.lampe_gang_eingang
      to: 'on'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: group.personen
        state: 'home'
      - condition: state
        entity_id: switch.tv
        state: 'on'
      - condition: or
        conditions:
          - condition: sun
            after: sunset
            after_offset: '-00:10:00'
          - condition: time
            before: '03:00'
  action:
    - service: light.turn_on
      data: 
        entity_id: group.wohnzimmer_lampen
        brightness: 20

# Turn on light at Sofa if ATV is paused
- alias: 'Turn on light when AppleTV is paused'
  trigger:
    - platform: state
      entity_id: media_player.atv_wohnzimmer
      from: 'playing'
      to: 'paused'
      for:
        seconds: 1
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: sun.sun
        state: below_horizon
      - condition: time
        after: '15:00'
        before: '03:00'
  action:
    - service: light.turn_on
      data: 
        entity_id: group.wohnzimmer_lampen
        brightness: 150

# Turn on light at Sofa if ATV is paused
- alias: 'Dim light when AppleTV is played'
  trigger:
    - platform: state
      entity_id: media_player.atv_wohnzimmer
      from: 'paused'
      to: 'playing'  
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: sun.sun
        state: below_horizon
      - condition: time
        after: '15:00'
        before: '03:00'
  action:
    - service: light.turn_on
      data: 
        entity_id: group.wohnzimmer_lampen
        brightness: 20

# Turn of devices in the bedroom 30 minutes when switched on after 23:00
- alias: '45 minutes timer for devices at night'
  trigger:
    - platform: state
      entity_id: group.schlafzimmer
      from: 'off'
      to: 'on'
  condition:
    condition: time
    after: '23:00'
    before: '05:00'
  action:
    - service: script.turn_off_bedroom_delay_45
    #- service: notify.ios_iphones
    #  data:
    #    title: 'Timer'
    #    message: 'I will turn off the devices in the bedroom in 45 minutes'

# Turn off devices in the livingroom 15 minutes when switched on after 3:01
- alias: '15 minutes timer for devices at night'
  trigger:
    - platform: state
      entity_id: group.wohnzimmer
      from: 'off'
      to: 'on'
  condition:
    condition: time
    after: '03:01'
    before: '05:00'
  action:
    - service: script.turn_off_livingroom_delay_15
    #- service: notify.ios_iphones
    #  data:
    #    title: 'Timer'
    #    message: 'I will turn off the devices in the livingroom in 15 minutes'


# Turn on lights in bedroom, if TV is switched off
- alias: 'Turn on lights in bedroom after TV is switched off'
  trigger:
    - platform: state
      entity_id: switch.tv
      from: 'on'
      to: 'off'
  condition:
    condition: time
    after: '21:00'
    before: '00:00'
  action: 
    - service: switch.turn_on
      entity_id: switch.light_sascha
    - service: switch.turn_on
      entity_id: switch.light_nicole 

# Turn off lights in livingroom after TV is switched off
- alias: 'Turn off lights in livingroom after TV is switched off'
  trigger:
    - platform: state
      entity_id: switch.tv
      from: 'on'
      to: 'off'
  condition:
    condition: time
    after: '21:00'
    before: '05:00'
  action: 
    - service: script.turn_off_livingroom_delay_15
    - service: notify.ios_iphones
      data:
        title: 'Timer'
        message: 'I will turn of the lights in 15 minutes. Good Night.'

# Turn on lights in the livingroom if someone is awake before sun rises
- alias: 'Livingroom lights in the morning'
  trigger:
    - platform: state
      entity_id: light.gang
      from: 'off'
      to: 'on'
  condition:
    condition: and
    conditions:
      - condition: sun
        after: sunrise
        after_offset: '-01:00:00'
      - condition: sun
        after: sunrise
        after_offset: '+00:00:00'
  action:
    - service: light.turn_on
      data: 
        entity_id: group.wohnzimmer_lampen
        brightness: 150