- alias: 'Lights: Turn on livingroom lights at sunset'
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: sensor.dark_outside
      from: 'off' 
      to: 'on'
    - platform: state
      entity_id: group.personen
      from: 'not_home'
      to: 'home'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: group.personen
        state: 'home'
      - condition: or
        conditions:
          - condition: state
            entity_id: sensor.dark_outside
            state: 'on'
          - condition: time
            before: '03:00'
  action:
    - service: script.turn_on 
      data_template:
        entity_id: >
          {% if is_state('switch.tv', 'on') %}
            script.turn_on_livingroom_dimmed_lights
          {% else %}
            script.turn_on_livingroom_default_lights
          {% endif %}
    # - service: homeassistant.turn_on
    #   entity_id: group.christmas

# Turn on light at Sofa if ATV is paused   
- alias: 'Lights: Dim lights when AppleTV is played'
  initial_state: 'on'   
  trigger:    
    - platform: state   
      entity_id: media_player.wohnzimmer    
      from: 'paused'    
      to: 'playing'     
  condition:    
    condition: and    
    conditions:   
      - condition: state
        entity_id: sensor.dark_outside
        state: 'on'
      - condition: time   
        after: '21:00'    
        before: '03:00'
      - condition: state
        entity_id: light.sofa
        state: 'on'   
  action:   
    - service: script.turn_on_livingroom_dimmed_lights

# Turn on light at Sofa if ATV is paused
- alias: 'Lights: Turn on light when AppleTV is paused'
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: media_player.wohnzimmer
      from: 'playing'
      to: 'paused'
      for:
        seconds: 1
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: sensor.dark_outside
        state: 'on'
      - condition: time
        after: '21:00'
        before: '03:00'
      - condition: state
        entity_id: light.sofa
        state: 'on'
  action:
    - service: script.turn_on_livingroom_default_lights

- alias: 'Lights: 60 minutes timer for devices at night'
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: group.bed_room
      from: 'off'
      to: 'on'
  condition:
    condition: time
    after: '23:00'
    before: '05:00'
  action:
    - service: script.turn_off_bedroom_delay_60

# Turn off devices in the livingroom 10 minutes when switched on after 3:01
- alias: 'Lights: 15 minutes timer for devices at night'
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: group.living_room
      from: 'off'
      to: 'on'
  condition:
    condition: time
    after: '03:01'
    before: '05:00'
  action:
    - service: script.turn_off_livingroom_delay_10

# Turn on lights in bedroom, if TV is switched off
- alias: 'Lights: Turn on lights in bedroom after TV is switched off'
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: switch.tv
      from: 'on'
      to: 'off'
  condition:
    condition: time
    after: '20:00'
    before: '02:00'
  action: 
    - service: script.turn_on_bedroom_dimmed_lights
    - service: script.turn_on_bath_default_lights
    - service: script.turn_off_livingroom_delay_10

# Turn on lights in the livingroom if someone is awake before sun rises
- alias: 'Lights: Turn on livingroom lights in the morning from Tue to Sat'
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: light.bad
      from: 'off'
      to: 'on'
    - platform: state
      entity_id: light.kueche1
      from: 'off'
      to: 'on'
    - platform: state
      entity_id: light.eingang
      from: 'off'
      to: 'on'
  condition:
    condition: and
    conditions:
      - condition: time
        after: '06:30'
        before: '10:00'
        weekday:
          - tue
          - wed
          - thu
          - fri
          - sat
      - condition: state
        entity_id: sensor.dark_outside
        state: 'on'
  action:
    - service: script.turn_off
      entity_id: script.turn_off_livingroom_lights_delay_30
    - service: script.turn_on_livingroom_morning
    - service: script.turn_off_livingroom_lights_delay_30

    # Turn on lights in the livingroom if someone is awake before sun rises
- alias: 'Lights: Turn on livingroom lights in the morning on Mondays'
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: light.bad
      from: 'off'
      to: 'on'
    - platform: state
      entity_id: light.kueche1
      from: 'off'
      to: 'on'
    - platform: state
      entity_id: light.eingang
      from: 'off'
      to: 'on'
  condition:
    condition: and
    conditions:
      - condition: time
        after: '05:00'
        before: '10:00'
        weekday:
          - mon
      - condition: state
        entity_id: sensor.dark_outside
        state: 'on'
  action:
    - service: script.turn_off
      entity_id: script.turn_off_livingroom_lights_delay_30
    - service: script.turn_on_livingroom_morning
    - service: script.turn_off_livingroom_lights_delay_30

- alias: 'Lights: Dim hallway light at night'
  initial_state: 'on'
  trigger:
      platform: time
      at: '22:00'
  action:
    - service: light.turn_on
      data: 
        entity_id: light.bad
        brightness: 10
    - delay:
        seconds: 2
    - service: light.turn_off
      entity_id: light.bad

- alias: 'Lights: Set hallway light to be brighter during the day'
  initial_state: 'on'
  trigger:
      platform: time
      at: '04:55'
  action:
    - service: light.turn_on
      data: 
        entity_id: light.bad
        brightness: 50
        transition: 4
    - delay:
        seconds: 1 
    - service: light.turn_off
      entity_id: light.bad

- alias: 'Lights: Turn on light in the kitchen if motion is detected'
  trigger:
    platform: state
    entity_id: binary_sensor.motion_sensor_158d0001a90475
    from: 'off'
    to: 'on'
  condition:
    - condition: state
      entity_id: sensor.dark_outside
      state: 'on'
  action:
    - service: script.turn_on_kitchen_lights

- alias: 'Lights: Turn off light in the kitchen if there is no motion for 2.5 minutes'
  trigger:
    platform: state
    entity_id: binary_sensor.motion_sensor_158d0001a90475
    from: 'on'
    to: 'off'
    for: 
      seconds: 30
  action:
    - service: script.turn_off_kitchen_lights

- alias: 'Lights: Turn on light in bathroom if motion is detected'
  trigger:
    platform: state
    entity_id: binary_sensor.motion_sensor_158d000121c575
    from: 'off'
    to: 'on'
  condition:
    condition: and
    conditions:
      - condition: time
        after: '16:00'
        before: '02:00'
      - condition: state
        entity_id: sensor.dark_outside
        state: 'on'
  action:
    - service: script.turn_on_bath_default_lights

- alias: 'Lights: Turn off light in bathroom if there is no motion for 3 minutes'
  trigger:
    platform: state
    entity_id: binary_sensor.motion_sensor_158d000121c575
    from: 'on'
    to: 'off'
    for: 
      minutes: 1
  action:
    - service: light.turn_off
      data:
        entity_id: light.bath
        transition: 2

- alias: 'Lights: Turn on hallway light if door is opened'
  trigger:
    platform: state
    entity_id: binary_sensor.door_window_sensor_158d0001d8253a
    from: 'off'
    to: 'on'
  condition:
    - condition: state
      entity_id: sensor.dark_outside
      state: 'on'
  action:
    - service: light.turn_on
      data:
        entity_id: light.eingang

- alias: 'Lights: Toggle lights in bedroom'
  trigger:  
    platform: event
    event_type: click
    event_data:
      entity_id: binary_sensor.switch_158d0001d8795f
      click_type: single
  action:
    - service: light.toggle
      entity_id: light.bedroom_lights