- alias: 'Watch AppleTV'
  trigger:
    platform: state
    entity_id: input_select.tv_mode
    to: 'AppleTV'
  condition:  
   condition: state
   entity_id: switch.tv
   state: 'on'
  action:
    - service: script.input_apple_tv

- alias: 'Watch Plex'
  trigger:
    platform: state
    entity_id: input_select.tv_mode
    to: 'Plex'
  condition:  
   condition: state
   entity_id: switch.tv
   state: 'on'
  action:
    - service: script.input_plex

- alias: 'Watch FireTV'
  trigger:
    platform: state
    entity_id: input_select.tv_mode
    to: 'FireTV'
  condition:  
   condition: state
   entity_id: switch.tv
   state: 'on'
  action:
    - service: script.input_fire_tv

- alias: 'Watch TV'
  trigger:
    platform: state
    entity_id: input_select.tv_mode
    to: 'TV'
  condition:  
   condition: state
   entity_id: switch.tv
   state: 'on'
  action:
    - service: script.input_tv

- alias: 'Listen to music'
  trigger:
    platform: state
    entity_id: input_select.tv_mode
    to: 'Music'
  condition:  
   condition: state
   entity_id: switch.tv
   state: 'on'
  action:
    - service: script.input_music

- alias: 'Watch AppleTV + TV'
  trigger:
    platform: state
    entity_id: input_select.tv_mode
    to: 'AppleTV'
  condition:  
   condition: state
   entity_id: switch.tv
   state: 'off'
  action:
    - service: switch.turn_on
      entity_id: switch.tv
    - delay:
        seconds: 20
    - service: script.input_apple_tv

- alias: 'Watch Plex + TV'
  trigger:
    platform: state
    entity_id: input_select.tv_mode
    to: 'Plex'
  condition:  
   condition: state
   entity_id: switch.tv
   state: 'off'
  action:
    - service: switch.turn_on
      entity_id: switch.tv
    - delay:
        seconds: 20
    - service: script.input_plex

- alias: 'Watch FireTV + TV'
  trigger:
    platform: state
    entity_id: input_select.tv_mode
    to: 'FireTV'
  condition:  
   condition: state
   entity_id: switch.tv
   state: 'off'
  action:
    - service: switch.turn_on
      entity_id: switch.tv
    - delay:
        seconds: 20
    - service: script.input_fire_tv

- alias: 'Watch TV + TV'
  trigger:
    platform: state
    entity_id: input_select.tv_mode
    to: 'TV'
  condition:  
   condition: state
   entity_id: switch.tv
   state: 'off'
  action:
    - service: switch.turn_on
      entity_id: switch.tv
    - delay:
        seconds: 20
    - service: script.input_tv

- alias: 'Listen to music + TV'
  trigger:
    platform: state
    entity_id: input_select.tv_mode
    to: 'Music'
  condition:  
   condition: state
   entity_id: switch.tv
   state: 'off'
  action:
    - service: switch.turn_on
      entity_id: switch.tv
    - delay:
        seconds: 20
    - service: script.input_music

- alias: 'Turn off TV'
  trigger:
    platform: state
    entity_id: input_select.tv_mode
    to: 'AUS'
  action:
    - service: switch.turn_off
      entity_id: switch.tv

- alias: Speaker - Adjust Volume
  trigger:
    platform: state
    entity_id: input_slider.sonos_speaker
  action:
    - service: media_player.volume_set
      data_template:
        entity_id: media_player.living_room
        volume_level: '{{ trigger.to_state.state }}'

- alias: Speaker- Volume
  trigger:
    platform: state
    entity_id: media_player.living_room
  action:
    - service: input_slider.select_value
      data_template:
        entity_id: input_slider.sonos_speaker
        value: '{{ states.media_player.living_room.attributes.volume_level }}'

- alias: 'Pause AppleTV if SONOS is used'
  trigger:
    platform: state
    entity_id: media_player.living_room
    from: 'paused'
    to: 'playing'
  condition:
    - condition: state
      entity_id: media_player.atv_wohnzimmer
      state: 'playing'
  action:
    - service: media_player.media_pause
      entity_id: media_player.atv_wohnzimmer

- alias: 'Auto standby is Sonos is paused for 10 minutes'
  trigger:
    platform: state
    entity_id: media_player.living_room
    from: 'playing'
    to: 'paused'
    for:
        minutes: 10
  action:
    - service: switch.turn_off
      entity_id: switch.sonos_speaker

- alias: 'Pause SONOS if AppleTV is used'
  trigger:
    - platform: state
      entity_id: media_player.atv_wohnzimmer
      from: 'paused'
      to: 'playing'
    - platform: state
      entity_id: input_select.tv_mode
      to: 'AppleTV'
    - platform: state
      entity_id: input_select.tv_mode
      to: 'TV'
    - platform: state
      entity_id: input_select.tv_mode
      to: 'Plex'
    - platform: state
      entity_id: input_select.tv_mode
      to: 'FireTV'
  condition:
    - condition: state
      entity_id: media_player.living_room
      state: 'playing'
  action:
    - service: media_player.media_pause
      entity_id: media_player.living_room
