- alias: 'Media: Watch AppleTV'
  trigger:
    platform: state
    entity_id: input_select.tv_mode
    to: 'AppleTV'
  condition:  
   condition: state
   entity_id: switch.tv
   state: 'on'
  action:
    - service: script.input_apple_tv

- alias: 'Media: Watch Plex'
  trigger:
    platform: state
    entity_id: input_select.tv_mode
    to: 'Plex'
  condition:  
   condition: state
   entity_id: switch.tv
   state: 'on'
  action:
    - service: script.input_plex

- alias: 'Media: Watch TV'
  trigger:
    platform: state
    entity_id: input_select.tv_mode
    to: 'TV'
  condition:  
   condition: state
   entity_id: switch.tv
   state: 'on'
  action:
    - service: script.input_tv

- alias: 'Media: Listen to music'
  trigger:
    platform: state
    entity_id: input_select.tv_mode
    to: 'Music'
  condition:  
   condition: state
   entity_id: switch.tv
   state: 'on'
  action:
    - service: script.input_music

- alias: 'Media: Watch AppleTV + TV'
  trigger:
    platform: state
    entity_id: input_select.tv_mode
    to: 'AppleTV'
  condition:  
   condition: state
   entity_id: switch.tv
   state: 'off'
  action:
    - service: switch.turn_on
      entity_id: switch.tv
    - delay:
        seconds: 15
    - service: script.input_apple_tv

- alias: 'Media: Watch Plex + TV'
  trigger:
    platform: state
    entity_id: input_select.tv_mode
    to: 'Plex'
  condition:  
   condition: state
   entity_id: switch.tv
   state: 'off'
  action:
    - service: switch.turn_on
      entity_id: switch.tv
    - delay:
        seconds: 15
    - service: script.input_plex

- alias: 'Media: Watch TV + TV'
  trigger:
    platform: state
    entity_id: input_select.tv_mode
    to: 'TV'
  condition:  
   condition: state
   entity_id: switch.tv
   state: 'off'
  action:
    - service: switch.turn_on
      entity_id: switch.tv
    - delay:
        seconds: 15
    - service: script.input_tv

- alias: 'Media: Listen to music + TV'
  trigger:
    platform: state
    entity_id: input_select.tv_mode
    to: 'Music'
  condition:  
   condition: state
   entity_id: switch.tv
   state: 'off'
  action:
    - service: script.livingroom_dimmed_lights
    - service: script.input_music

- alias: "Play selected source on sonos"
  trigger:
    - entity_id: input_select.sonos_source
      platform: state
      from: 'SELECT'
  condition:  
   condition: state
   entity_id: switch.speaker_1
   state: 'on'    
  action:
  - service: media_player.shuffle_set
    data:
      entity_id: media_player.living_room
      shuffle: true
  - data_template:
      source: "{{ trigger.to_state.state }}"
    entity_id: media_player.living_room
    service: media_player.select_source
  - service: input_select.select_option
    data:
      entity_id: input_select.sonos_source
      option: 'SELECT'

- alias: "Play selected source on sonos + sonos"
  trigger:
    - entity_id: input_select.sonos_source
      platform: state
      from: 'SELECT'
  condition:  
   condition: state
   entity_id: switch.speaker_1
   state: 'off'    
  action:
  - service: switch.turn_on
    entity_id: switch.speaker_1
  - delay:
      seconds: 35
  - service: media_player.shuffle_set
    data:
      entity_id: media_player.living_room
      shuffle: true
  - data_template:
      source: "{{ trigger.to_state.state }}"
    entity_id: media_player.living_room
    service: media_player.select_source
  - service: input_select.select_option
    data:
      entity_id: input_select.sonos_source
      option: 'SELECT'

- alias: 'Media: Turn off TV'
  trigger:
    platform: state
    entity_id: input_select.tv_mode
    to: 'AUS'
  action:
    - service: switch.turn_off
      entity_id: switch.tv

- alias: Speaker - Adjust Volume
  trigger:
    platform: state
    entity_id: input_number.sonos_speaker
  action:
    - service: media_player.volume_set
      data_template:
        entity_id: media_player.living_room
        volume_level: '{{ trigger.to_state.state }}'

- alias: Speaker - Update Volume slider
  trigger:
    platform: state
    entity_id: media_player.living_room
  action:
    - service: input_number.set_value
      data_template:
        entity_id: input_number.sonos_speaker
        value: '{{ states.media_player.living_room.attributes.volume_level }}'


- alias: 'Media: Pause AppleTV if SONOS is used'
  trigger:
    platform: state
    entity_id: media_player.living_room
    from: 'paused'
    to: 'playing'
  condition:
    - condition: state
      entity_id: media_player.wohnzimmer
      state: 'playing'
  action:
    - service: media_player.media_pause
      entity_id: media_player.wohnzimmer

- alias: 'Media: Auto standby is Sonos is paused for 10 minutes'
  trigger:
    platform: state
    entity_id: media_player.living_room
    from: 'playing'
    to: 'paused'
    for:
        minutes: 10
  action:
    - service: switch.turn_off
      entity_id: switch.speaker_1

- alias: 'Media: Pause SONOS if AppleTV is used'
  trigger:
    - platform: state
      entity_id: media_player.wohnzimmer
      from: 'paused'
      to: 'playing'
  condition:
    - condition: state
      entity_id: media_player.living_room
      state: 'playing'
  action:
    - service: media_player.media_pause
      entity_id: media_player.living_room

- alias: 'Media: Play Radio when someone arrives at home'
  trigger:
    platform: state
    entity_id: group.personen
    from: 'not_home'
    to: 'home'
  condition:
    - condition: time
      after: '08:00'
      before: '23:00'
  action:
    - service: script.sonos_play_radio

- alias: 'Media: Turn on radio in the morning'
  trigger:
    - platform: state
      entity_id: light.bad
      from: 'off'
      to: 'on'
    - platform: state
      entity_id: light.kueche1
      from: 'off'
      to: 'on'
    - platform: state
      entity_id: light.eingang
      from: 'off'
      to: 'on'
  condition:
    condition: and
    conditions:
    - condition: time
      after: '07:00'
      before: '10:00'
    - condition: state
      entity_id: switch.tv
      state: 'off'
    - condition: or
      conditions:
      - condition: state
        entity_id: switch.speaker_1
        state: 'off'
      - condition: state
        entity_id: media_player.living_room
        state: 'paused'
  action:
    - service: script.sonos_play_radio
      data:
        variables:
          volume: 0.1
