- alias: 'watch AppleTV'
  trigger:
    platform: state
    entity_id: input_select.tv_mode
    to: 'AppleTV'
  condition:  
   condition: state
   entity_id: switch.tv
   state: 'on'
  action:
    - service: script.input_apple_tv

- alias: 'watch Plex'
  trigger:
    platform: state
    entity_id: input_select.tv_mode
    to: 'Plex'
  condition:  
   condition: state
   entity_id: switch.tv
   state: 'on'
  action:
    - service: script.input_plex

- alias: 'watch FireTV'
  trigger:
    platform: state
    entity_id: input_select.tv_mode
    to: 'FireTV'
  condition:  
   condition: state
   entity_id: switch.tv
   state: 'on'
  action:
    - service: script.input_fire_tv

- alias: 'watch TV'
  trigger:
    platform: state
    entity_id: input_select.tv_mode
    to: 'Fernseher'
  condition:  
   condition: state
   entity_id: switch.tv
   state: 'on'
  action:
    - service: script.input_tv

- alias: 'listen to music'
  trigger:
    platform: state
    entity_id: input_select.tv_mode
    to: 'Music'
  condition:  
   condition: state
   entity_id: switch.tv
   state: 'on'
  action:
    - service: script.input_music

- alias: 'watch AppleTV + TV'
  trigger:
    platform: state
    entity_id: input_select.tv_mode
    to: 'AppleTV'
  condition:  
   condition: state
   entity_id: switch.tv
   state: 'off'
  action:
    - service: switch.turn_on
      entity_id: switch.tv
    - delay:
        seconds: 20
    - service: script.input_apple_tv


- alias: 'watch Plex + TV'
  trigger:
    platform: state
    entity_id: input_select.tv_mode
    to: 'Plex'
  condition:  
   condition: state
   entity_id: switch.tv
   state: 'off'
  action:
    - service: switch.turn_on
      entity_id: switch.tv
    - delay:
        seconds: 20
    - service: script.input_plex

- alias: 'watch FireTV + TV'
  trigger:
    platform: state
    entity_id: input_select.tv_mode
    to: 'FireTV'
  condition:  
   condition: state
   entity_id: switch.tv
   state: 'off'
  action:
    - service: switch.turn_on
      entity_id: switch.tv
    - delay:
        seconds: 20
    - service: script.input_fire_tv

- alias: 'watch TV + TV'
  trigger:
    platform: state
    entity_id: input_select.tv_mode
    to: 'Fernseher'
  condition:  
   condition: state
   entity_id: switch.tv
   state: 'off'
  action:
    - service: switch.turn_on
      entity_id: switch.tv
    - delay:
        seconds: 20
    - service: script.input_tv

- alias: 'listen to music'
  trigger:
    platform: state
    entity_id: input_select.tv_mode
    to: 'Music'
  condition:  
   condition: state
   entity_id: switch.tv
   state: 'off'
  action:
    - service: switch.turn_on
      entity_id: switch.tv
    - delay:
        seconds: 20
    - service: script.input_music

- alias: 'Turn off TV'
  trigger:
    platform: state
    entity_id: input_select.tv_mode
    to: 'AUS'
  action:
    - service: switch.turn_off
      entity_id: switch.tv

- alias: 'Turn on TV if media is played'
  trigger: 
    - platform: state
      entity_id: media_player.appletv
      from: 'paused'
      to: 'playing' 
  condition:
    condition: state
    entity_id: switch.tv
    state: 'off'
  action:
    - service: switch.turn_on
      entity_id: switch.tv
    - delay:
        seconds: 20
    - service: input_select.select_option
      data:
        entity_id: input_select.tv_mode
        option: Music