- alias: 'Misc: Turn off all'
  trigger:
      platform: time
      at: '03:00'
  action:
    - service: script.turn_off_all


- alias: 'Misc: Update Available Notifications'
  trigger:
    platform: state
    entity_id: updater.updater
  action:
    - service: notify.ios_iphones_app
      data:
        title: 'Update'
        message: 'Update for Home Assistant is available.'

# Inspired by https://community.home-assistant.io/t/logger-set-level/14267
- alias: 'Misc: Log Level'
  trigger:
    platform: state
    entity_id: input_select.log_level
  action:
    service: logger.set_level
    data_template:
      homeassistant.components: "{{ trigger.to_state.state }}"


# automations for the fan
- alias: 'Misc: Activate Fan auto off'
  trigger:
    platform: state
    entity_id: switch.ventilator
    to: 'on'
  action: 
    - service: script.turn_on
      entity_id: script.turn_off_fan_after_delay

- alias: 'Misc: Deactivate fan auto off'
  trigger:
    platform: state
    entity_id: switch.ventilator
    to: 'off'
  action: 
    - service: script.turn_off
      entity_id: script.turn_off_fan_after_delay 

- alias: 'Misc: Turn of speaker if unused at startup'
  trigger:
    platform: homeassistant
    event: start
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: group.personen
        state: 'home'
      - condition: state
        entity_id: media_player.living_room
        state: 'paused'
  action:
    - service: switch.turn_off
      entity_id: switch.sonos_speaker

# - alias: 'Misc: Startup default states'
#   trigger:
#     platform: homeassistant
#     event: start
#   action:
#     - service: input_select.select_option
#       data:
#         entity_id: input_select.tv_mode
#         option: AppleTV

- alias: 'Misc: Startup nobody is home'
  trigger:
    platform: homeassistant
    event: start
  condition:
    - condition: state
      entity_id: group.personen
      state: 'not_home'
  action:
    - service: switch.turn_off
      entity_id: switch.sonos_speaker
    - service: input_select.select_option
      data:
        entity_id: input_select.tv_mode
        option: AUS

- alias: 'Misc: Update config if travis build is successfull'
  trigger:
    platform: state
    entity_id: sensor.travis_build_label
  condition:
    - condition: state
      entity_id: sensor.travis_status
      state: 'Success'
  action:
    # turn on TV before updating the config, since the broadlink needs to be on during startup
    - service: script.prepare_restart
    - service: script.get_latest_config

- alias: 'Misc: Raspberry full volume'
  trigger:
    platform: numeric_state
    entity_id: sensor.disk_use_
    above: 90
  action:
    - service: notify.ios_iphones_app
      data:
        title: 'System'
        message: 'Volume is running out of space. Current usage is: {{states.sensor.disk_use_.state}}%'