- alias: "Misc: Turn off all"
  initial_state: "on"
  trigger:
    platform: time
    at: "03:00"
  action:
    - service: script.turn_off_all

# Inspired by https://community.home-assistant.io/t/logger-set-level/14267
- alias: "Misc: Log Level"
  initial_state: "on"
  trigger:
    platform: state
    entity_id: input_select.log_level
  action:
    service: logger.set_level
    data_template:
      homeassistant.components: "{{ trigger.to_state.state }}"

# - alias: 'Misc: Activate Fan auto off'
#   initial_state: 'on'
#   trigger:
#     platform: state
#     entity_id: fan.fan
#     to: 'on'
#   action:
#     - service: script.turn_off_fan_after_delay

# - alias: 'Misc: Deactivate fan auto off'
#   initial_state: 'on'
#   trigger:
#     platform: state
#     entity_id: fan.fan
#     to: 'off'
#   action:
#     - service: script.turn_off
#       entity_id: script.turn_off_fan_after_delay
