- alias: 'Misc: Turn off all'
  initial_state: 'on'
  trigger:
      platform: time
      at: '03:00'
  action:
    - service: script.turn_off_all

- alias: 'Misc: Update Available Notifications'
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: updater.updater
  action:
    - service: notify.ios_iphones_app
      data:
        title: 'Update'
        message: 'Update for Home Assistant is available.'

# Inspired by https://community.home-assistant.io/t/logger-set-level/14267
- alias: 'Misc: Log Level'
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: input_select.log_level
  action:
    service: logger.set_level
    data_template:
      homeassistant.components: "{{ trigger.to_state.state }}"

- alias: 'Misc: Activate Fan auto off'
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: fan.fan
    to: 'on'
  action: 
    - service: script.turn_off_fan_after_delay

- alias: 'Misc: Deactivate fan auto off'
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: fan.fan
    to: 'off'
  action: 
    - service: script.turn_off
      entity_id: script.turn_off_fan_after_delay 

- alias: 'Misc: Notify if travis build is successfull'
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: sensor.tribunex_home_assistant_last_build_state
    to: 'passed'
  action:
    - service: notify.ios_iphones_app
      data:
        title: 'Travis'
        message: 'Build was successful'
    - service: script.restart_hass

- alias: 'Misc: Raspberry full volume'
  initial_state: 'on'
  trigger:
    platform: numeric_state
    entity_id: sensor.disk_use_percent
    above: 90
  action:
    - service: notify.ios_iphones_app
      data:
        title: 'System'
        message: 'Volume is running out of space. Current usage is: {{states.sensor.disk_use_.state}}%'