- alias: 'Plants: Water notification' 
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: group.user_1
    from: 'not_home'
    to: 'home'
    for:
      minutes: 5 
  condition:
    condition: or
    conditions:
      - condition: state
        entity_id: plant.bonsai
        state: 'problem'
      - condition: state
        entity_id: plant.bad
        state: 'problem'
      - condition: state
        entity_id: plant.palme_small
        state: 'problem'
      - condition: state
        entity_id: plant.palme
        state: 'problem'
  action:
    - service: notify.ios_iphones_app
      data_template:
        title: 'Plants'
        message: >
          'Please water Plant '
          {% if is_state('plant.bonsai', 'problem') %}
            'Bonsai! Moisture: {{states.sensor.bonsai_moisture.state}}% | Conductivity: {{states.sensor.bonsai_conductivity.state}}'
          {% else %}
            {% if is_state('plant.palm', 'problem') %}
              'Palm! Moisture: {{states.sensor.palme_moisture.state}}% | Conductivity: {{states.sensor.palme_conductivity.state}}'
            {% else %}
              {% if is_state('plant.palm_small', 'problem') %}
                'Palm next to the computer! Moisture: {{states.sensor.palmek_moisture.state}}% | Conductivity: {{states.sensor.palmek_conductivity.state}}'
              {% else %}
                {% if is_state('plant.bad', 'problem') %}
                  'in the Bathroom! Moisture: {{states.sensor.bad_moisture.state}}% | Conductivity: {{states.sensor.bad_conductivity.state}}'
                {% endif %}
              {% endif %}
            {% endif %}
          {% endif %}