- alias: 'Plants: Water Bathroom plant' 
  hide_entity: True
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: group.user_1
    from: 'not_home'
    to: 'home'
    for:
      minutes: 5
  condition:
    condition: numeric_state
    entity_id: sensor.bad_moisture
    below: 15
  action:
    - service: notify.ios_iphones_app
      data:
        title: 'Plants'
        message: 'Please water plant in the bathroom! Moisture: {{states.sensor.bad_moisture.state}}% | Conductivity: {{states.sensor.bad_conductivity.state}}'

- alias: 'Plants: Water Bonsai plant' 
  hide_entity: True
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: group.user_1
    from: 'not_home'
    to: 'home'
    for:
      minutes: 4 
  condition:
    condition: numeric_state
    entity_id: sensor.bonsai_moisture
    below: 10
  action:
    - service: notify.ios_iphones_app
      data:
        title: 'Plants'
        message: 'Please water Plant Bonsai! Moisture: {{states.sensor.bonsai_moisture.state}}% | Conductivity: {{states.sensor.bonsai_conductivity.state}}'

- alias: 'Plants: Water Palm plant'
  hide_entity: True 
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: group.user_1
    from: 'not_home'
    to: 'home'
    for:
      minutes: 3 
  condition:
    condition: numeric_state
    entity_id: sensor.palme_moisture
    below: 20
  action:
    - service: notify.ios_iphones_app
      data:
        title: 'Plants'
        message: 'Please water Palm! Moisture: {{states.sensor.palme_moisture.state}}% | Conductivity: {{states.sensor.palme_conductivity.state}}'

- alias: 'Plants: Water small palm plant'
  hide_entity: True 
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: group.user_1
    from: 'not_home'
    to: 'home'
    for:
      minutes: 6 
  condition:
    condition: numeric_state
    entity_id: sensor.palme_moisture
    below: 15
  action:
    - service: notify.ios_iphones_app
      data:
        title: 'Plants'
        message: 'Please water Palm next to the computer! Moisture: {{states.sensor.palmek_moisture.state}}% | Conductivity: {{states.sensor.palmek_conductivity.state}}'
