- alias: 'Presence: Nicole left home'
  initial_state: 'on'
  trigger:
    platform: zone
    entity_id: device_tracker.owntracks_nicole_iphone
    zone: zone.home
    event: leave
  condition:
    condition: state    
    entity_id: group.sascha   
    state: 'not home'  
  action:
    - service: notify.ios_iphones_app
      data:
        title: 'Location'
        message: 'Nicole left home.'

- alias: 'Presence: Nicole arrived at home'
  initial_state: 'on'
  trigger:
    platform: zone
    entity_id: device_tracker.owntracks_nicole_iphone
    zone: zone.home
    event: enter
  action:
    - service: notify.ios_iphones_app
      data:
        title: 'Location'
        message: 'Nicole arrived at home.'

- alias: 'Presence: Nicole left work'
  initial_state: 'on'
  trigger:
    platform: zone
    entity_id: device_tracker.owntracks_nicole_iphone
    zone: zone.work_nicole
    event: leave
  action:
    - service: notify.ios_iphones_app
      data:
        title: 'Location'
        message: 'Nicole left work.'

- alias: 'Presence: Nicole arrived at work'
  initial_state: 'on'
  trigger:
    platform: zone
    entity_id: device_tracker.owntracks_nicole_iphone
    zone: zone.work_nicole
    event: enter
  action:
    - service: notify.ios_iphones_app
      data:
        title: 'Location'
        message: 'Nicole arrived at work.'

- alias: 'Presence: Nobody at home'
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: group.personen
    from: 'home'
    to: 'not_home'
    for: 
      minutes: 5 
  action:
    - service: script.turn_off_all
  #- service: notify.ios_iphones_app
    #  data:
    #    title: 'Location'
    #    message: 'Everybody left. I will switch off all devices.'