- alias: 'Nicole left home'
  trigger:
    platform: zone
    entity_id: device_tracker.nicoles_iphone_app
    zone: zone.home
    event: leave
  action:
    - service: notify.ios_iphones
      data:
        title: 'Location'
        message: 'Nicole left home.'

- alias: 'Nicole arrived at home'
  trigger:
    platform: zone
    entity_id: device_tracker.nicoles_iphone_app
    zone: zone.home
    event: enter
  action:
    - service: notify.ios_iphones
      data:
        title: 'Location'
        message: 'Nicole arrived at home.'

- alias: 'Nicole left work'
  trigger:
    platform: zone
    entity_id: device_tracker.nicoles_iphone_app
    zone: zone.work_nicole
    event: leave
  action:
    - service: notify.ios_iphones
      data:
        title: 'Location'
        message: 'Nicole left work.'

- alias: 'Nicole arrived at work'
  trigger:
    platform: zone
    entity_id: device_tracker.nicoles_iphone_app
    zone: zone.work_nicole
    event: enter
  action:
    - service: notify.ios_iphones
      data:
        title: 'Location'
        message: 'Nicole arrived at work.'

- alias: 'Nobody at home'
  trigger:
    platform: state
    entity_id: group.personen
    from: 'home'
    to: 'not_home'
    for: 
      minutes: 5 
  action:
    - service: script.turn_off_all
  #- service: notify.ios_iphones
    #  data:
    #    title: 'Location'
    #    message: 'Everybody left. I will switch off all devices.'