- alias: 'Nicole left'
  hide_entity: True
  trigger:
    platform: state
    entity_id: device_tracker.nicolesiphone
    # Optional 
    from: 'home'
    to: 'not_home'
  action:
    - service: notify.ios_iphones
      data:
        title: 'Location'
        message: 'Nicole left.'

- alias: 'Nicole arrived'
  hide_entity: True
  trigger:
    platform: state
    entity_id: device_tracker.nicolesiphone
    # Optional 
    from: 'not_home'
    to: 'home'
  action:
    - service: notify.ios_iphones
      data:
        title: 'Location'
        message: 'Nicole arrived.'


- alias: 'Nobody at home'
  hide_entity: True
  trigger:
    platform: state
    entity_id: group.personen
    from: 'home'
    to: 'not_home'
    for:
      minutes: 5 
  action:
    - service: notify.ios_iphones
      data:
        title: 'Location'
        message: 'Everybody left. I will switch off all devices.'
    - service: switch.turn_off