- alias: "Presence: User 2 left home"
  initial_state: "on"
  trigger:
    - platform: state
      entity_id: device_tracker.user_2_iphone
      from: "away"
  condition:
    condition: state
    entity_id: group.user_1
    state: "not home"
  action:
    - service: notify.devices_user_1
      data:
        title: "Location"
        message: "User 2 left home."

- alias: "Presence: User 2 arrived at home"
  initial_state: "on"
  trigger:
    - platform: state
      entity_id: device_tracker.user_2_iphone
      to: "home"
  action:
    - service: notify.devices_user_1
      data:
        title: "Location"
        message: "User 2 arrived at home."

- alias: "Presence: Nobody at home"
  initial_state: "on"
  trigger:
    - platform: state
      entity_id: group.personen
      from: "home"
      to: "not_home"
  action:
    - service: script.turn_off_all
