- alias: 'Prices: Notify if cruise price is lower'
  initial_state: 'on'
  trigger:
    - platform: numeric_state
      entity_id: sensor.mein_schiff_ostsee
      below: 1945
  action:
    - service: notify.ios_iphones_app
      data:
        title: 'Price Drop'
        message: 'The cruise is cheaper: ({{states.sensor.mein_schiff_price.state}}€)'

- alias: 'Prices: Notify if cruise price is higher'
  initial_state: 'on'
  trigger:
    - platform: numeric_state
      entity_id: sensor.mein_schiff_ostsee
      above: 1945
  action:
    - service: notify.ios_iphones_app
      data:
        title: 'Price Increase'
        message: 'The cruise is more expensive: ({{states.sensor.mein_schiff_price.state}}€)'