- alias: 'Prices: Notify if cruise price is lower'
  initial_state: 'on'
  trigger:
    - platform: numeric_state
      entity_id: sensor.mein_schiff_price
      below: 1395
  action:
    - service: notify.ios_iphones_app
      data:
        title: 'Price Drop'
        message: 'The cruise is cheaper: ({{states.sensor.mein_schiff_price.state}}€)'
