# Inspired by https://github.com/CCOSTAN/Home-AssistantConfig
- alias: "Printer: Printer ink levels"
  initial_state: "on"
  trigger:
    - platform: numeric_state
      entity_id: sensor.epson_ink_level_black, sensor.epson_ink_level_magenta, sensor.epson_ink_level_yellow, sensor.epson_ink_level_cyan
      below: 10
  action:
    - service: notify.devices_user_1
      data_template:
        title: "Devices"
        message: "Ink is low! {{ trigger.to_state.attributes.friendly_name }} is {{ trigger.to_state.state }}"
