- alias: 'Robot: Robot started cleaning' 
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: vacuum.vacuum_cleaner
    from: 'docked'
    to: 'cleaning'
  action:
    - service: notify.mobile_app_batphone
      data:
        title: 'Robot'
        message: 'Robot started to clean!'

- alias: 'Robot: Robot stopped cleaning' 
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: vacuum.vacuum_cleaner
    from: 'returning'
    to: 'docked'
  action:
    - service: notify.mobile_app_batphone
      data:
        title: 'Robot'
        message: 'Cleanup successful after {{states.vacuum.vacuum_cleaner.attributes.cleaning_time}} minutes.'
    - service: input_boolean.turn_on
      data:
        entity_id: input_boolean.cleaned_today

- alias: 'Robot: Robot cleanup if nobody is home'
  initial_state: 'on'
  trigger:
    platform: time
    at: '14:00'
  condition:
    condition: and
    conditions:
      - condition: time
        weekday:
          - mon
          - fri
      - condition: state
        entity_id: group.personen
        state: 'not_home'
      - condition: state
        entity_id: input_boolean.cleaned_today
        state: 'off'
      - condition: state
        entity_id: input_boolean.vacation_mode
        state: 'off'
  action:
    - service: script.start_vacuum_cleaning

- alias: 'Robot: Robot waits until everybody left'
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: group.personen
    from: 'home'
    to: 'not_home' 
  condition:
    condition: and
    conditions:
      - condition: time
        after: '14:00:00'
        weekday:
          - mon
          - fri
      - condition: state
        entity_id: input_boolean.cleaned_today
        state: 'off'
      - condition: state
        entity_id: input_boolean.vacation_mode
        state: 'off'
  action:
    - service: script.start_vacuum_cleaning

- alias: 'Robot: Reset cleaned today counter'
  initial_state: 'on'
  trigger:
    platform: time
    at: '01:00:00'
  action:
    - service: input_boolean.turn_off
      data:
        entity_id: input_boolean.cleaned_today