- alias: 'Robot started cleaning' 
  trigger:
    platform: state
    entity_id: sensor.mi_info_status
    from: 'Charging'
    to: 'Cleaning'
  action:
    - service: notify.ios_iphones
      data:
        title: 'Robot'
        message: 'Robot started to clean!'

- alias: 'Robot stopped cleaning' 
  trigger:
    platform: state
    entity_id: sensor.mi_info_status
    from: 'Returning home'
    to: 'Charging'
  action:
    - service: notify.ios_iphones
      data:
        title: 'Robot'
        message: 'Robot started stopped cleaning after {{states.vacuum.staubsauger.state}} and is succesfully docked!'
    - service: input_boolean.turn_on
      data:
        entity_id: input_boolean.cleaned_today

- alias: 'Robot cleanup if nobody is home'
  trigger:
    platform: time
    at: '14:00'
  condition:
    condition: and
    conditions:
      - condition: time
        weekday:
          - mon
          - wed
          - fri
      - condition: state
        entity_id: group.personen
        state: 'not_home'
      - condition: state
        entity_id: input_boolean.cleaned_today
        state: 'off'
  action:
    - service: vacuum.turn_on
      entity_id: vacuum.staubsauger

- alias: 'Robot waits until everybody left'
  trigger:
    platform: state
    entity_id: group.personen
    from: 'home'
    to: 'not_home' 
  condition:
    condition: and
    conditions:
      - condition: time
        after: '14:00:00'
        weekday:
          - mon
          - wed
          - fri
      - condition: state
        entity_id: input_boolean.cleaned_today
        state: 'off'
  action:
    - service: vacuum.turn_on
      entity_id: vacuum.staubsauger

- alias: 'Reset cleaned today counter'
  trigger:
    platform: time
    at: '01:00:00'
  action:
    - service: input_boolean.turn_off
      data:
        entity_id: input_boolean.cleaned_today

- alias: 'Robot: Clean dust bin' 
  trigger:
    platform: state
    entity_id: device_tracker.iphones
    from: 'not_home'
    to: 'home'
    for:
      minutes: 10
  condition:
    - condition: state
      entity_id: input_boolean.cleaned_today
      state: 'on'
  action:
    - service: notify.ios_iphones
      data:
        title: 'Robot'
        message: 'Please clean the dust bin.'
