- alias: "Startup: Startup notification"
  initial_state: "on"
  trigger:
    - platform: homeassistant
      event: start
  action:
    - service: notify.devices_user_1
      data:
        title: "System"
        message: "Home Assistant started"
    - delay:
        minutes: 1
