- alias: 'Weather: CO2 Bedroom'
  initial_state: 'on'
  trigger:
    platform: numeric_state
    entity_id: sensor.netatmo_schlafzimmer_co2_2
    above: 900
  action:
    - service: notify.ios_iphones_app
      data:
        title: 'Rooms'
        message: 'High CO2 in bedroom Currently: {{states.sensor.netatmo_schlafzimmer_co2_2.state}}ppm'

- alias: 'Weather: CO2 Livingroom'
  initial_state: 'on'
  trigger:
    platform: numeric_state
    entity_id: sensor.netatmo_wohnzimmer_co2_2
    above: 900
  action:
    - service: notify.ios_iphones_app
      data:
        title: 'Rooms'
        message: 'High CO2 in bedroom Currently: {{states.sensor.netatmo_schlafzimmer_co2_2.state}}ppm'

- alias: 'Noise: Noise Livingroom'
  initial_state: 'on'
  trigger:
    platform: numeric_state
    entity_id: sensor.netatmo_wohnzimmer_noise_2
    above: 59
  action:
    - service: notify.ios_iphones_app
      data:
        title: 'Rooms'
        message: 'It is quite noise. Currently: {{states.sensor.netatmo_wohnzimmer_noise_2.state}}db'

- alias: 'Weather: Hotter outside'
  initial_state: 'on'
  trigger:
    - platform: numeric_state
      entity_id: sensor.out_vs_in
      above: 2
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: device_tracker.iphones
        state: 'home'
      - condition: numeric_state
        entity_id: 'sensor.netatmo_outdoor_temperature'
        above: '20'
      - condition: state
        entity_id: binary_sensor.door_window_sensor_158d0001b7700c
        state: 'on'
  action:
    - service: notify.ios_iphones_app
      data:
        title: 'Doors'
        message: 'Close the balcony door, since it is {{states.sensor.out_vs_in.state}}°C outside.'

  - alias: 'Weather: Colder outside'
  initial_state: 'on'
  trigger:
    - platform: numeric_state
      entity_id: sensor.out_vs_in
      below: -2
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: device_tracker.iphones
        state: 'home'
      - condition: numeric_state
        entity_id: 'sensor.netatmo_outdoor_temperature'
        above: '20'
      - condition: state
        entity_id: binary_sensor.door_window_sensor_158d0001b7700c
        state: 'off'
  action:
    - service: notify.ios_iphones_app
      data:
        title: 'Doors'
        message: 'Open the balcony door, since it is {{states.sensor.out_vs_in.state}}°C colder outside.'

- alias: 'Weather: Weather Report'
  initial_state: 'on'
  trigger:
    platform: time
    at: '07:00'
  condition:
    condition: state
    entity_id: device_tracker.iphones
    state: 'home'
  action:
    - service: notify.ios_iphones_app
      data:
        title: 'Weather Report for today'
        message: 'Current: {{states.sensor.netatmo_outdoor_temperature.state}}°C 
        H/L: {{states.sensor.dark_sky_daily_high_temperature.state}}°C/{{states.sensor.dark_sky_daily_low_temperature.state}}°C 
        {{states.sensor.dark_sky_hourly_summary.state}}'    

- alias: 'Weather: Rainy Day'
  initial_state: 'on'
  trigger:
    - platform: numeric_state
      entity_id: sensor.dark_sky_precip_probability
      above: 60
  condition:
    - condition: time   
      after: '07:00'    
      before: '20:00'
  action:
    - service: notify.ios_iphones_app
      data:
        title: 'Rain Alert'
        message: 'It looks like its gonna rain: ({{states.sensor.dark_sky_precip_probability.state}}%) / ({{states.sensor.dark_sky_precip_intensity.state}}). {{states.sensor.dark_sky_summary.state}}'

- alias: 'Weather: Rain detected by water sensor'
  trigger:
    platform: state
    entity_id: binary_sensor.water_leak_sensor_158d00021371e5
    from: 'off'
    to: 'on'
  condition:
    - condition: time   
      after: '07:00'    
      before: '22:00'
  action:
    - service: notify.ios_iphones_app
      data:
        title: 'Rain Alert'
        message: 'Water Sensor: Rain detected: ({{states.sensor.dark_sky_precip_probability.state}}%) / ({{states.sensor.dark_sky_precip_intensity.state}}). {{states.sensor.dark_sky_summary.state}}'

- alias: 'Weather: Stopped Rain detected by water sensor'
  trigger:
    platform: state
    entity_id: binary_sensor.water_leak_sensor_158d00021371e5
    from: 'on'
    to: 'off'
  condition:
    - condition: time   
      after: '07:00'    
      before: '22:00'
  action:
    - service: notify.ios_iphones_app
      data:
        title: 'Rain Alert'
        message: 'Water sensor: It looks like it stopped raining: ({{states.sensor.dark_sky_precip_probability.state}}%) / ({{states.sensor.dark_sky_precip_intensity.state}}). {{states.sensor.dark_sky_summary.state}}'

- alias: 'Weather: Rainy Day'
  initial_state: 'on'
  trigger:
    - platform: numeric_state
      entity_id: sensor.dark_sky_precip_probability
      below: 20
  condition:
    - condition: time   
      after: '07:00'    
      before: '20:00'
  action:
    - service: notify.ios_iphones_app
      data:
        title: 'Rain Stoppes'
        message: 'It looks like it stopped raining: ({{states.sensor.dark_sky_precip_probability.state}}%) / ({{states.sensor.dark_sky_precip_intensity.state}}). {{states.sensor.dark_sky_summary.state}}'