- alias: 'Weather: CO2 Bedroom'
  trigger:
    platform: numeric_state
    entity_id: sensor.netatmo_schlafzimmer_co2
    above: 900
  action:
    - service: notify.ios_iphones_app
      data:
        title: 'Rooms'
        message: 'High CO2 in bedroom Currently: {{states.sensor.netatmo_schlafzimmer_co2.state}}ppm'

- alias: 'Weather: CO2 Livingroom'
  trigger:
    platform: numeric_state
    entity_id: sensor.netatmo_wohnzimmer_co2
    above: 900
  action:
    - service: notify.ios_iphones_app
      data:
        title: 'Rooms'
        message: 'High CO2 in bedroom Currently: {{states.sensor.netatmo_schlafzimmer_co2.state}}ppm'

- alias: 'Weather: Noise Livingroom'
  trigger:
    platform: numeric_state
    entity_id: sensor.netatmo_wohnzimmer_noise
    above: 59
  action:
    - service: notify.ios_iphones_app
      data:
        title: 'Rooms'
        message: 'It is quite noise. Currently: {{states.sensor.netatmo_wohnzimmer_noise.state}}db'


- alias: 'Weather: Out vs In notification'
  trigger:
    - platform: numeric_state
      entity_id: sensor.out_vs_in
      above: 2
    - platform: numeric_state
      entity_id: sensor.out_vs_in
      below: -2
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: device_tracker.iphones
        state: 'home'
      - condition: numeric_state
        entity_id: 'sensor.netatmo_outdoor_temperature'
        above: '20'
  action:
    - service: notify.ios_iphones_app
      data:
        title: 'Weather'
        message: 'Out vs. In is: {{states.sensor.out_vs_in.state}}°C. Out: {{states.sensor.netatmo_outdoor_temperature.state}}°C / In: {{states.sensor.netatmo_wohnzimmer_temperature.state}}°C'

- alias: 'Weather: Weather Report'
  trigger:
    platform: time
    at: '07:00'
  condition:
    condition: state
    entity_id: device_tracker.iphones
    state: 'home'
  action:
    - service: notify.ios_iphones_app
      data:
        title: 'Weather Report for today'
        message: 'Current: {{states.sensor.netatmo_outdoor_temperature.state}}°C 
        H/L: {{states.sensor.dark_sky_daily_high_temperature.state}}°C/{{states.sensor.dark_sky_daily_low_temperature.state}}°C 
        {{states.sensor.dark_sky_hourly_summary.state}}'    

- alias: 'Weather: Rainy Day'
  trigger:
    - platform: state
      entity_id: sensor.dark_sky_precip
      to: 'rain'
  action:
    - service: notify.ios_iphones_app
      data:
        title: 'Weather Report'
        message: 'It looks like its gonna rain ({{states.sensor.dark_sky_precip_intensity.state}}) soon ({{states.sensor.dark_sky_precip_probability.state}}%). {{states.sensor.sensor.dark_sky_summary.state}}'

