- alias: 'CO2 Bedroom'
  trigger:
    platform: numeric_state
    entity_id: sensor.netatmo_schlafzimmer_co2
    above: 900
  action:
    - service: notify.ios_iphones
      data:
        title: 'Rooms'
        message: 'High CO2 in bedroom Currently: {{states.sensor.netatmo_schlafzimmer_co2.state}}ppm'

- alias: 'CO2 Livingroom'
  trigger:
    platform: numeric_state
    entity_id: sensor.netatmo_wohnzimmer_co2
    above: 900
  action:
    - service: notify.ios_iphones
      data:
        title: 'Rooms'
        message: 'High CO2 in bedroom Currently: {{states.sensor.netatmo_schlafzimmer_co2.state}}ppm'

- alias: 'Noise Livingroom'
  trigger:
    platform: numeric_state
    entity_id: sensor.netatmo_wohnzimmer_noise
    above: 65
  action:
    - service: notify.ios_iphones
      data:
        title: 'Rooms'
        message: 'It is quite noise. Currently: {{states.sensor.netatmo_wohnzimmer_noise.state}}db'


- alias: 'It is warmer outside'
  trigger:
    - platform: numeric_state
      entity_id: sensor.out_vs_in
      above: 0
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: group.personen
        state: 'home'
      - condition: numeric_state
        entity_id: 'sensor.netatmo_outdoor_temperature'
        above: '20'
  action:
    - service: notify.ios_iphones
      data:
        title: 'Weather'
        message: 'Close the door! It is {{states.sensor.out_vs_in.state}}°C warmer outside'

- alias: 'It is colder outside'
  trigger:
    - platform: numeric_state
      entity_id: sensor.out_vs_in
      below: 0
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: group.personen
        state: 'home'
      - condition: numeric_state
        entity_id: 'sensor.netatmo_outdoor_temperature'
        above: '20'
  action:
    - service: notify.ios_iphones
      data:
        title: 'Weather'
        message: 'You should open the door! It is {{states.sensor.out_vs_in.state}}°C colder outside'

- alias: 'Weather Report'
  trigger:
    platform: time
    after: '07:30'
  action:
    - service: notify.ios_iphones
      data:
        title: 'Weather Report for today'
        message: 'Current: {{states.sensor.netatmo_outdoor_temperature.state}}°C 
        H/L: {{states.sensor.dark_sky_daily_high_temperature.state}}°C/{{states.sensor.dark_sky_daily_low_temperature.state}}°C 
        {{states.sensor.dark_sky_hourly_summary.state}}'    

- alias: 'Rainy Day'
  trigger:
    - platform: state
      entity_id: sensor.dark_sky_precip_type
      state: 'rain'
  action:
    - service: notify.ios_iphones
      data:
        title: 'Weather Report'
        message: 'It looks like its gonna rain soon. {{states.sensor.dark_sky_hourly_summary.state}}'

