- alias: 'Update config if travis build is successfull'
  trigger:
    platform: state
    entity_id: sensor.travis_build_label
  condition:
    - condition: state
      entity_id: sensor.travis_status
      state: 'Success'
  action:
    # turn on TV before updating the config, since the broadlink needs to be on during startup
    - service: script.prepare_restart
    - service: script.get_latest_config

