##########################
# Automations 
##########################

- alias: 'Nicole left'
  hide_entity: True
  trigger:
    platform: state
    entity_id: device_tracker.nicolesiphone
    # Optional 
    from: 'home'
    to: 'not_home'
  action:
    - service: notify.telegram
      data:
        message: 'Nicole just left home.'

- alias: 'Nicole arrived'
  hide_entity: True
  trigger:
    platform: state
    entity_id: device_tracker.nicolesiphone
    # Optional 
    from: 'not_home'
    to: 'home'
  action:
    - service: notify.telegram
      data:
        message: 'Nicole arrived at home.'

- alias: 'Water Sanseviera' 
  hide_entity: True
  trigger:
    platform: state
    entity_id: device_tracker.iphones
    from: 'not_home'
    to: 'home'
  condition:
    condition: numeric_state
    entity_id: sensor.sanseviera_moisture
    below: 20
  action:
    - service: notify.telegram
      data:
        message: 'Please water Sanseviera! Moisture: {{states.sensor.sanseviera_moisture.state}}% | Light: {{states.sensor.sanseviera_light_intensity.state}} lux | Conductivity: {{states.sensor.sanseviera_conductivity.state}}'

- alias: 'Water Palm'
  hide_entity: True 
  trigger:
    platform: state
    entity_id: device_tracker.iphones
    from: 'not_home'
    to: 'home'
  condition:
    condition: numeric_state
    entity_id: sensor.palme_moisture
    below: 20
  action:
    - service: notify.telegram
      data:
        message: 'Please water Palm! Moisture: {{states.sensor.palme_moisture.state}}% | Light: {{states.sensor.palme_light_intensity.state}} lux | Conductivity: {{states.sensor.palme_conductivity.state}}'

- alias: 'CO2 Bedroom'
  hide_entity: True
  trigger:
    platform: numeric_state
    entity_id: sensor.netatmo_schlafzimmer_co2
    above: 900
  action:
    - service: notify.telegram
      data:
        message: 'High CO2 in bedroom Currently: {{states.sensor.netatmo_schlafzimmer_co2.state}}ppm'

- alias: 'CO2 Livingroom'
  hide_entity: True
  trigger:
    platform: numeric_state
    entity_id: sensor.netatmo_wohnzimmer_co2
    above: 900
  action:
    - service: notify.telegram
      data:
        message: 'High CO2 in bedroom Currently: {{states.sensor.netatmo_schlafzimmer_co2.state}}ppm'

- alias: 'Noise Livingroom'
  hide_entity: True
  trigger:
    platform: numeric_state
    entity_id: sensor.netatmo_wohnzimmer_noise
    above: 65
  action:
    - service: notify.telegram
      data:
        message: 'It is quite noise. Currently: {{states.sensor.netatmo_wohnzimmer_noise.state}}db'

- alias: 'Update Available Notifications'
  hide_entity: True
  trigger:
    platform: state
    entity_id: updater.updater
  action:
    - service: notify.telegram
      data:
        message: 'Update for Home Assistant is available.'

- alias: 'Power off all'
  hide_entity: True
  trigger:
      platform: time
      after: '03:00'
  action:
    service: switch.turn_off

- alias: 'Nobody at home'
  hide_entity: True
  trigger:
    platform: state
    entity_id: group.personen
    from: 'home'
    to: 'not_home'
    for:
      minutes: 5 
  action:
    - service: notify.telegram
      data:
        message: 'Everybody left. I will switch off all devices.'
    - service: switch.turn_off

- alias: 'Switch on light after sunset'
  trigger:
    platform: state
    entity_id: group.personen
    from: 'not_home'
    to: 'home'
  condition:
    condition: sun
    after: sunset
    after_offset: "-00:30:00"

  action:
    - service: switch.turn_on
      entity_id: switch.light_tv

- alias: 'Lights when someone arrives home'
  trigger:
    - platform: sun
      event: sunset
      #offset: '-00:15:00'
  condition:
    condition: state
    entity_id: group.personen
    state: 'home'
  action:
    - service: switch.turn_on
      entity_id: switch.light_tv

- alias: 'Weather Report'
  trigger:
    platform: time
    after: '07:30'
  action:
    - service: notify.telegram
      data:
        message: 'Weather Report for today: Current: {{states.sensor.netatmo_outdoor_temperature.state}}°C 
        H/L: {{states.sensor.dark_sky_daily_high_temperature.state}}°C/{{states.sensor.dark_sky_daily_low_temperature.state}}°C 
        {{states.sensor.dark_sky_hourly_summary.state}}'

# Vacation Mode 
# Inspired by https://github.com/ronmarco/home-assistant-config/blob/master/yaml_automation/status-vacation.yaml

# Turn vacation mode on automatically
- alias: 'Turn on vacation mode when nobody is home for more than 24 hours'
  trigger:
    - platform: state
      entity_id: group.personen
      from: 'home'
      to: 'not_home'
      for:
        hours: 24
        minutes: 0
        seconds: 0
  action:
    - service: homeassistant.turn_on
      entity_id: input_boolean.vacation_mode
    - service: notify.telegram
      data:
        message: 'I did not see anybody within the last 24 hours. I will switch on the vacation mode'

# Turn vacation mode off automatically
- alias: 'Turn vacation mode off when home'
  trigger:
    - platform: state
      entity_id: group.personen 
      from: 'not_home'
      to: 'home'
  action:
    - service: homeassistant.turn_off
      entity_id: input_boolean.vacation_mode
    - service: notify.telegram
      data:
        message: 'Welcome back! I switched off the vation mode'

# Turn on lights when vacation mode active
- alias: 'Turn on vacation lights at sunset when vacation mode on'
  trigger:
    - platform: state
      entity_id: sun.sun
      from: 'above_horizon'
      to: 'below_horizon'
  condition:
    - condition: state
      entity_id: input_boolean.vacation_mode
      state: 'on'
  action:
    - service: script.vacation_lights

# Turn on light at Sofa if ATV is paused
- alias: 'Turn on light when AppleTV is paused'
  trigger:
    - platform: state
      entity_id: media_player.wohnzimmer
      from: 'playing'
      to: 'paused'
      for:
        seconds: 5
  condition:
    condition: state
    entity_id: sun.sun
    state: below_horizon
  action:
    - service: switch.turn_on
      entity_id: switch.light_sofa

# Turn on light at Sofa if ATV is paused
- alias: 'Turn off light when AppleTV is played'
  trigger:
    - platform: state
      entity_id: media_player.wohnzimmer
      from: 'paused'
      to: 'playing'  
  condition:
    condition: state
    entity_id: sun.sun
    state: below_horizon
  action:
    - service: switch.turn_off
      entity_id: switch.light_sofa

# Turn of devices in the bedroom 30 minutes when switched on after 23:00
- alias: '45 minutes timer for devices at night'
  trigger:
    - platform: state
      entity_id: group.schlafzimmer
      from: 'off'
      to: 'on'
      for:
        minutes: 45
  condition:
    condition: time
    after: '23:00'
    before: '05:00'
  action:
    - service: script.turn_off_bedroom_delay_45
    - service: notify.telegram
      data:
        message: 'I will turn off the devices in the bedroom in 45 minutes'

# Turn off devices in the livingroom 15 minutes when switched on after 3:01
- alias: '15 minutes timer for devices at night'
  trigger:
    - platform: state
      entity_id: group.wohnzimmer
      from: 'off'
      to: 'on'
      for:
        minutes: 15
  condition:
    condition: time
    after: '03:01'
    before: '05:00'
  action:
    - service: script.turn_off_livingroom_delay_15
    - service: notify.telegram
      data:
        message: 'I will turn off the devices in the livingroom in 15 minutes'


# Turn on lights in bedroom, if TV is switched off
- alias: 'Turn on lights in bedroom after TV is switched off'
  trigger:
    - platform: state
      entity_id: switch.tv
      from: 'on'
      to: 'off'
  condition:
    condition: time
    after: '21:00'
    before: '05:00'
  action: 
    - service: switch.turn_on
      entity_id: switch.light_sascha
    - service: switch.turn_on
      entity_id: switch.nicole  

# Turn off lights in livingroom after TV is switched off
- alias: 'Turn off lights in livingroom after TV is switched off'
  trigger:
    - platform: state
      entity_id: switch.tv
      from: 'on'
      to: 'off'
      for:
        minutes: 15
  condition:
    condition: time
    after: '21:00'
    before: '05:00'
  action: 
    - service: script.turn_off_livingroom_delay_15
    - service: notify.telegram
      data:
        message: 'I will turn of the lights in 15 minutes. Good Night.'

- alias: 'watch TV (was HDMI)'
  trigger:
    platform: state
    entity_id: input_select.tv_mode
    to: 'TV'
  condition:
      condition: state
      entity_id: input_select.hdmi_mode
      state: 'HDMI'
  action:
    - service: script.watch_tv
    - service: input_select.select_option
      data:
        entity_id: input_select.hdmi_mode
        option: 'TV'

- alias: 'watch AppleTV (was TV)'
  trigger:
    platform: state
    entity_id: input_select.tv_mode
    to: 'AppleTV'
  condition:
    condition: state
    entity_id: input_select.hdmi_mode
    state: 'AUS'
  action:
    - service: script.turn_tv_on
    - service: scrip.turn_receiver_on
    - service: script.watch_apple_tv
    - service: input_select.select_option
      data:
        entity_id: input_select.hdmi_mode
        option: 'HDMI'

- alias: 'watch AppleTV (was TV)'
  trigger:
    platform: state
    entity_id: input_select.tv_mode
    to: 'AppleTV'
  condition:
    condition: state
    entity_id: input_select.hdmi_mode
    state: 'TV'
  action:
    - service: script.watch_apple_tv
    - service: input_select.select_option
      data:
        entity_id: input_select.hdmi_mode
        option: 'HDMI'
  
- alias: 'watch AppleTV (was FireTV)'
  trigger:
    platform: state
    entity_id: input_select.tv_mode
    to: 'AppleTV'
  condition:
    condition: state
    entity_id: input_select.hdmi_mode
    state: 'HDMI'
  action:
    - service: broadlink.send_packet_192_168_178_51
      data:
        packet:
          - "JgBQAAABKJMUERQ1FBEVEBU1FBEUNRQ2FDUUERU0FDYUERQ1FTUUERQ1FDUUNhQ1FBEVEBURFBEUERQRFBEUERQ1FDYUNRQ1FQAFAgABKEgUAA0FAAAAAAAAAAA="

- alias: 'watch FireTV (was TV)'
  trigger:
    platform: state
    entity_id: input_select.tv_mode
    to: 'FireTV'
  condition:
    condition: state
    entity_id: input_select.hdmi_mode
    state: 'TV'
  action:
    - service: script.watch_fire_tv
    - service: input_select.select_option
      data:
        entity_id: input_select.hdmi_mode
        option: 'HDMI'
  
- alias: 'watch FireTV (was AppleTV)'
  trigger:
    platform: state
    entity_id: input_select.tv_mode
    to: 'FireTV'
  condition:
    condition: state
    entity_id: input_select.hdmi_mode
    state: 'HDMI'
  action:
    - service: broadlink.send_packet_192_168_178_51
      data:
        packet:
          - "JgBQAAABKZIUERU1FBEUERQ1FBEVNRQ1FDUUEhQ1FDUUERU1FDUUERQ2FBEUNRQ1FBIUERQRFBEUERQ1FBEVERQ1FDUUNRU1FAAFAgABKEkUAA0FAAAAAAAAAAA="
   
- alias: 'listen to music (tv is on)'
  trigger:
    platform: state
    entity_id: input_select.tv_mode
    to: 'Music'
  condition:
    condition: or
    conditions:
      - condition: state
        entity_id: input_select.hdmi_mode
        state: 'HDMI'
      - condition: state
        entity_id: input_select.hdmi_mode
        state: 'TV'
  action:
    - service: script.turn_tv_on
    - service: script.listen_to_music
    - service: input_select.select_option
      data:
        entity_id: input_select.hdmi_mode
        option: 'AUS'

- alias: 'listen to music (receiver is off)'
  trigger:
    platform: state
    entity_id: input_select.tv_mode
    to: 'Music'
  condition:
    condition: state
    entity_id: input_select.hdmi_mode
    state: 'AUS'
  action:
    - service: script.turn_receiver_on
    - service: script.listen_to_music

- alias: 'turn off tv'
  trigger:
    platform: state
    entity_id: input_select.tv_mode
    to: 'AUS'
  action:
    - service: script.turn_tv_on
    - service: scrip.turn_receiver_on
    - service: input_select.select_option
      data:
        entity_id: input_select.hdmi_mode
        option: 'AUS'


