##########################
# Binary Sensors
##########################

# Monitor system uptime
- platform: ping
  name: PING Eltern
  host: home.cbs-service.net

- platform: ping
  name: PING Sonja
  host: bmw.cbs-service.net

- platform: ping
  name: PING Polanetzki
  host: buero.pblaw.de

- platform: ping
  name: PING Dreieich
  host: dreieich.cbs-service.net

- platform: ping
  name: PING Schwarzwald
  host: heesen.cbs-service.net

- platform: ping
  name: PING Gote
  host: gote.cbs-service.net

- platform: ping
  name: PING Sebastian
  host: seb.cbs-service.net

- platform: ping
  name: PING Uwe
  host: uwe.cbs-service.net

- platform: ping
  name: PING VHV
  host: vhv.cbs-service.net

- platform: ping
  name: PING WSW
  host: 192.168.2.1


- platform: 'bayesian'
  prior: 0.5
  name: 'Sascha Home'
  probability_threshold: 0.95
  observations:
    - entity_id: 'device_tracker.iphones'
      prob_given_true: 0.9
      prob_given_false: 0.2
      platform: 'state'
      to_state: 'home'
    - entity_id: 'device_tracker.owntracks_iphones'
      prob_given_true: 0.7
      prob_given_false: 0.4
      platform: 'state'
      to_state: 'home'