- platform: group
  name: Office
  entities:
    - cover.office_left
    - cover.office_right

- platform: group
  name: Livingroom
  entities:
    - cover.livingroom_coach_left
    - cover.livingroom_coach_right
    - cover.livingroom_door
    - cover.livingroom_small

- platform: group
  name: Livingroom_front
  entities:
    - cover.livingroom_door
    - cover.livingroom_coach_left

- platform: group
  name: Front
  entities:
    - cover.livingroom_door
    - cover.livingroom_coach_left
    - cover.office
    - cover.child

- platform: group
  name: Livingroom_right
  entities:
    - cover.livingroom_coach_right
    - cover.livingroom_small

- platform: group
  name: All
  entities:
    - cover.livingroom
    - cover.office
    - cover.child
    - cover.kitchen

- platform: group
  name: Side
  entities:
    - cover.livingroom_right
    - cover.kitchen

- platform: group
  name: Livingroom_tv
  entities:
    - cover.livingroom_coach_right
