##########################
# Groups
##########################
living_room:
  name: 'Living Room'
  entities:
    - sensor.netatmo_wohnzimmer_temperature
    - sensor.netatmo_wohnzimmer_co2
    - sensor.netatmo_wohnzimmer_humidity
    - sensor.netatmo_wohnzimmer_pressure
    - sensor.netatmo_wohnzimmer_noise
    - light.fernseher
    - light.sofa
    - light.sessel
    - binary_sensor.door_window_sensor_158d0001b7700c
bed_room:
  name: 'Bedroom'
  entities:
    - sensor.netatmo_schlafzimmer_temperature
    - sensor.netatmo_schlafzimmer_co2
    - sensor.netatmo_schlafzimmer_humidity
    - light.bed2
    - light.bed1
    - switch.tv_2
    - switch.ventilator
outdoor:
  name: 'Outdoor'
  entities:
    - binary_sensor.door_window_sensor_158d0001d8253a
    - sensor.netatmo_outdoor_temperature
    - sensor.dark_sky_daily_high_temperature
    - sensor.dark_sky_daily_low_temperature
    - sensor.dark_sky_summary
    - sun.sun
    - sensor.netatmo_outdoor_humidity
    - sensor.dark_sky_wind_speed
    - sensor.dark_sky_precip
    - sensor.dark_sky_precip_intensity
    - sensor.dark_sky_precip_probability
office:
  name: 'Office'
  entities:
    - switch.server
    - sensor.palmek_temperature
plant_1:
  name: 'Sanseviera'
  entities:  
    - sensor.sanseviera_moisture
    - sensor.sanseviera_light_intensity
    - sensor.sanseviera_temperature
    - sensor.sanseviera_conductivity
    - sensor.sanseviera_battery
plant_2:
  name: 'Palm'
  entities:  
    - sensor.palme_moisture
    - sensor.palme_light_intensity
    - sensor.palme_temperature
    - sensor.palme_conductivity
    - sensor.palme_battery
plant_3:
  name: 'Bath'
  entities:  
    - sensor.bad_moisture
    - sensor.bad_light_intensity
    - sensor.bad_temperature
    - sensor.bad_conductivity
    - sensor.bad_battery
plant_4:
  name: 'Small Palm'
  entities:  
    - sensor.palmek_moisture
    - sensor.palmek_light_intensity
    - sensor.palmek_temperature
    - sensor.palmek_conductivity
    - sensor.palmek_battery
pi:
  name: 'Raspberry'
  entities:
    - sensor.cpu_temperature
    - sensor.cpu_use
    - sensor.disk_used_
    - sensor.last_boot
    - sensor.ram_free
    - sensor.sent_eth0
    - sensor.received_eth0
    - sensor.speedtest_download
    - sensor.speedtest_upload
personen:
  name: 'People'
  entities:
    - group.user_1
    - group.user_2
user_1:
  name: !secret user_1
  entities:
    - device_tracker.iphones
    - device_tracker.owntracks_iphones
user_2:
  name: !secret user_2
  entities:
    - device_tracker.user_2_iphone
    - device_tracker.owntracks_user_2_iphone
tv_scenes:
  name: 'TV'
  entities:
    - switch.tv_mode
    - switch.appletv_mode
    - switch.plex_mode
    - switch.music_mode
    - switch.tv
iphone:
  name: 'Devices'
  entities:
    - sensor.iphones_battery_level
    - sensor.iphones_battery_state
    - sensor.ipads_battery_level
    - sensor.ipads_battery_state
pings:
  name: 'Ping'
  entities:
    - binary_sensor.ping_eltern
    - binary_sensor.ping_sonja
    - binary_sensor.ping_gote
    - binary_sensor.ping_dreieich
    - binary_sensor.ping_schwarzwald
    - binary_sensor.ping_polanetzki
    - binary_sensor.ping_sebastian
    - binary_sensor.ping_uwe
    - binary_sensor.ping_vhv
    - binary_sensor.ping_wsw
settings:
  name: 'Settings'
  entities:
    - script.get_latest_config
    - script.restart_hass
    - script.restart_homebridge
    - input_select.log_level
    - input_select.tv_mode
    - input_boolean.vacation_mode
    - input_boolean.cleaned_today
    - sensor.ha_current_version
devices:
  name: 'Devices'
  entities:
    - switch.tv
    - switch.speaker_1
    - switch.socket_1
    - sensor.fritz_netmonitor
    - sensor.robo
    - sensor.epson
    - sensor.tradfri
    - sensor.plex
    - sensor.appletv_livingroom
    - sensor.appletv_bedroom
    - sensor.broadlink
    - sensor.switch
    - sensor.server
    - sensor.aqara_gateway
battery_levels:
  name: 'Battery Levels'
  entities:
    - sensor.eingang
    - sensor.bad
    - sensor.kueche
    - sensor.netatmo_schlafzimmer_battery
    - sensor.netatmo_outdoor_battery
    - sensor.door1_battery
    - sensor.door2_battery
    - sensor.motion1_battery
    - sensor.motion2_battery
    - sensor.cube_battery
    - sensor.switch1_battery
robot:
  name: 'Vacuum Cleaner'
  entities:
    - vacuum.vacuum_cleaner
    - input_boolean.cleaned_today
speaker:
  name: 'Music'
  entities:
    - input_select.sonos_source
    - switch.sonos_mode
    - input_number.sonos_speaker   
printer:
  name: 'Epson Printer'
  entities:
    - sensor.epson
    - sensor.epson_ink_level_black
    - sensor.epson_ink_level_magenta
    - sensor.epson_ink_level_yellow
    - sensor.epson_ink_level_cyan    
all_speaker:
  entities:
    - switch.speaker_1
    - switch.socket_1
doors:
  name: 'Doors'
  entities:
    - binary_sensor.door_window_sensor_158d0001b7700c
lights_livingroom:
  name: 'Lights Living Room'
  entities:
    - light.fernseher
    - light.sofa
    - light.sessel
docker_container:
  name: 'Docker Container'
  control: hidden
  entities:
    - switch.homebridge
    - switch.influxdb
    - switch.grafana
    - switch.mosquitto
    - switch.resilio
    - switch.dnsmasq
    - switch.portainer

not_necessary_devices:
  name: 'Not necessary'
  entities:
    - switch.light_baum
    - switch.light_sterne
    - switch.server
    - switch.socket_1
    - switch.speaker_1
    - switch.tv
    - switch.tv_2
    - switch.ventilator

lights_bedroom:
  name: 'Lights Bedroom'
  entities:
    - light.bed2
    - light.bed1

# Tabs
default_view:
  name: 'Home'
  view: yes
  icon: mdi:home
  entities:
    - group.living_room
    - group.bed_room
    - group.office
    - group.outdoor
    - group.states
    - group.robot
    - group.personen
media:
  name: 'Media'
  view: yes
  icon: mdi:television 
  entities:
    - group.tv_scenes
    - media_player.wohnzimmer
    - media_player.schlafzimmer
    - group.speaker
    - media_player.living_room    
plants:
  name: 'Plants'
  view: yes
  icon: mdi:barley
  entities:
    - group.plant_1
    - group.plant_2  
    - group.plant_3
    - group.plant_4
system:
  name: 'System'
  view: yes
  icon: mdi:server
  entities:
    - group.pi
    - group.devices
    - group.pings
    - group.docker_container
automation:
  name: 'Automation'
  view: yes
  icon: mdi:settings
  entities:
    - group.settings
    - group.all_automations
    - group.all_scripts
christmas:
  name: 'Christmas'
  view: no
  icon: mdi:pine-tree
  entities:
    - switch.light_baum
    - switch.light_sterne
device_status:
  name: 'Device Status'
  view: yes
  icon: mdi:oil-temperature
  entities:
    - group.printer
    - group.battery_levels