##########################
# Groups
##########################



wohnzimmer:
  name: Wohnzimmer
  entities:
    - sensor.netatmo_wohnzimmer_temperature
    - sensor.netatmo_wohnzimmer_co2
    - sensor.netatmo_wohnzimmer_humidity
    - sensor.netatmo_wohnzimmer_pressure
    - sensor.netatmo_wohnzimmer_noise
    - switch.light_sessel
    - light.lampe_fernseher
    - light.lampe_sofa
    - switch.tv
    - input_select.tv_mode
    - media_player.wohnzimmer
    - device_tracker.broadlink
schlafzimmer:
  name: Schlafzimmer
  entities:
    - sensor.netatmo_schlafzimmer_temperature
    - sensor.netatmo_schlafzimmer_co2
    - sensor.netatmo_schlafzimmer_humidity
    - switch.light_sascha
    - switch.light_nicole
    - switch.tv_2
outdoor:
  name: Außen
  entities:
    - sensor.dark_sky_summary
    - sun.sun
    - sensor.netatmo_outdoor_temperature
    - sensor.dark_sky_temperature
    - sensor.dark_sky_daily_high_temperature
    - sensor.dark_sky_daily_low_temperature
    - sensor.netatmo_outdoor_humidity
    - sensor.dark_sky_humidity
    - sensor.dark_sky_wind_speed
    - sensor.dark_sky_hourly_summary
gang:
  name: Gang
  entities:
    - light.lampe_gang_bad
arbeitszimmer:
  name: Arbeitszimmer
  entities:
    - group.pi
    - switch.server
    - sensor.palme_temperature
plant_wohnzimmer:
  name: Sanseviera
  entities:  
    - sensor.sanseviera_moisture
    - sensor.sanseviera_light_intensity
    - sensor.sanseviera_temperature
    - sensor.sanseviera_conductivity
    - sensor.sanseviera_battery
plant_palme:
  name: Palme
  entities:  
    - sensor.palme_moisture
    - sensor.palme_light_intensity
    - sensor.palme_temperature
    - sensor.palme_conductivity
    - sensor.palme_battery
pi:
  name: Raspberry
  entities:
    - sensor.cpu_temperature
    - sensor.cpu_use
    - sensor.disk_use_
    - sensor.last_boot
    - sensor.ram_free
    - sensor.sent_eth0
    - sensor.received_eth0
    - sensor.fastcom_download
personen:
  name: Personen
  entities:
    - device_tracker.iphones
    - device_tracker.nicolesiphone
automation_group:
  name: Automations
  entities:
    - automation.co2_bedroom
    - automation.co2_livingroom
    - automation.lights_in_the_dark
    - automation.lights_when_i_am_home
    - automation.nicole_arrived
    - automation.nicole_left
    - automation.nobody_at_home
    - automation.noise_livingroom
    - automation.power_off_all
    - automation.update_available_notifications
    - automation.water_palm
    - automation.water_sanseviera
    - automation.weather_report
    - automation.turn_on_vacation_lights_at_sunset_when_vacation_mode_on
    - automation.turn_on_vacation_mode_when_nobody_is_home_for_more_than_24_hours
    - automation.turn_vacation_mode_off_when_home
    - automation.15_minutes_timer_for_devices_at_night
    - automation.45_minutes_timer_for_devices_at_night
    - automation.switch_on_light_after_sunset
    - automation.turn_off_light_when_appletv_is_played
    - automation.turn_on_light_when_appletv_is_paused
    - automation.turn_off_lights_in_livingroom_after_tv_is_switched_off
    - automation.turn_on_lights_in_bedroom_after_tv_is_switched_off
states:
  name: States
  entities:
    - input_boolean.vacation_mode
scripts:
  name: Skripte
  entities:
    - script.reload_automations
    - script.restart_ha
    - script.reboot_pi
    - script.get_latest_config
    - script.vacation_lights
    - script.restart_music
    - script.turn_off_bedroom_delay_45
    - script.turn_off_livingroom_delay_15
    - script.turn_tv_on
    - script.turn_receiver_on
    - script.listen_to_music
    - script.watch_tv
    - script.watch_apple_tv
    - script.watch_fire_tv
tv_scenes:
  name: TV
  entities:
    - scene.tv
    - scene.apple_tv
    - scene.firetv
    - scene.musik
iphone:
  name: iPhone
  entities:
    - sensor.iphones_battery_level
    - sensor.iphones_battery_state
pings:
  name: Ping
  entities:
    - binary_sensor.ping_eltern
    - binary_sensor.ping_sonja
    - binary_sensor.ping_gote
    - binary_sensor.ping_dreieich
    - binary_sensor.ping_schwarzwald
    - binary_sensor.ping_polanetzki
    - binary_sensor.ping_sebastian
    - binary_sensor.ping_uwe
    - binary_sensor.ping_vhv

# Tabs
default_view:

rooms:
  name: Räume
  view: yes
  icon: mdi:home
  entities:
    - group.outdoor
    - group.wohnzimmer
    - group.schlafzimmer
    - group.arbeitszimmer
    - group.states
plants:
  name: Pflanzen
  view: yes
  icon: mdi:barley
  entities:
    - group.plant_wohnzimmer
    - group.plant_palme  
automation:
  name: Automation
  view: yes
  icon: mdi:settings
  entities:
    - group.state
    - group.automation_group
    - group.scripts
scenes: 
  name: Szenen
  view: yes
  icon: mdi:lightbulb-on
  entities:
    - scene.alles_aus
    - scene.lampen_bett
    - scene.lampen_wohnzimmer
    - group.tv_scenes
home:
  name: Home
  view: yes
  icon: mdi:account
  entities:
    - group.personen
    - group.iphone
system:
  name: System
  view: yes
  icon: mdi:server
  entities:
    - group.pi
    - group.pings