##########################
# Groups
##########################
living_room:
  name: 'Living Room'
  entities:
    - light.living_room_lights
    - switch.appletv_mode
    - switch.sonos_mode
bed_room:
  name: 'Bedroom'
  entities:
    - light.bedroom_lights
    - switch.tv_2
    - switch.fan
outdoor:
  name: 'Outdoor'
  entities:
    - sensor.dark_sky_daily_high_temperature
    - sensor.dark_sky_daily_low_temperature
    - sensor.dark_sky_summary
    - sun.sun
    - sensor.dark_outside
    - sensor.dark_sky_wind_speed
    - sensor.dark_sky_precip
    - sensor.dark_sky_precip_intensity
    - sensor.dark_sky_precip_probability
office:
  name: 'Office'
  entities:
    - switch.server
    - sensor.illumination_158d0001ff3f0a
pi:
  name: 'Raspberry'
  entities:
    - sensor.cpu_temperature
    - sensor.cpu_use
    - sensor.disk_used_
    - sensor.last_boot
    - sensor.ram_free
    - sensor.sent_eth0
    - sensor.received_eth0
    - sensor.speedtest_download
    - sensor.speedtest_upload
personen:
  name: 'People'
  entities:
    - group.user_1
    - group.user_2
user_1:
  name: !secret user_1
  entities:
    - device_tracker.iphones
    - device_tracker.owntracks_iphones
user_2:
  name: !secret user_2
  entities:
    - device_tracker.user_2_iphone
    - device_tracker.owntracks_user_2_iphone
tv_scenes:
  name: 'TV'
  entities:
    - switch.tv_mode
    - switch.appletv_mode
    - switch.plex_mode
    - switch.music_mode
    - switch.tv
iphone:
  name: 'Devices'
  entities:
    - sensor.iphones_battery_level
    - sensor.iphones_battery_state
    - sensor.ipads_battery_level
    - sensor.ipads_battery_state
pings:
  name: 'Ping'
  entities:
    - binary_sensor.ping_eltern
    - binary_sensor.ping_sonja
    - binary_sensor.ping_gote
    - binary_sensor.ping_dreieich
    - binary_sensor.ping_schwarzwald
    - binary_sensor.ping_polanetzki
    - binary_sensor.ping_sebastian
    - binary_sensor.ping_uwe
    - binary_sensor.ping_vhv
    - binary_sensor.ping_wsw
    - binary_sensor.ping_anny
settings:
  name: 'Settings'
  entities:
    - script.get_latest_config
    - script.restart_hass
    - input_select.log_level
    - input_select.tv_mode
    - input_boolean.vacation_mode
    - input_boolean.cleaned_today
devices:
  name: 'Devices'
  entities:
    - switch.tv
    - switch.speaker_1
    - switch.speaker_2
    - sensor.fritz_netmonitor
    - sensor.robo
    - sensor.epson
    - sensor.tradfri
    - sensor.plex
    - sensor.appletv_livingroom
    - sensor.appletv_bedroom
    - sensor.broadlink
    - sensor.switch
    - sensor.server
    - sensor.aqara_gateway
    - sensor.sonoff_tv
    - sensor.sonoff_tv_2 
    - sensor.sonoff_speaker_1
    - sensor.sonoff_speaker_2
battery_levels:
  name: 'Battery Levels'
  entities:
    - sensor.eingang
    - sensor.bad
    - sensor.kueche
    - sensor.door1_battery
    - sensor.door2_battery
    - sensor.motion1_battery
    - sensor.motion2_battery
    - sensor.cube_battery
    - sensor.switch1_battery
robot:
  name: 'Vacuum Cleaner'
  entities:
    - vacuum.vacuum_cleaner
    - input_boolean.cleaned_today
speaker:
  name: 'Music'
  entities:
    - input_select.sonos_source
    - switch.sonos_mode
    - input_number.sonos_speaker   
printer:
  name: 'Epson Printer'
  entities:
    - sensor.epson
    - sensor.epson_ink_level_black
    - sensor.epson_ink_level_magenta
    - sensor.epson_ink_level_yellow
    - sensor.epson_ink_level_cyan   
prices:
  name: 'Prices'
  entities:
    - sensor.mein_schiff_price 
all_speaker:
  entities:
    - switch.speaker_1
    - switch.speaker_2
balcony_doors:
  name: 'balcony_doors'
  entities:
    - binary_sensor.door_window_sensor_158d0001b7700c
doors:
  name: 'Doors'
  entities:
    - binary_sensor.door_window_sensor_158d0001b7700c
    - binary_sensor.door_window_sensor_158d0001d8253a
docker_container:
  name: 'Docker Container'
  control: hidden
  entities:
    - switch.influxdb
    - switch.grafana
    - switch.mosquitto
    - switch.resilio
    - switch.portainer
    - switch.pihole
not_necessary_devices:
  name: 'Not necessary'
  entities:
    - switch.light_baum
    - switch.light_sterne
    - switch.server
    - switch.speaker_2
    - switch.speaker_1
    - switch.tv
    - switch.tv_2
    - switch.fan
temperature:
  name: 'Temperature'
  entities:
    - sensor.dark_sky_temperature
    - sensor.temperature_158d00022b6674
    - sensor.temperature_158d00022c9982
    - sensor.temperature_158d00022cb37f
    - sensor.temperature_158d00022cb65c
humidity:
  name: 'Humidity'
  entities:
    - sensor.dark_sky_humidity
    - sensor.humidity_158d00022b6674
    - sensor.humidity_158d00022c9982
    - sensor.humidity_158d00022cb37f
    - sensor.humidity_158d00022cb65c
pressure:
  name: 'Pressure'
  entities:
    - sensor.pressure_158d00022b6674
    - sensor.pressure_158d00022c9982
    - sensor.pressure_158d00022cb37f
    - sensor.pressure_158d00022cb65c

# Tabs
default_view:
  name: 'Home'
  view: yes
  icon: mdi:home
  entities:
    - group.living_room
    - group.bed_room
    - group.office
    - group.temperature
    - group.doors
    - group.states
    - group.robot
    - group.personen
    - group.humidity
media:
  name: 'Media'
  view: yes
  icon: mdi:television 
  entities:
    - group.tv_scenes
    - media_player.wohnzimmer
    - media_player.schlafzimmer
    - group.speaker
    - media_player.living_room    
plants:
  name: 'Plants'
  view: yes
  icon: mdi:barley
  entities:
    - plant.bonsai
    - plant.bad
    - plant.palm
    - plant.palm_small
system:
  name: 'System'
  view: yes
  icon: mdi:server
  entities:
    - group.pi
    - group.devices
    - group.pings
    - group.docker_container
automation:
  name: 'Automation'
  view: yes
  icon: mdi:settings
  entities:
    - group.settings
    - group.all_automations
    - group.all_scripts
christmas:
  name: 'Christmas'
  view: no
  icon: mdi:pine-tree
  entities:
    - switch.light_baum
    - switch.light_sterne
device_status:
  name: 'Device Status'
  view: yes
  icon: mdi:oil-temperature
  entities:
    - group.printer
    - group.prices
    - group.battery_levels
    - group.outdoor