##########################
# Groups
##########################
wohnzimmer:
  name: Wohnzimmer
  entities:
    - light.lampe_fernseher
    - light.lampe_sofa
    - switch.light_sessel
    - sensor.netatmo_wohnzimmer_temperature
    - sensor.netatmo_wohnzimmer_co2
    - sensor.netatmo_wohnzimmer_humidity
    - sensor.netatmo_wohnzimmer_pressure
    - sensor.netatmo_wohnzimmer_noise

    #- device_tracker.broadlink
wohnzimmer_lampen:
  name: Wohnzimmer Lampen
  entities:
    - light.lampe_fernseher
    - light.lampe_sofa
schlafzimmer:
  name: Schlafzimmer
  entities:
    - switch.light_sascha
    - switch.light_nicole
    - switch.tv_2
    - switch.ventilator
    - sensor.netatmo_schlafzimmer_temperature
    - sensor.netatmo_schlafzimmer_co2
    - sensor.netatmo_schlafzimmer_humidity
outdoor:
  name: Außen
  entities:
    - sensor.dark_sky_summary
    - sun.sun
    - sensor.netatmo_outdoor_temperature
    #- sensor.dark_sky_temperature
    - sensor.dark_sky_daily_high_temperature
    - sensor.dark_sky_daily_low_temperature
    - sensor.netatmo_outdoor_humidity
    #- sensor.dark_sky_humidity
    - sensor.dark_sky_wind_speed
    #- sensor.dark_sky_hourly_summary
    - sensor.dark_sky_precip_intensity
gang:
  name: Gang
  entities:
    - light.lampe_gang_bad
arbeitszimmer:
  name: Arbeitszimmer
  entities:
    - switch.server
    - sensor.palme_temperature
plant_wohnzimmer:
  name: Sanseviera
  entities:  
    - sensor.sanseviera_moisture
    - sensor.sanseviera_light_intensity
    - sensor.sanseviera_temperature
    - sensor.sanseviera_conductivity
    - sensor.sanseviera_battery
plant_palme:
  name: Palme
  entities:  
    - sensor.palme_moisture
    - sensor.palme_light_intensity
    - sensor.palme_temperature
    - sensor.palme_conductivity
    - sensor.palme_battery
plant_bad:
  name: Bad
  entities:  
    - sensor.bad_moisture
    - sensor.bad_light_intensity
    - sensor.bad_temperature
    - sensor.bad_conductivity
    - sensor.bad_battery
plant_palmek:
  name: Palmek
  entities:  
    - sensor.palmek_moisture
    - sensor.palmek_light_intensity
    - sensor.palmek_temperature
    - sensor.palmek_conductivity
    - sensor.palmek_battery
pi:
  name: Raspberry
  entities:
    - sensor.cpu_temperature
    - sensor.cpu_use
    - sensor.disk_use_
    - sensor.last_boot
    - sensor.ram_free
    - sensor.sent_eth0
    - sensor.received_eth0
    - sensor.fastcom_download
personen:
  name: Personen
  entities:
    - device_tracker.iphones
    - device_tracker.nicolesiphone
tv_scenes:
  name: TV
  entities:
    - switch.tv_mode
    - switch.appletv_mode
    - switch.plex_mode
    - switch.fire_tv_mode
    - switch.music_mode
iphone:
  name: Devices
  entities:
    - sensor.iphones_battery_level
    - sensor.iphones_battery_state
    - sensor.ipads_battery_level
    - sensor.ipads_battery_state
pings:
  name: Ping
  entities:
    - binary_sensor.ping_eltern
    - binary_sensor.ping_sonja
    - binary_sensor.ping_gote
    - binary_sensor.ping_dreieich
    - binary_sensor.ping_schwarzwald
    - binary_sensor.ping_polanetzki
    - binary_sensor.ping_sebastian
    - binary_sensor.ping_uwe
    - binary_sensor.ping_vhv
stocks:
  name: Stock
  entities:
    - sensor.amzn
    - sensor.aapl
    - sensor.stag
settings:
  name: Settings
  entities:
    - input_select.log_level
    - input_select.tv_mode
    - input_boolean.vacation_mode
devices:
  name: Devices
  entities:
    - sensor.robo

# Tabs
default_view:
  #name: Räume
  view: yes
  icon: mdi:home
  entities:
    - group.outdoor
    - group.wohnzimmer
    - group.schlafzimmer
    - group.arbeitszimmer
    - group.states
media:
  name: Media
  view: yes
  icon: mdi:television 
  entities:
    - group.tv_scenes
    - media_player.appletv
    - input_slider.appletv_delay
home:
  name: Home
  view: yes
  icon: mdi:account
  entities:
    - group.personen
    - group.iphone
plants:
  name: Pflanzen
  view: yes
  icon: mdi:barley
  entities:
    - group.plant_wohnzimmer
    - group.plant_palme  
    - group.plant_bad
    - group.plant_palmek
system:
  name: System
  view: yes
  icon: mdi:server
  entities:
    - group.pi
    - group.devices
    - group.pings
automation:
  name: Automation
  view: yes
  icon: mdi:settings
  entities:
    - group.all_automations
    - group.all_scripts
    - scene.alles_aus
    - scene.lampen_bett
    - scene.lampen_wohnzimmer
    - group.settings
finance:
  name: Finance
  view: yes
  icon: mdi:trending-up
  entities:
    - group.stocks