- platform: group
  name: Living Room Lights
  entities:
    - light.fernseher
    - light.sofa
    - light.sessel
- platform: group
  name: Bedroom Lights
  entities:
    - light.bed2
    - light.bed1
- platform: group
  name: Kitchen Lights
  entities:
    - light.kueche1
    - light.kueche2

- platform: mqtt
  name: "Christmas Tree"
  state_topic: "tele/sonoff/living_room/tree/STATE"
  value_template: "{{ value_json.POWER }}"
  command_topic: "cmnd/sonoff/living_room/tree/POWER"
  availability_topic: "tele/sonoff/living_room/tree/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: false

- platform: mqtt
  name: "Stars"
  state_topic: "tele/sonoff/living_room/stars/STATE"
  value_template: "{{ value_json.POWER }}"
  command_topic: "cmnd/sonoff/living_room/stars/POWER"
  availability_topic: "tele/sonoff/living_room/stars/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: false