- platform: mqtt
  name: "stairs"
  state_topic: "shellies/shelly1-98F4ABD0B809/relay/0"
  command_topic: "shellies/shelly1-98F4ABD0B809/relay/0/command"
  payload_on: "on"
  payload_off: "off"
  optimistic: false
  qos: 0
  retain: true

- platform: group
  name: Gang
  entities:
    - light.front_gang
    - light.front_gang_2

- platform: group
  name: Kitchen
  entities:
    - light.kitchen_1
    - light.kitchen_2
    - light.kitchen_3
    - light.kitchen_4
    - light.kitchen_5

- platform: group
  name: bedroom
  entities:
    - light.bed_1
    - light.bed_2
