##########################
# Sensors
##########################

# Weather Prediction
- platform: darksky
  api_key: !secret dark_sky_api_password
  monitored_conditions:
    - summary
    - temperature
    - wind_speed
    - humidity
    - temperature_min
    - temperature_max
    - hourly_summary
    - precip_type
    - precip_intensity
    - precip_probability
    - cloud_cover

- platform: speedtest
  minute: 30
  hour:
    - 0
    - 6
    - 12
    - 18
  monitored_conditions:
    - download
    - upload

- platform: fritzbox_netmonitor
  host: !secret fritz_host

- platform: travisci
  api_key: !secret github_token

- platform: command_line
  name: CPU Temperature
  command: 'cat /sys/class/thermal/thermal_zone0/temp'
  unit_of_measurement: '°C'
  value_template: '{{ (value | multiply(0.001)) | round(1) }}'

- platform: systemmonitor
  resources:
  - type: disk_use_percent
    arg: /
  - type: memory_free
  - type: processor_use
  - type: network_in
    arg: eth0
  - type: network_out
    arg: eth0
  - type: last_boot

# Plant sensors
- platform: miflora
  mac: C4:7C:8D:62:B7:02
  name: Sanseviera 
  force_update: false
  median: 3
  monitored_conditions:
    - moisture
    - light
    - temperature
    - conductivity
    - battery

- platform: miflora
  mac: C4:7C:8D:62:B7:30
  name: Bad
  force_update: false
  median: 3
  monitored_conditions:
    - moisture
    - light
    - temperature
    - conductivity
    - battery

- platform: miflora
  mac: C4:7C:8D:62:B8:85
  name: Palme
  force_update: false
  median: 3
  monitored_conditions:
    - moisture
    - light
    - temperature
    - conductivity
    - battery

- platform: miflora
  mac: C4:7C:8D:62:C1:9C
  name: Palmek
  force_update: false
  median: 3
  monitored_conditions:
    - moisture
    - light
    - temperature
    - conductivity
    - battery

# - platform: yahoo_finance
#   symbols:
#     - AMZN
#     - AAPL
#     - STAG

# Inspired by https://community.home-assistant.io/t/temp-compare/19497
- platform: template
  sensors:
    out_vs_in:
      value_template: "{{states.sensor.netatmo_outdoor_temperature.state | round(0) - states.sensor.netatmo_wohnzimmer_temperature.state | round(0)}}"
      friendly_name: "Temperature Diff"

# Inspired by https://community.home-assistant.io/t/0-46-1-not-available-via-upgrade/19539
- platform: rest
  resource: https://pypi.python.org/pypi/homeassistant/json
  name: HA Current Version
  value_template: '{{ value_json.info.version }}'
  scan_interval: 3600

# Inspired by https://github.com/CCOSTAN/Home-AssistantConfig/blob/9b088e5bee97d242463b7d794edeb4a1d967bac1/sensor/devices_states.yaml
- platform: template
  sensors: 
      # Inspired by https://github.com/rytilahti/python-mirobo/issues/4   
      vacuum_status:   
       value_template: '{{ states.vacuum.staubsauger.attributes.status}}'    
       friendly_name: 'Status'   
       icon_template: mdi:comment

      door1_battery:   
       value_template: '{{ states.binary_sensor.door_window_sensor_158d0001d8253a.attributes.battery_level}}'    
       friendly_name: 'Status'   
       icon_template: mdi:battery-80

      motion1_battery:   
       value_template: '{{ states.binary_sensor.motion_sensor_158d0001a90475.attributes.battery_level}}'    
       friendly_name: 'Status'   
       icon_template: mdi:battery-80

      switch1_battery:   
       value_template: '{{ states.binary_sensor.switch_158d0001d8795f.attributes.battery_level}}'    
       friendly_name: 'Status'   
       icon_template: mdi:battery-80
      
      sascha_home:
        value_template:
          "{% if is_state('binary_sensor.sascha_home', 'on') %}
          home
          {% else %}
          not_home
          {% endif %}"
        friendly_name: Sascha

      robo:
        friendly_name: 'Robo'
        value_template: "{{ 'online' if is_state('device_tracker.pc286c07f695b2', 'home') else 'off' }}"

      epson:
        friendly_name: 'Epson'
        value_template: "{{ 'online' if is_state('device_tracker.epson029ea9', 'home') else 'off' }}"

      broadlink:
        friendly_name: 'Broadlink'
        value_template: "{{ 'online' if is_state('device_tracker.broadlink', 'home') else 'off' }}"

      plex:
        friendly_name: 'Plex'
        value_template: "{{ 'online' if is_state('device_tracker.plex', 'home') else 'off' }}"

      switch:
        friendly_name: 'Switch'
        value_template: "{{ 'online' if is_state('device_tracker.switch', 'home') else 'off' }}"

      tradfri:
        friendly_name: 'Tradfri Gateway'
        value_template: "{{ 'online' if is_state('device_tracker.tradfri', 'home') else 'off' }}"

      appletv_bedroom:
        friendly_name: 'AppleTV Bedroom'
        value_template: "{{ 'online' if is_state('device_tracker.schlafzimmer', 'home') else 'off' }}"

      appletv_livingroom:
        friendly_name: 'AppleTV Livingroom'
        value_template: "{{ 'online' if is_state('device_tracker.wohnzimmer', 'home') else 'off' }}"

      netatmo:
        friendly_name: 'Netatmo'
        value_template: "{{ 'online' if is_state('device_tracker.netatmo', 'home') else 'off' }}"

      server:
        friendly_name: 'Server'
        value_template: "{{ 'online' if is_state('device_tracker.server', 'home') else 'off' }}"

      sonos:
        friendly_name: 'Sonos 1'
        value_template: "{{ 'online' if is_state('device_tracker.batplay1', 'home') else 'off' }}"

      sonos2:
        friendly_name: 'Sonos 2'
        value_template: "{{ 'online' if is_state('device_tracker.batplay2', 'home') else 'off' }}"

      aqara_gateway:
        friendly_name: 'Aqara Gateway'
        value_template: "{{ 'online' if is_state('device_tracker.aqara_gateway', 'home') else 'off' }}"

- platform: command_line
  name: Epson Ink Level Black
  command: /usr/bin/curl -X GET http://epson.cbs-service.net/PRESENTATION/HTML/TOP/PRTINFO.HTML  | awk -F"'" '/Ink_K.PNG/ && $6+0 == $6 { printf "%.0f\n", $6 / 50 * 100 }'
  unit_of_measurement: '%'
  scan_interval: 60

- platform: command_line
  name: Epson Ink Level Magenta
  command: /usr/bin/curl -X GET http://epson.cbs-service.net/PRESENTATION/HTML/TOP/PRTINFO.HTML  | awk -F"'" '/Ink_M.PNG/ && $6+0 == $6 { printf "%.0f\n", $6 / 50 * 100 }'
  unit_of_measurement: '%'
  scan_interval: 60

- platform: command_line
  name: Epson Ink Level Yellow
  command: /usr/bin/curl -X GET http://epson.cbs-service.net/PRESENTATION/HTML/TOP/PRTINFO.HTML  | awk -F"'" '/Ink_Y.PNG/ && $6+0 == $6 { printf "%.0f\n", $6 / 50 * 100 }'
  unit_of_measurement: '%'
  scan_interval: 60

- platform: command_line
  name: Epson Ink Level Cyan
  command: /usr/bin/curl -X GET http://epson.cbs-service.net/PRESENTATION/HTML/TOP/PRTINFO.HTML  | awk -F"'" '/Ink_C.PNG/ && $6+0 == $6 { printf "%.0f\n", $6 / 50 * 100 }'
  unit_of_measurement: '%'
  scan_interval: 60
  


