##########################
# Sensors
##########################

# Inspired by https://github.com/CCOSTAN/Home-AssistantConfig/blob/9b088e5bee97d242463b7d794edeb4a1d967bac1/sensor/devices_states.yaml
- platform: template
  sensors:
    # Inspired by https://community.home-assistant.io/t/temp-compare/19497
    out_vs_in:
      value_template: "{{states.sensor.openweathermap_temperature.state | round(0) - states.sensor.temperature_livingroom.state | round(0)}}"
      friendly_name: "Temperature Diff"

    robo:
      friendly_name: "Robo"
      value_template: "{{ 'online' if is_state('device_tracker.robot', 'home') else 'off' }}"

    epson:
      friendly_name: "Epson"
      value_template: "{{ 'online' if is_state('device_tracker.epson', 'home') else 'off' }}"

    plex:
      friendly_name: "Plex"
      value_template: "{{ 'online' if is_state('device_tracker.plex', 'home') else 'off' }}"

    switch:
      friendly_name: "Switch"
      value_template: "{{ 'online' if is_state('device_tracker.switch', 'home') else 'off' }}"

    appletv_bedroom:
      friendly_name: "AppleTV Bedroom"
      value_template: "{{ 'online' if is_state('device_tracker.appletvschlafzimmer', 'home') else 'off' }}"

    appletv_livingroom:
      friendly_name: "AppleTV Livingroom"
      value_template: "{{ 'online' if is_state('device_tracker.appletvwohnzimmer', 'home') else 'off' }}"

    server:
      friendly_name: "Server"
      value_template: "{{ 'online' if is_state('device_tracker.server', 'home') else 'off' }}"

    robot_dust_bin:
      friendly_name: "Robot dust bin"
      value_template: >
        {% if ( (is_state('input_boolean.cleaned_today', 'on')) and (is_state('group.user_1', 'home')) ) %}
        full
        {% else %}
        empty
        {% endif %}

    # energy
    energy_all_total:
      unit_of_measurement: "kWh"
      value_template: "{{ (states('sensor.energy_all_total_wh')|float / 1000 ) | round(1) }}"
      device_class: energy
      friendly_name: "WHG Total"

    energy_all_ht:
      unit_of_measurement: "kWh"
      value_template: "{{ (states('sensor.energy_all_ht_wh')|float / 1000 ) | round(1) }}"
      device_class: energy
      friendly_name: "WHG HT"

    energy_all_nt:
      unit_of_measurement: "kWh"
      value_template: "{{ (states('sensor.energy_all_nt_wh')|float / 1000 ) | round(1) }}"
      device_class: energy
      friendly_name: "WHG NT"

# - platform: command_line
#   name: Mein Schiff Ostsee
#   command: /usr/bin/curl -s https://www.pooldeck24.de/mein-schiff/mein-schiff-buchen/mein-schiff-flexpreise | grep "Ostsee mit St. Petersburg II" -A 2 | grep -o '[0-9]\.[0-9]\+' | tr -d '.'
#   unit_of_measurement: '€'
#   scan_interval: 120

- platform: time_date
  display_options:
    - 'date_time'

- platform: statistics
  name: "Rain last day"
  entity_id: sensor.rain_last_hour
  state_characteristic: total
  max_age:
    hours: 24
  sampling_size: 24
  precision: 0
