##########################
# Sensors
##########################

# Weather Prediction
- platform: darksky
  api_key: !secret dark_sky_api_password
  monitored_conditions:
    - summary
    - temperature
    - wind_speed
    - humidity
    - temperature_high
    - temperature_low
    - hourly_summary
    - precip_type
    - precip_intensity
    - precip_probability
    - cloud_cover

- platform: speedtest
  minute: 30
  hour:
    - 0
    - 6
    - 12
    - 18
  monitored_conditions:
    - download
    - upload

- platform: fritzbox_netmonitor
  host: !secret fritz_host

- platform: travisci
  api_key: !secret github_token
  repository:
    - home_assistant
  branch:
    - master
  monitored_conditions:
    - last_build_state

- platform: command_line
  name: CPU Temperature
  command: 'cat /sys/class/thermal/thermal_zone0/temp'
  unit_of_measurement: '°C'
  value_template: '{{ (value | multiply(0.001)) | round(1) }}'

- platform: systemmonitor
  resources:
  - type: disk_use_percent
    arg: /
  - type: memory_free
  - type: processor_use
  - type: network_in
    arg: eth0
  - type: network_out
    arg: eth0
  - type: last_boot

# Plant sensors
- platform: miflora
  mac: C4:7C:8D:62:B7:02
  name: Bonsai 
  force_update: false
  median: 3
  monitored_conditions:
    - moisture
    - light
    - temperature
    - conductivity
    - battery

- platform: miflora
  mac: C4:7C:8D:62:B7:30
  name: Bad
  force_update: false
  median: 3
  monitored_conditions:
    - moisture
    - light
    - temperature
    - conductivity
    - battery

- platform: miflora
  mac: C4:7C:8D:62:B8:85
  name: Palme
  force_update: false
  median: 3
  monitored_conditions:
    - moisture
    - light
    - temperature
    - conductivity
    - battery

- platform: miflora
  mac: C4:7C:8D:62:C1:9C
  name: Palmek
  force_update: false
  median: 3
  monitored_conditions:
    - moisture
    - light
    - temperature
    - conductivity
    - battery    

# Inspired by https://github.com/CCOSTAN/Home-AssistantConfig/blob/9b088e5bee97d242463b7d794edeb4a1d967bac1/sensor/devices_states.yaml
- platform: template
  sensors: 
      # Inspired by https://community.home-assistant.io/t/temp-compare/19497
      out_vs_in:
        value_template: "{{states.sensor.dark_sky_temperature.state | round(0) - states.sensor.temperature_158d00022cb65c.state | round(0)}}"
        friendly_name: "Temperature Diff"

      # Inspired by https://github.com/rytilahti/python-mirobo/issues/4   
      vacuum_status:   
       value_template: '{{ states.vacuum.vacuum_cleaner.attributes.status}}'    
       friendly_name: 'Status'   
       icon_template: mdi:comment

      door1_battery:   
       value_template: '{{ states.binary_sensor.door_window_sensor_158d0001d8253a.attributes.battery_level}}'    
       friendly_name: 'Front Door'   
       icon_template: mdi:battery

      door2_battery:   
       value_template: '{{ states.binary_sensor.door_window_sensor_158d0001b7700c.attributes.battery_level}}'    
       friendly_name: 'Balcony Door'   
       icon_template: mdi:battery

      motion1_battery:   
       value_template: '{{ states.binary_sensor.motion_sensor_158d0001a90475.attributes.battery_level}}'    
       friendly_name: 'Kitchen Motion'   
       icon_template: mdi:battery

      motion2_battery:   
       value_template: '{{ states.binary_sensor.motion_sensor_158d000121c575.attributes.battery_level}}'    
       friendly_name: 'Working Room Motion'   
       icon_template: mdi:battery

      switch1_battery:   
       value_template: '{{ states.binary_sensor.switch_158d0001d8795f.attributes.battery_level}}'    
       friendly_name: 'Switch'   
       icon_template: mdi:battery
      
      cube_battery:   
       value_template: '{{ states.binary_sensor.cube_158d0001108360.attributes.battery_level}}'    
       friendly_name: 'Cube'   
       icon_template: mdi:battery

      robo:
        friendly_name: 'Robo'
        value_template: "{{ 'online' if is_state('device_tracker.robot', 'home') else 'off' }}"

      epson:
        friendly_name: 'Epson'
        value_template: "{{ 'online' if is_state('device_tracker.epson', 'home') else 'off' }}"

      broadlink:
        friendly_name: 'Broadlink'
        value_template: "{{ 'online' if is_state('device_tracker.broadlink', 'home') else 'off' }}"

      plex:
        friendly_name: 'Plex'
        value_template: "{{ 'online' if is_state('device_tracker.plex', 'home') else 'off' }}"

      switch:
        friendly_name: 'Switch'
        value_template: "{{ 'online' if is_state('device_tracker.switch', 'home') else 'off' }}"

      tradfri:
        friendly_name: 'Tradfri Gateway'
        value_template: "{{ 'online' if is_state('device_tracker.tradfri', 'home') else 'off' }}"

      appletv_bedroom:
        friendly_name: 'AppleTV Bedroom'
        value_template: "{{ 'online' if is_state('device_tracker.appletvschlafzimmer', 'home') else 'off' }}"

      appletv_livingroom:
        friendly_name: 'AppleTV Livingroom'
        value_template: "{{ 'online' if is_state('device_tracker.appletvwohnzimmer', 'home') else 'off' }}"
        
      server:
        friendly_name: 'Server'
        value_template: "{{ 'online' if is_state('device_tracker.server', 'home') else 'off' }}"

      aqara_gateway:
        friendly_name: 'Aqara Gateway'
        value_template: "{{ 'online' if is_state('device_tracker.aqaragateway', 'home') else 'off' }}"

      sonoff_tv:
        friendly_name: 'Sonoff TV'
        value_template: "{{ 'online' if is_state('device_tracker.sonofftv', 'home') else 'off' }}"

      sonoff_tv_2:
        friendly_name: 'Sonoff TV2'
        value_template: "{{ 'online' if is_state('device_tracker.sonofftv2', 'home') else 'off' }}"

      sonoff_speaker_1:
        friendly_name: 'Sonoff Speaker 1'
        value_template: "{{ 'online' if is_state('device_tracker.sonoffspeakerlivingroom', 'home') else 'off' }}"

      sonoff_speaker_2:
        friendly_name: 'Sonoff Speaker 2'
        value_template: "{{ 'online' if is_state('device_tracker.sonoffdefault1', 'home') else 'off' }}"

      # Inspired by https://community.home-assistant.io/t/virtual-light-sensor/31975/9
      dark_outside:
        friendly_name: 'Dark Outside'
        value_template: >
          {% if (states.sensor.illumination_158d0001ff3f0a.state | int < 10) %}
          on
          {% else %}
          off
          {% endif %}

- platform: command_line
  name: Epson Ink Level Black
  command: /usr/bin/curl -s -X GET http://epson.cbs-service.net/PRESENTATION/HTML/TOP/PRTINFO.HTML  | awk -F"'" '/Ink_K.PNG/ && $6+0 == $6 { printf "%.0f\n", $6 / 50 * 100 }'
  unit_of_measurement: '%'
  scan_interval: 120

- platform: command_line
  name: Epson Ink Level Magenta
  command: /usr/bin/curl -s -X GET http://epson.cbs-service.net/PRESENTATION/HTML/TOP/PRTINFO.HTML  | awk -F"'" '/Ink_M.PNG/ && $6+0 == $6 { printf "%.0f\n", $6 / 50 * 100 }'
  unit_of_measurement: '%'
  scan_interval: 120

- platform: command_line
  name: Epson Ink Level Yellow
  command: /usr/bin/curl -s -X GET http://epson.cbs-service.net/PRESENTATION/HTML/TOP/PRTINFO.HTML  | awk -F"'" '/Ink_Y.PNG/ && $6+0 == $6 { printf "%.0f\n", $6 / 50 * 100 }'
  unit_of_measurement: '%'
  scan_interval: 120

- platform: command_line
  name: Epson Ink Level Cyan
  command: /usr/bin/curl -s -X GET http://epson.cbs-service.net/PRESENTATION/HTML/TOP/PRTINFO.HTML  | awk -F"'" '/Ink_C.PNG/ && $6+0 == $6 { printf "%.0f\n", $6 / 50 * 100 }'
  unit_of_measurement: '%'
  scan_interval: 120

- platform: command_line
  name: Mein Schiff Price
  command: /usr/bin/curl -s https://www.pooldeck24.de/mein-schiff/mein-schiff-buchen/mein-schiff-flexpreise | grep "Jungfernfahrt neue Mein Schiff" -A 2 | grep -o '[0-9]\.[0-9]\+' | tr -d '.'
  unit_of_measurement: '€'
  scan_interval: 120

- platform: luftdaten
  sensorid: 3111
  monitored_conditions:
    - P1
    - P2