##########################
# Switches
##########################

- platform: mqtt
  name: "Zigbee2mqtt Main join"
  state_topic: "zigbee2mqtt/bridge/config/permit_join"
  command_topic: "zigbee2mqtt/bridge/config/permit_join"
  payload_on: "true"
  payload_off: "false"

- platform: wake_on_lan
  name: Server
  host: server.cbs-service.net
  mac: "38-EA-A7-A3-25-F0"
  turn_off:
    service: shell_command.turn_off_server

- platform: broadlink
  host: !secret broadlink_ip
  mac: "34:EA:34:E0:BE:D5"
  friendly_name: IR Control
  type: rm_mini

- platform: template
  switches:
    tv_mode:
      value_template: "{{ is_state('input_select.tv_mode', 'TV')}}"
      turn_on:
        service: input_select.select_option
        data:
          entity_id: input_select.tv_mode
          option: TV
      turn_off:
        service: input_select.select_option
        data:
          entity_id: input_select.tv_mode
          option: AUS
    appletv_mode:
      value_template: "{{ is_state('input_select.tv_mode', 'AppleTV')}}"
      turn_on:
        service: input_select.select_option
        data:
          entity_id: input_select.tv_mode
          option: AppleTV
      turn_off:
        service: script.turn_on
        entity_id: script.turn_off_tv_livingroom
    plex_mode:
      value_template: "{{ is_state('input_select.tv_mode', 'Plex')}}"
      turn_on:
        service: input_select.select_option
        data:
          entity_id: input_select.tv_mode
          option: Plex
      turn_off:
        service: input_select.select_option
        data:
          entity_id: input_select.tv_mode
          option: AUS
    music_mode:
      value_template: "{{ is_state('input_select.tv_mode', 'Music')}}"
      turn_on:
        service: input_select.select_option
        data:
          entity_id: input_select.tv_mode
          option: Music
      turn_off:
        service: script.turn_on
        entity_id: script.turn_off_tv_livingroom
    sonos_mode:
      value_template: "{{ is_state('media_player.living_room', 'playing')}}"
      turn_on:
        service: script.turn_on
        entity_id: script.play_sonos_radio
      turn_off:
        service: script.turn_on
        entity_id: script.pause_sonos
    vacuum_mode:
      value_template: "{{ is_state('vacuum.vacuum_cleaner', 'Cleaning')}}"
      turn_on:
        service: vacuum.start
        entity_id: vacuum.vacuum_cleaner
      turn_off:
        service: vacuum.return_to_base
        entity_id: vacuum.vacuum_cleaner
    tv_media:
      turn_on:
        service: switch.turn_on
        data:
          entity_id: 
            - switch.tv
            - switch.sonos_playbar
      turn_off:
        service: switch.turn_off
        data:
          entity_id: 
            - switch.tv
            - switch.sonos_playbar

- platform: mqtt
  name: "Light Stairs"
  state_topic: "shellies/shelly1-98F4ABD0B809/relay/0"
  command_topic: "shellies/shelly1-98F4ABD0B809/relay/0/command"
  payload_on: "on"
  payload_off: "off"
  state_on: "on"
  state_off: "off"
  optimistic: false
  qos: 0
  retain: true
