##########################
# Switches
##########################

- platform: mqtt
  name: "TV"
  state_topic: "tele/sonoff/tv/1/STATE"
  value_template: "{{ value_json.POWER }}"
  command_topic: "cmnd/sonoff/tv/1/POWER"
  availability_topic: "tele/sonoff/tv/1/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: false

- platform: mqtt
  name: "TV 2"
  state_topic: "tele/sonoff/tv/2/STATE"
  value_template: "{{ value_json.POWER }}"
  command_topic: "cmnd/sonoff/tv/2/POWER"
  availability_topic: "tele/sonoff/tv/2/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: false

- platform: mqtt
  name: "Speaker 1"
  state_topic: "tele/sonoff/speaker/1/STATE"
  value_template: "{{ value_json.POWER }}"
  command_topic: "cmnd/sonoff/speaker/1/POWER"
  availability_topic: "tele/sonoff/speaker/1/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: false

- platform: mqtt
  name: "Speaker 2"
  state_topic: "tele/sonoff/speaker/2/STATE"
  value_template: "{{ value_json.POWER }}"
  command_topic: "cmnd/sonoff/speaker/2/POWER"
  availability_topic: "tele/sonoff/speaker/2/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: false

- platform: wake_on_lan
  name: Server
  host: server.cbs-service.net
  mac_address: '38-EA-A7-A3-25-F0'
  turn_off:
    service: shell_command.turn_off_server

- platform: broadlink
  host: !secret broadlink_ip
  mac: '34:EA:34:E0:BE:D5'
  friendly_name: IR Control
  type: rm_mini

- platform: rest
  resource: http://192.168.178.5:8126/container/influxdb
  name: Influxdb
  body_on: '{"state": "start"}'
  body_off: '{"state": "stop"}'
  is_on_template: '{{ value_json is not none and value_json.state == "running" }}'

- platform: rest
  resource: http://192.168.178.5:8126/container/portainer
  name: Portainer
  body_on: '{"state": "start"}'
  body_off: '{"state": "stop"}'
  is_on_template: '{{ value_json is not none and value_json.state == "running" }}'

- platform: rest
  resource: http://192.168.178.5:8126/container/mosquitto
  name: Mosquitto
  body_on: '{"state": "start"}'
  body_off: '{"state": "stop"}'
  is_on_template: '{{ value_json is not none and value_json.state == "running" }}'

- platform: rest
  resource: http://192.168.178.5:8126/container/resilio
  name: Resilio
  body_on: '{"state": "start"}'
  body_off: '{"state": "stop"}'
  is_on_template: '{{ value_json is not none and value_json.state == "running" }}'

- platform: rest
  resource: http://192.168.178.5:8126/container/grafana
  name: Grafana
  body_on: '{"state": "start"}'
  body_off: '{"state": "stop"}'
  is_on_template: '{{ value_json is not none and value_json.state == "running" }}'

- platform: rest
  resource: http://192.168.178.5:8126/container/pihole
  name: pihole
  body_on: '{"state": "start"}'
  body_off: '{"state": "stop"}'
  is_on_template: '{{ value_json is not none and value_json.state == "running" }}'

- platform: rest
  resource: http://192.168.178.5:8126/container/gitpull
  name: gitpull
  body_on: '{"state": "start"}'
  body_off: '{"state": "stop"}'
  
- platform: template
  switches:
    tv_mode:
      value_template: "{{ is_state('input_select.tv_mode', 'TV')}}"
      turn_on:
        service: input_select.select_option
        data:
          entity_id: input_select.tv_mode
          option: TV
      turn_off:
        service: input_select.select_option
        data:
          entity_id: input_select.tv_mode
          option: AUS
    appletv_mode:
      value_template: "{{ is_state('input_select.tv_mode', 'AppleTV')}}"
      turn_on:
        service: input_select.select_option
        data:
          entity_id: input_select.tv_mode
          option: AppleTV
      turn_off:
        service: input_select.select_option
        data:
          entity_id: input_select.tv_mode
          option: AUS
    plex_mode:
      value_template: "{{ is_state('input_select.tv_mode', 'Plex')}}"
      turn_on:
        service: input_select.select_option
        data:
          entity_id: input_select.tv_mode
          option: Plex
      turn_off:
        service: input_select.select_option
        data:
          entity_id: input_select.tv_mode
          option: AUS
    music_mode:
      value_template: "{{ is_state('input_select.tv_mode', 'Music')}}"
      turn_on:
        service: input_select.select_option
        data:
          entity_id: input_select.tv_mode
          option: Music
      turn_off:
        service: input_select.select_option
        data:
          entity_id: input_select.tv_mode
          option: AUS
    sonos_mode:
      value_template: "{{ is_state('media_player.living_room', 'playing')}}"
      turn_on:
        service: script.turn_on
        entity_id: script.play_sonos_radio
      turn_off:
        service: script.turn_on
        entity_id: script.pause_sonos
    vacuum_mode:
      value_template: "{{ is_state('vacuum.vacuum_cleaner', 'cleaning')}}"
      turn_on:
        service: vacuum.start
        entity_id: vacuum.vacuum_cleaner
      turn_off:
        service: vacuum.stop
        entity_id: vacuum.vacuum_cleaner
    heating_living_room:
      value_template: "{{ is_state('climate.living_room', 'heat')}}"
      turn_on:
        service: script.turn_on
        entity_id: script.turn_on_heating_living_room
      turn_off:
        service: script.turn_on
        entity_id: script.turn_off_heating_living_room
    heating_bath_room:
      value_template: "{{ is_state('climate.bath', 'heat')}}"
      turn_on:
        service: script.turn_on
        entity_id: script.turn_on_heating_bath_room
      turn_off:
        service: script.turn_on
        entity_id: script.turn_off_heating_bath_room

- platform: flux
  lights:
    - light.living_room_lights