##########################
# Switches
##########################

- platform: mqtt
  name: "Zigbee2mqtt Main join"
  state_topic: "zigbee2mqtt/bridge/config/permit_join"
  command_topic: "zigbee2mqtt/bridge/config/permit_join"
  payload_on: "true"
  payload_off: "false"

- platform: wake_on_lan
  name: Server
  host: server.cbs-service.net
  mac: "38-EA-A7-A3-25-F0"
  turn_off:
    service: shell_command.turn_off_server

- platform: template
  switches:
    vacuum_mode:
      value_template: "{{ is_state('vacuum.vacuum_cleaner', 'Cleaning')}}"
      turn_on:
        service: vacuum.start
        entity_id: vacuum.vacuum_cleaner
      turn_off:
        service: vacuum.return_to_base
        entity_id: vacuum.vacuum_cleaner
    tv_media:
      value_template: "{{ is_state('switch.tv', 'on')}}"
      turn_on:
        service: script.turn_on_tv
      turn_off:
        service: switch.turn_off
        data:
          entity_id:
            - switch.tv
            - switch.sonos_playbar
    cover_coach:
      value_template: "{{ state_attr('cover.livingroom_coach_left', 'current_position') == 50 }}"
      turn_off:
        - service: cover.open_cover
          entity_id:
            - cover.livingroom_coach_left
            - cover.livingroom_coach_right
      turn_on:
        - service: cover.set_cover_position
          data:
            entity_id:
              - cover.livingroom_coach_right
              - cover.livingroom_coach_left
            position: 50
