##########################
# Switches
##########################
    
- platform: command_line
  switches:
    light_tv:
      command_on: "sudo /opt/rcswitch-pi/send 11111 2 1"
      command_off: "sudo /opt/rcswitch-pi/send 11111 2 0"
      friendly_name: Lampe Fernseher
    tv:
      command_on: "sudo /opt/rcswitch-pi/send 11111 1 1"
      command_off: "sudo /opt/rcswitch-pi/send 11111 1 0"
      friendly_name: Fernseher
    light_sofa:
      command_on: "sudo /opt/rcswitch-pi/send 11111 4 1"
      command_off: "sudo /opt/rcswitch-pi/send 11111 4 0"
      friendly_name: Lampe Sofa
    light_sessel:
      command_on: "sudo /opt/rcswitch-pi/send 11111 3 1"
      command_off: "sudo /opt/rcswitch-pi/send 11111 3 0"
      friendly_name: Lampe Sessel
    light_stern:
      command_on: "sudo /opt/rcswitch-pi/send 11110 3 1"
      command_off: "sudo /opt/rcswitch-pi/send 11110 3 0"
      friendly_name: Stern
    light_baum:
      command_on: "sudo /opt/rcswitch-pi/send 11110 4 1"
      command_off: "sudo /opt/rcswitch-pi/send 11110 4 0"
      friendly_name: Weihnachtsbaum    
    tv_2:
      command_on: "sudo /opt/rcswitch-pi/send 11001 1 1"
      command_off: "sudo /opt/rcswitch-pi/send 11001 1 0"
      friendly_name: Fernseher 2
    light_nicole:
      command_on: "sudo /opt/rcswitch-pi/send 11001 2 1"
      command_off: "sudo /opt/rcswitch-pi/send 11001 2 0"
      friendly_name: Lampe Nicole
    light_sascha:
      command_on: "sudo /opt/rcswitch-pi/send 11001 3 1"
      command_off: "sudo /opt/rcswitch-pi/send 11001 3 0"
      friendly_name: Lampe Sascha
- platform: wake_on_lan
  name: Server
  host: server.cbs-service.net
  mac_address: "38-EA-A7-A3-25-F0"
  turn_off:
    service: shell_command.turn_off_server
- platform: broadlink
  host: 192.168.178.51
  mac: '34:EA:34:E0:BE:D5'
  friendly_name: IR Control
  type: rm_mini
  switches:
     tv:
      friendly_name: "Samsung TV"
      command_on: 'JgDSAJWTFDYTNhQ2ExETEhMRExETEhM2FDYTNhQRExETERQRExETERQ2ExEUERMRExEUERMREzcTERM3EzYUNhM2EzcTNhQABf6WkhU1FDUUNhQRExETERMSExETNhQ2FDYTERMRFBETERMRFBETNhQRExEUERMRExETEhM2FBAUNhQ1FDYUNhM2FDYTAAXgDSAJWTFDYTNhQ2ExETEhMRExETEhM2FDYTNhQRExETERQRExETERQ2ExEUERMRExEUERMREzcTERM3EzYUNhM2EzcTNhQABf6WkhU1FDUUNhQRExETERMSExETNhQ2FDYTERMRFBETERMRFBETNhQRExEUERMRExETEhM2FBAUNhQ1FDYUNhM2FDYTAAX='
      command_off: 'JgDSAJWTFDYTNhQ2ExETEhMRExETEhM2FDYTNhQRExETERQRExETERQ2ExEUERMRExEUERMREzcTERM3EzYUNhM2EzcTNhQABf6WkhU1FDUUNhQRExETERMSExETNhQ2FDYTERMRFBETERMRFBETNhQRExEUERMRExETEhM2FBAUNhQ1FDYUNhM2FDYTAAXgDSAJWTFDYTNhQ2ExETEhMRExETEhM2FDYTNhQRExETERQRExETERQ2ExEUERMRExEUERMREzcTERM3EzYUNhM2EzcTNhQABf6WkhU1FDUUNhQRExETERMSExETNhQ2FDYTERMRFBETERMRFBETNhQRExEUERMRExETEhM2FBAUNhQ1FDYUNhM2FDYTAAX='


